#!/usr/bin/env python3
"""
eden_build.py — derives the three dashboard embeds from eden/eden-catalog.json.

Read-only against eden-catalog.json. Writes to dashboard/dashboard.html via
safe_write to update three embedded JSON blocks:

  1. <script type="application/json" id="regimen-label-lookup">...</script>
     — slim per-product label data keyed by canonical_name
  2. <script type="application/json" id="goal-recommendations-data">...</script>
     — goal_to_products + product_pricing + user_stated_goals
  3. REGIMEN_BASE_DATA.recommended array inside the canonical JS block
     — HBSP trio (tiers.hbsp_default)

All three embeds carry the same eden_version field — the boot-time
verifier in dashboard.html will reject any drift.

Run after every eden_seal.py invocation. Agent (Claude) MAY run this tool;
all dashboard writes go through tools/safe_write.py.

Exit codes:
  0 — build complete, embeds updated, integrity check passed
  1 — failure (catalog invalid, write failure, integrity drift)
  2 — Eden in BOOTSTRAP state, no build attempted
"""

import datetime
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
EDEN_DIR = ROOT / "eden"
CATALOG_PATH = EDEN_DIR / "eden-catalog.json"
GOLDEN_PATH = EDEN_DIR / "eden-catalog.golden.sha256"
DASHBOARD_PATH = ROOT / "dashboard" / "dashboard.html"
SAFE_WRITE = ROOT / "tools" / "safe_write.py"


def is_bootstrap() -> bool:
    if not GOLDEN_PATH.exists():
        return True
    golden = GOLDEN_PATH.read_text(encoding="utf-8").strip()
    return golden in ("", "BOOTSTRAP-PLACEHOLDER-PRE-SEAL")


def load_catalog() -> dict:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def derive_regimen_label_lookup(catalog: dict) -> dict:
    """Build the regimen-label-lookup embed — slim per-product data keyed by
    canonical_name (NOT the EDEN-LOCKED ID) for backwards-compat with existing
    dashboard lookups by name. Includes nutrient panels + serving + pricing.

    Note: keying by canonical_name preserves the existing dashboard contract
    where label lookups are name-based. The EDEN-LOCKED ID is added as an
    eden_id field so consumers can cross-reference.
    """
    products = catalog.get("products", {})
    out = {
        "_meta": {
            "purpose": "Eden-derived regimen label lookup. Generated by eden/tools/eden_build.py from eden-catalog.json.",
            "eden_version": catalog.get("eden_version"),
            "sealed_at": catalog.get("sealed_at"),
            "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        },
        "products": {},
    }
    for eden_id, prod in products.items():
        name = prod.get("canonical_name")
        if not name:
            continue
        out["products"][name] = {
            "eden_id": eden_id,
            "canonical_name": name,
            "brand": prod.get("brand"),
            "brand_tier": prod.get("brand_tier"),
            "category": prod.get("category_label", ""),
            "serving_size": prod.get("serving_size", ""),
            "servings_per_container": prod.get("servings_per_container"),
            "dose_text": prod.get("dose_text", ""),
            "nutrients": prod.get("nutrients", []),
            "non_essentials_parsed": prod.get("non_essentials", []),
            "features": prod.get("features", []),
            "what_it_does": prod.get("what_it_does", ""),
            "tagline": prod.get("tagline", ""),
        }
    return out


def derive_goal_recommendations_data(catalog: dict) -> dict:
    """Build the goal-recommendations-data embed.

    Shape (kept compatible with existing engine consumer):
      {
        schema_version,
        _purpose, _round, _eden_version,
        user_stated_goals: [],
        goal_to_products: { <goal_key>: [{product, category, tagline}, ...] },
        product_pricing: { <product_name>: {retail, servings_per_container, daily_cost_at_1_serving, category} }
      }
    """
    products = catalog.get("products", {})
    goals = catalog.get("goals", {})

    goal_to_products = {gkey: [] for gkey in goals.keys()}
    product_pricing = {}

    for eden_id, prod in products.items():
        name = prod.get("canonical_name")
        if not name:
            continue
        category = prod.get("category_label", "")
        tagline = prod.get("tagline", "") or prod.get("what_it_does", "")
        for gkey in prod.get("goals", []):
            if gkey in goal_to_products:
                goal_to_products[gkey].append({
                    "product": name,
                    "category": category,
                    "tagline": tagline,
                    "eden_id": eden_id,
                })
        pricing = prod.get("pricing", {})
        if pricing and pricing.get("daily_cost_at_1_serving") is not None:
            product_pricing[name] = {
                "retail": pricing.get("retail"),
                "servings_per_container": prod.get("servings_per_container"),
                "daily_cost_at_1_serving": pricing.get("daily_cost_at_1_serving"),
                "category": category,
                "eden_id": eden_id,
            }

    return {
        "schema_version": 1,
        "_purpose": "Eden-derived goal-recommendations data. Generated by eden/tools/eden_build.py.",
        "_eden_version": catalog.get("eden_version"),
        "_sealed_at": catalog.get("sealed_at"),
        "_generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "user_stated_goals": [],
        "goal_to_products": goal_to_products,
        "product_pricing": product_pricing,
    }


def derive_regimen_base_data_recommended(catalog: dict) -> list:
    """Build the REGIMEN_BASE_DATA.recommended array from tiers.hbsp_default.

    Each entry follows the legacy item shape so existing dashboard
    rendering doesn't need changes:
      { id, name, kind, source, dose_text, scaling_factor, notes,
        actual_range, timing, category, what_it_does, nutrients }

    The id is the EDEN-LOCKED-* id (the dashboard's stale stk_* IDs
    are migrated away).
    """
    products = catalog.get("products", {})
    hbsp_ids = catalog.get("tiers", {}).get("hbsp_default", [])
    out = []
    for eden_id in hbsp_ids:
        prod = products.get(eden_id)
        if not prod:
            continue
        out.append({
            "id": eden_id,
            "name": prod.get("canonical_name"),
            "kind": "recommended",
            "source": "wallach_hbsp_default",
            "dose_text": prod.get("dose_text", ""),
            "scaling_factor": 1.0,
            "notes": prod.get("notes", ""),
            "actual_range": "",
            "timing": "",
            "category": prod.get("category_label", ""),
            "what_it_does": prod.get("what_it_does", ""),
            "nutrients": prod.get("nutrients", []),
            "has_nutrient_data": isinstance(prod.get("nutrients"), list) and len(prod.get("nutrients", [])) > 0,
            "_eden_id": eden_id,
            "_eden_version": catalog.get("eden_version"),
        })
    return out


def main() -> int:
    if is_bootstrap():
        print("BOOTSTRAP: Eden golden hash is the placeholder. Run eden_seal.py first.")
        return 2

    if not CATALOG_PATH.exists():
        print(f"FAIL: catalog file missing: {CATALOG_PATH}", file=sys.stderr)
        return 1

    try:
        catalog = load_catalog()
    except json.JSONDecodeError as e:
        print(f"FAIL: catalog JSON parse error: {e}", file=sys.stderr)
        return 1

    # Derive the three embeds
    embed_lookup = derive_regimen_label_lookup(catalog)
    embed_goal_recs = derive_goal_recommendations_data(catalog)
    embed_hbsp = derive_regimen_base_data_recommended(catalog)

    print(f"BUILD: Eden eden_version={catalog.get('eden_version')}")
    print(f"  regimen-label-lookup: {len(embed_lookup['products'])} products")
    print(f"  goal-recommendations-data: {sum(len(v) for v in embed_goal_recs['goal_to_products'].values())} goal-product entries; {len(embed_goal_recs['product_pricing'])} pricing entries")
    print(f"  REGIMEN_BASE_DATA.recommended: {len(embed_hbsp)} HBSP item(s)")
    print()
    print("NOTE: Phase E (Chunk F) will wire the embed writes into dashboard.html via safe_write.")
    print("      This skeleton run derives the embed JSON without modifying dashboard.html yet.")
    print()
    # Emit derived embeds as separate JSON files for review during Phase E build
    out_dir = EDEN_DIR / "derived"
    out_dir.mkdir(exist_ok=True)
    (out_dir / "regimen-label-lookup.json").write_text(json.dumps(embed_lookup, indent=2), encoding="utf-8")
    (out_dir / "goal-recommendations-data.json").write_text(json.dumps(embed_goal_recs, indent=2), encoding="utf-8")
    (out_dir / "regimen-base-data-recommended.json").write_text(json.dumps(embed_hbsp, indent=2), encoding="utf-8")
    print(f"Derived embeds written to {out_dir}/ for review.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
