/**
 * state/corpus.ts — read boundary for the sealed Wallach claim graph
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces the eden/corpus claim graph to the views. The offline file:// app
 * cannot fetch(), so the slim embed (dashboard/assets/data/corpus-embed.json,
 * generated by eden/tools/corpus_embed.py) is inlined at build via esbuild JSON
 * import. It is validated ONCE through the Zod boundary; a bad/absent embed reads
 * as an empty corpus so the drawer degrades gracefully instead of throwing.
 *
 * Pure reads only — no mutation, no localStorage. The corpus is canonical,
 * sealed, hash-anchored truth; this module never writes it.
 *
 * §00.A: every claim here traces to a Wallach allowlist primary (the book id on
 * each claim), so surfacing them is the educational layer the source rule blesses.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import corpusEmbed from '../../../data/corpus-embed.json';
import {
  type CorpusBook,
  type CorpusClaim,
  type CorpusCondition,
  type CorpusEmbed,
  CorpusEmbedSchema,
  type CorpusEssential,
  type CorpusPlannedBook,
} from '../core/schemas/index.js';

const EMPTY_CORPUS: CorpusEmbed = {
  knowledge_version: 0,
  books: {},
  planned_books: [],
  essentials: {},
  conditions: {},
  claims: {},
};

let cached: CorpusEmbed | null = null;

/** The validated corpus embed (parsed once; bad/absent embed → empty). */
function corpus(): CorpusEmbed {
  if (cached === null) {
    const parsed = CorpusEmbedSchema.safeParse(corpusEmbed);
    cached = parsed.success ? parsed.data : EMPTY_CORPUS;
  }
  return cached;
}

/** The sealed knowledge_version stamped into the embed (0 if unloaded). */
export function knowledgeVersion(): number {
  return corpus().knowledge_version;
}

/** A single claim atom by id, or null if absent. */
export function getClaim(id: string): CorpusClaim | null {
  return corpus().claims[id] ?? null;
}

/**
 * Every TIER-1 claim of one book, in stable id order — the book browser's data.
 * Tier-2 (search-only) claims are held back here too: they are excluded from the
 * operational indices and stay reserved for the future Ask-Wallach search, so a
 * plain book browse must not surface them.
 */
export function getClaimsForBook(bookId: string): CorpusClaim[] {
  return Object.values(corpus().claims)
    .filter(c => c.book === bookId && (c.tier ?? 1) === 1)
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** Resolve a list of claim ids to atoms, dropping any unknown id (stable order). */
export function resolveClaims(ids: readonly string[]): CorpusClaim[] {
  const out: CorpusClaim[] = [];
  for (const id of ids) {
    const c = getClaim(id);
    if (c !== null) {
      out.push(c);
    }
  }
  return out;
}

/** An essential entry by canon slug (e.g. 'magnesium', 'vitamin-a'). */
export function getEssentialBySlug(slug: string): CorpusEssential | null {
  return corpus().essentials[slug] ?? null;
}

let layoutKeyToSlug: Map<string, string> | null = null;

/** layout_key → slug index (built once) — the Coverage periodic-table join. */
function layoutIndex(): Map<string, string> {
  if (layoutKeyToSlug === null) {
    layoutKeyToSlug = new Map<string, string>();
    for (const e of Object.values(corpus().essentials)) {
      layoutKeyToSlug.set(e.layout_key, e.slug);
    }
  }
  return layoutKeyToSlug;
}

/**
 * An essential entry by the Coverage-layout key the Knowledge view holds
 * (e.g. 'Magnesium', 'Vitamin A (Retinol / beta-carotene)'). Null if unmapped.
 */
export function getEssentialByLayoutKey(layoutKey: string): CorpusEssential | null {
  const slug = layoutIndex().get(layoutKey);
  return slug !== undefined ? getEssentialBySlug(slug) : null;
}

/** A condition entry by slug (e.g. 'angina', 'diabetes'). */
export function getCondition(slug: string): CorpusCondition | null {
  return corpus().conditions[slug] ?? null;
}

/** All condition entries (insertion order = derived alphabetical). */
export function listConditions(): CorpusCondition[] {
  return Object.values(corpus().conditions);
}

/** Display name for a condition slug, humanized fallback if absent from corpus. */
export function conditionDisplayName(slug: string): string {
  return getCondition(slug)?.display_name ?? humanizeSlug(slug);
}

/** Display name for an essential slug, slug fallback if absent. */
export function essentialDisplayName(slug: string): string {
  return getEssentialBySlug(slug)?.display_name ?? humanizeSlug(slug);
}

/** snake_case / kebab-case slug → Title Case label. */
export function humanizeSlug(slug: string): string {
  return slug
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

/** Citation label for a book id — "Title (3rd ed. 2011)" or the id if unknown. */
export function getBookLabel(bookId: string): string {
  const b = corpus().books[bookId];
  if (b === undefined) {
    return bookId;
  }
  const ed = (b.edition !== undefined && b.edition !== null && b.edition.length > 0) ? `${b.edition} ed.` : '';
  const yr = (b.year !== undefined && b.year !== null) ? String(b.year) : '';
  const tail = [ed, yr].filter(s => s.length > 0).join(' ');
  return tail.length > 0 ? `${b.title} (${tail})` : b.title;
}

/** All in-housed books, newest first (release year desc, then title). */
export function listBooks(): CorpusBook[] {
  const yearOf = (b: CorpusBook): number => {
    const y = typeof b.year === 'number' ? b.year : Number.parseInt(String(b.year ?? ''), 10);
    return Number.isNaN(y) ? -Infinity : y;
  };
  return Object.values(corpus().books).sort((a, b) => {
    const ya = yearOf(a);
    const yb = yearOf(b);
    if (ya !== yb) {
      return yb - ya;
    }
    return a.title < b.title ? -1 : a.title > b.title ? 1 : 0;
  });
}

/**
 * Books paired with their corpus id (the embed keys `books` by id, which
 * `listBooks` drops). The book browser needs the id to join to claims via
 * `getClaimsForBook`. Same newest-first ordering as `listBooks`.
 */
export function listBooksWithId(): Array<CorpusBook & { book_id: string }> {
  return Object.entries(corpus().books)
    .map(([book_id, b]) => ({ ...b, book_id }))
    .sort((a, b) => {
      const ya = typeof a.year === 'number' ? a.year : Number.parseInt(String(a.year ?? ''), 10);
      const yb = typeof b.year === 'number' ? b.year : Number.parseInt(String(b.year ?? ''), 10);
      const na = Number.isNaN(ya) ? -Infinity : ya;
      const nb = Number.isNaN(yb) ? -Infinity : yb;
      if (na !== nb) {
        return nb - na;
      }
      return a.title < b.title ? -1 : a.title > b.title ? 1 : 0;
    });
}

/** Planned (not-yet-in-housed) books — shown 'coming soon' in the Corpus tab. */
export function listPlannedBooks(): CorpusPlannedBook[] {
  return corpus().planned_books;
}
