/**
 * state/corpus.ts — read boundary for the sealed Wallach claim graph
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces the eden/corpus claim graph to the views. The offline file:// app
 * cannot fetch(), so the slim embed (dashboard/assets/data/corpus-embed.json,
 * generated by eden/tools/corpus_embed.py) is inlined at build via esbuild JSON
 * import. It is validated ONCE through the Zod boundary; a bad/absent embed reads
 * as an empty corpus so the drawer degrades gracefully instead of throwing.
 *
 * Pure reads only — no mutation, no localStorage. The corpus is canonical,
 * sealed, hash-anchored truth; this module never writes it.
 *
 * §00.A: every claim here traces to a Wallach allowlist primary (the book id on
 * each claim), so surfacing them is the educational layer the source rule blesses.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import corpusEmbed from '../../../data/corpus-embed.json';
import {
  type CorpusBook,
  type CorpusClaim,
  type CorpusCondition,
  type CorpusEmbed,
  CorpusEmbedSchema,
  type CorpusEssential,
} from '../core/schemas/index.js';

const EMPTY_CORPUS: CorpusEmbed = {
  knowledge_version: 0,
  books: {},
  planned_books: [],
  essentials: {},
  conditions: {},
  umbrellas: {},
  claims: {},
};

let cached: CorpusEmbed | null = null;

/** The validated corpus embed (parsed once; bad/absent embed → empty). */
function corpus(): CorpusEmbed {
  if (cached === null) {
    const parsed = CorpusEmbedSchema.safeParse(corpusEmbed);
    cached = parsed.success ? parsed.data : EMPTY_CORPUS;
  }
  return cached;
}

/** The sealed knowledge_version stamped into the embed (0 if unloaded). */
export function knowledgeVersion(): number {
  return corpus().knowledge_version;
}

/**
 * How many sealed claims the shipped corpus carries — the rail's "Corpus · N entries".
 *
 * ★ DERIVED, NEVER TYPED. The demo hardcoded "1,358" because it is a static mockup, with a
 * warning that it MUST derive in live: a count that is true today and frozen forever is a
 * lie with a delay, which is exactly what "EDEN v1 · sealed 8E594A01" was.
 *
 * ★ IT IS A COUNT, NOT THE SEAL VERSION. Luneth first picked "CORPUS · 336 ENTRIES" off an
 * ambiguous label — 336 was the knowledge_version (it bumps on every re-seal), not a number
 * of anything. Do not relabel a version as a count. That is what knowledgeVersion() is for.
 */
export function claimCount(): number {
  return Object.keys(corpus().claims).length;
}

/** A single claim atom by id, or null if absent. */
export function getClaim(id: string): CorpusClaim | null {
  return corpus().claims[id] ?? null;
}

/** Resolve a list of claim ids to atoms, dropping any unknown id (stable order). */
export function resolveClaims(ids: readonly string[]): CorpusClaim[] {
  const out: CorpusClaim[] = [];
  for (const id of ids) {
    const c = getClaim(id);
    if (c !== null) {
      out.push(c);
    }
  }
  return out;
}

/** An essential entry by canon slug (e.g. 'magnesium', 'vitamin-a'). */
export function getEssentialBySlug(slug: string): CorpusEssential | null {
  return corpus().essentials[slug] ?? null;
}

let layoutKeyToSlug: Map<string, string> | null = null;

/** layout_key → slug index (built once) — the Coverage periodic-table join. */
function layoutIndex(): Map<string, string> {
  if (layoutKeyToSlug === null) {
    layoutKeyToSlug = new Map<string, string>();
    for (const e of Object.values(corpus().essentials)) {
      layoutKeyToSlug.set(e.layout_key, e.slug);
    }
  }
  return layoutKeyToSlug;
}

/**
 * An essential entry by the Coverage-layout key the Knowledge view holds
 * (e.g. 'Magnesium', 'Vitamin A (Retinol / beta-carotene)'). Null if unmapped.
 */
export function getEssentialByLayoutKey(layoutKey: string): CorpusEssential | null {
  const slug = layoutIndex().get(layoutKey);
  return slug !== undefined ? getEssentialBySlug(slug) : null;
}

/** A condition entry by slug (e.g. 'angina', 'diabetes'). */
export function getCondition(slug: string): CorpusCondition | null {
  return corpus().conditions[slug] ?? null;
}

/** All condition entries (insertion order = derived alphabetical). */
export function listConditions(): CorpusCondition[] {
  return Object.values(corpus().conditions);
}

/**
 * Example child-subtype display names for an UMBRELLA condition (e.g. 'cancer' ->
 * ['Breast Cancer', 'Colon Cancer', ...]), most-cited subtype first. Empty array
 * when the slug is not a registered umbrella. Drives the condition deep-view "broad
 * category" tip; source is the taxonomy flowed into the embed by corpus_embed.py.
 */
export function umbrellaChildren(slug: string): string[] {
  return corpus().umbrellas?.[slug] ?? [];
}

/** Display name for a condition slug, humanized fallback if absent from corpus. */
export function conditionDisplayName(slug: string): string {
  return getCondition(slug)?.display_name ?? humanizeSlug(slug);
}

/** Friendly display name for an essential slug (common_name), else scientific, else slug. */
export function essentialDisplayName(slug: string): string {
  const e = getEssentialBySlug(slug);
  return e?.common_name ?? e?.display_name ?? humanizeSlug(slug);
}

/** snake_case / kebab-case slug → Title Case label. */
export function humanizeSlug(slug: string): string {
  return slug
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

/** Citation label for a book id — "Title (3rd ed. 2011)" or the id if unknown. */
export function getBookLabel(bookId: string): string {
  const b = corpus().books[bookId];
  if (b === undefined) {
    return bookId;
  }
  const ed = (b.edition !== undefined && b.edition !== null && b.edition.length > 0) ? `${b.edition} ed.` : '';
  const yr = (b.year !== undefined && b.year !== null) ? String(b.year) : '';
  const tail = [ed, yr].filter(s => s.length > 0).join(' ');
  return tail.length > 0 ? `${b.title} (${tail})` : b.title;
}

/** All in-housed books, newest first (release year desc, then title). */
export function listBooks(): CorpusBook[] {
  const yearOf = (b: CorpusBook): number => {
    const y = typeof b.year === 'number' ? b.year : Number.parseInt(String(b.year ?? ''), 10);
    return Number.isNaN(y) ? -Infinity : y;
  };
  return Object.values(corpus().books).sort((a, b) => {
    const ya = yearOf(a);
    const yb = yearOf(b);
    if (ya !== yb) {
      return yb - ya;
    }
    return a.title < b.title ? -1 : a.title > b.title ? 1 : 0;
  });
}
