/**
 * state/coverage.ts — periodic-table coverage state + live classifier
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Owns the answer to "which of the 90 essentials does the active regimen
 * cover, and how heavily." Builds a typed CoverageSnapshot keyed by the
 * canonical essential name — the single source of the live numbers consumed by
 * views/coverage.ts (hero count + per-section counts + per-tile status). The
 * layout (coverage-layout-data.json) joins to this snapshot via each tile's
 * `key` field, which equals the essential `name` here.
 *
 * DATA SOURCE:
 *   The essentials come from `essentials-targets-data.json` — the Wallach
 *   targets DB GENERATED by eden/tools/targets_derive.py from the sealed
 *   pillars (numeric targets are Wallach dose claims, R2). Inlined at build
 *   via esbuild JSON import + validated through Zod at the boundary. Each entry
 *   carries its canon `slug` — the join key to the registry resolver below.
 *
 * LIVE CLASSIFIER:
 *   The math lives here (the page loads no legacy JS). Every NUMBER still comes
 *   from Luneth's data (target.low/unit from the targets DB; nutrient amounts
 *   from regimen item labels). Nothing is invented; §00.A holds.
 *
 *   IDENTITY (A2, 2026-07-08): which essential a label nutrient credits is
 *   resolved by the ONE registry resolver — core/nutrient-resolver.ts::resolveSlug,
 *   a faithful port of eden/tools/nutrient_resolve.py, proven equal by the
 *   nutrient_resolver_parity invariant + a vitest. It returns a canon slug; each
 *   target carries its slug, so the join is a direct slug key (no display-name
 *   string-matching). This replaced a hand-rolled matcher that disagreed with the
 *   registry (e.g. it silently dropped "Thiamin" → Vitamin B1).
 *
 *   UNITS (Phase G-1): mcg/mg unify into one mg-family. The A/D/E targets are now
 *   METRIC (mcg RAE / mcg / mg) to match Youngevity's product units (the goal↔product
 *   alignment Luneth asked for). RESIDUAL: no target is IU-family anymore, so a product
 *   that still lists A/D/E in IU lands in the (now unused) totalIU accumulator and does
 *   NOT count toward its metric target (~7 products) — closeable by converting per-vitamin
 *   IU→mcg in toMg (needs the nutrient identity). Full canonical-unit unification stays a
 *   later chunk.
 *
 *   Pipeline: collect the active regimen (the migrated §31 state — committed +
 *   manual items, minus removed, with override scaling) → resolve each label
 *   nutrient to a canon slug + sum into the target's per-essential mg/IU totals
 *   (unit-convert + scale) → classify each essential against its Wallach target.
 *   The PDM aggregate-vehicle rule (trace_pdm): a trace_pdm mineral is `trace`
 *   (covered by presence) iff a plant-derived-mineral vehicle is in the stack —
 *   binary, not graduated.
 *
 *   Faithful to legacy thresholds (numeric: ok ≥ 0.95·low, warn ≥ 0.30·low,
 *   else gap) with ONE deliberate deviation: a numeric target with low ≤ 0 and
 *   zero delivery reports '' (pending) rather than legacy's 'ok' — legacy would
 *   mark it covered with nothing delivered, an §00.A overclaim.
 *
 *   Status buckets map legacy → view: ok→covered (numeric) / trace (trace_pdm),
 *   warn→partial, gap→gap, diet→covered, mute→'' (pending, rendered grey).
 *   Empty regimen ⇒ numeric targets are `gap`, the rest pending — the truthful
 *   bare state. recompute() re-runs on every `regimen:changed`.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import coverageLayoutData from '../../../data/coverage-layout-data.json';
import essentialsTargetsData from '../../../data/essentials-targets-data.json';
import { emit, on } from '../core/events.js';
import { resolveSlug } from '../core/nutrient-resolver.js';
import {
  CoverageLayoutSchema,
  type CoverageTarget,
  CoverageTargetSchema,
  type Essential,
  EssentialsDataSchema,
  type LayoutTile,
  RegimenNutrientSchema,
} from '../core/schemas/index.js';
import { onChange } from '../core/storage.js';
import {
  loadEffectiveRegimen,
  loadRgOverrides,
  type OverridesMap,
  type RegimenItem,
} from './regimen.js';

export type TileId = string;

export type TileCategory =
  | 'foundational'
  | 'major-trace'
  | 'rare-trace'
  | 'vitamins'
  | 'aminos'
  | 'fatty-acids'
  | 'other';

/** Live status bucket for one essential. '' = pending / no target (rendered grey). */
export type CoverageStatus = 'covered' | 'partial' | 'trace' | 'gap' | '';

export interface CoverageTile {
  tileId: TileId;
  category: TileCategory;
  symbol: string;
  name: string;
  /** Authoritative live bucket — views render this directly (no re-derivation). */
  status: CoverageStatus;
  /** Convenience flag: status is `covered` or `trace` (covered-by-presence). */
  covered: boolean;
  /** Ratio of Wallach target met (0..>1, can exceed 1 with stacking; 1 for trace/dietary). */
  fillPercent: number;
  /** Regimen item display names contributing to this tile. */
  coveredBy: string[];
  /** Whether this tile is closed via the PDM aggregate-vehicle rule. */
  aggregateVehicle: boolean;
  /**
   * Numeric intake-vs-Wallach-target readout for the deep-dive meter, in the
   * target's own display unit. `null` when the target is non-numeric (trace /
   * dietary / collective) -- there Wallach states no number, so the covered/
   * not-covered pill is the only honest readout and the view falls back to it.
   */
  intakeVsTarget: {
    deliveredAmount: number;
    targetLow: number;
    targetHigh: number;
    unit: string;
  } | null;
}

export interface CoverageSnapshot {
  tiles: CoverageTile[];
  coveredCount: number;
  totalCount: number;
  computedAt: string;
  /** Counts by category for the workspace section heads. */
  byCategory: { [K in TileCategory]?: { total: number; covered: number } };
}

// ─── Category + id helpers ─────────────────────────────────────────────────

/**
 * Map the targets-DB coarse category to our TileCategory. Mineral subsection
 * granularity (foundational / major-trace / rare-trace) lives in the layout,
 * not the targets DB, so minerals collapse to `other` here — `byCategory` is a
 * tally aid, not a render source (views read the layout for section grouping).
 */
function catFromTarget(raw: string): TileCategory {
  switch (raw) {
    case 'vitamins':
      return 'vitamins';
    case 'amino_acids':
      return 'aminos';
    case 'fatty_acids':
      return 'fatty-acids';
    default:
      return 'other';
  }
}

function buildTileId(name: string): TileId {
  return `tile_${name.toLowerCase().replace(/\W+/g, '_')}`;
}

// ─── Essential membership — single source for the "90" count ───────────────

/**
 * The periodic-table presentation layout. Single source for which essentials
 * exist and which count toward Wallach's 90: a tile flagged `essential: false`
 * (Omega-9 / oleic — body-synthesizable) is shown for completeness but NOT
 * counted. The targets-DB embed carries the per-essential dose; the layout
 * carries essentiality. §00.A: the count traces to Wallach's "90 Essential
 * Nutrients" enumeration (60 minerals + 16 vitamins + 12 amino acids + 2 EFAs).
 */
const LAYOUT = CoverageLayoutSchema.parse(coverageLayoutData);

function layoutTiles(): readonly LayoutTile[] {
  return LAYOUT.sections.flatMap(s =>
    s.subsections !== undefined
      ? s.subsections.flatMap(sub => sub.tiles)
      : (s.tiles ?? []),
  );
}

/** Canonical names the layout marks non-essential — excluded from the count. */
const NON_ESSENTIAL_NAMES: ReadonlySet<string> = new Set(
  layoutTiles().filter(t => t.essential === false).map(t => t.key),
);

/** Count of Wallach essentials (layout tiles where `essential !== false`) — 90. */
export function essentialCount(): number {
  return layoutTiles().filter(t => t.essential !== false).length;
}

// ─── Targets DB read (Zod-validated at the boundary) ───────────────────────

/** Zod-validate the build-inlined Wallach targets DB (`{ essentials: [...] }`). */
function readTargets(): Essential[] {
  const result = EssentialsDataSchema.safeParse(essentialsTargetsData);
  return result.success ? result.data.essentials : [];
}

// ─── Unit conversion (delivery vs. Wallach target, in the target's unit) ───

/** Convert an amount to a common unit. Faithful legacy `toMg`: IU stays IU. */
// IU→mg for the three fat-soluble vitamins that labels/Wallach state in IU. MUST mirror
// eden/tools/targets_derive.py IU_CONVERSIONS: the A/D/E TARGET is derived there in mcg/mg,
// so a product listing them in IU has to use the SAME physical factor to land in the same
// mg-family the target lives in (§00.B #3 — one conversion truth across the Python/TS line).
// Values are IU→mg: retinol/beta-carotene 0.3 mcg RAE/IU ÷1000; D 0.025 mcg/IU ÷1000; E 0.67 mg/IU.
const IU_TO_MG: Record<string, number> = {
  'vitamin-a': 0.3 / 1000,
  'vitamin-d': 0.025 / 1000,
  'vitamin-e': 0.67,
};

function toMg(value: number, unit: string | undefined, slug?: string): { v: number; u: 'mg' | 'iu' } {
  // Robust unit parse: labels/regimen snapshots carry SUFFIXED units ("mcg RAE", "mg NE",
  // "mcg DFE") and micro-sign variants. Match by token/prefix, not exact string, so a
  // "mcg RAE" can never fall through to the mg default and inflate 1000x (the Vitamin A bug).
  const u = (unit ?? 'mg').toLowerCase().trim();
  if (u.includes('iu')) {
    // A/D/E: convert IU into the mg-family so an IU-listed product still counts toward its
    // metric target (Phase G-1 residual). Other IU nutrients stay IU-family (no metric target).
    const f = slug !== undefined ? IU_TO_MG[slug] : undefined;
    return (f !== undefined) ? { v: value * f, u: 'mg' } : { v: value, u: 'iu' };
  }
  if (u.startsWith('mcg') || u.startsWith('ug') || u.includes('μg') || u.includes('µg')) {
    return { v: value / 1000, u: 'mg' };
  }
  if (u === 'g' || u.startsWith('gram')) {
    return { v: value * 1000, u: 'mg' };
  }
  return { v: value, u: 'mg' };  // 'mg' + 'mg RAE'/'mg NE' + unknown -> mg-family
}

/**
 * Convert accumulated delivery (kept internally in mg or IU) back into the
 * target's own display unit, so the deep-dive meter can show "intake / target"
 * in the same unit Wallach stated (mcg, mg, g, IU) rather than a raw mg figure.
 */
function deliveredInUnit(d: Delivery, unit: string | undefined): number {
  const u = (unit ?? 'mg').toLowerCase();
  if (u === 'iu') {
    return d.totalIU;
  }
  if (u === 'g') {
    return d.totalMg / 1000;
  }
  if (u === 'mcg' || u === 'μg' || u === 'µg') {
    return d.totalMg * 1000;
  }
  return d.totalMg;
}

// ─── Nutrient → essential resolution (the ONE registry resolver) ───────────

/** Index the targets by canon slug — the direct join key resolveSlug returns. */
function buildBySlug(targets: Essential[]): Map<string, Essential> {
  const m = new Map<string, Essential>();
  for (const t of targets) {
    m.set(t.slug, t);
  }
  return m;
}

// ─── Regimen delivery accumulation ─────────────────────────────────────────

interface Delivery {
  totalMg: number;
  totalIU: number;
  /** Display names of regimen items contributing (for hasSrc + PDM detection). */
  sources: string[];
}

const EMPTY_DELIVERY: Delivery = { totalMg: 0, totalIU: 0, sources: [] };

/** Resolve an item's serving/dose scaling factor (override → item → label.servings → 1). */
function readScale(item: RegimenItem, overrides: OverridesMap): number {
  const ov = overrides[String(item.id)];
  const candidates: unknown[] = [
    ov?.['scaling_factor'],
    (item as Record<string, unknown>)['scaling_factor'],
    (item.label as Record<string, unknown>)['servings'],
  ];
  for (const c of candidates) {
    const n = typeof c === 'number' ? c : typeof c === 'string' ? Number.parseFloat(c) : Number.NaN;
    if (Number.isFinite(n) && n > 0) {
      return n;
    }
  }
  return 1;
}

/**
 * Sum every regimen item's label nutrients into per-essential mg/IU totals.
 * Each label nutrient resolves to a canon slug via the registry resolver, then
 * to its target by slug — so the Coverage math credits the SAME essential the
 * Products pillar does (one resolution truth).
 */
function accumulate(
  items: RegimenItem[],
  overrides: OverridesMap,
  targets: Essential[],
  bySlug: Map<string, Essential>,
): Map<string, Delivery> {
  const out = new Map<string, Delivery>();
  for (const t of targets) {
    out.set(t.name, { totalMg: 0, totalIU: 0, sources: [] });
  }
  for (const item of items) {
    const scale = readScale(item, overrides);
    const displayName = typeof item.label.name === 'string' && item.label.name !== ''
      ? item.label.name
      : 'Unknown';
    const rawNutrients = Array.isArray(item.label.nutrients) ? item.label.nutrients : [];
    for (const raw of rawNutrients) {
      const parsed = RegimenNutrientSchema.safeParse(raw);
      if (!parsed.success) {
        continue;
      }
      const n = parsed.data;
      if (!(n.amount > 0)) {
        continue;
      }
      const slug = resolveSlug(n.name, n.form ?? null);
      if (slug === null) {
        continue;
      }
      const matched = bySlug.get(slug);
      if (matched === undefined) {
        continue;
      }
      const d = out.get(matched.name);
      if (d === undefined) {
        continue;
      }
      const conv = toMg(n.amount * scale, n.unit, matched.slug);
      if (conv.u === 'iu') {
        d.totalIU += conv.v;
      }
      else {
        d.totalMg += conv.v;
      }
      if (!d.sources.includes(displayName)) {
        d.sources.push(displayName);
      }
    }
  }
  return out;
}

// ─── Classification (legacy classifyLive port) ─────────────────────────────

const PDM_TRACE = /\bbtt\b|tangerine|plant.derived|humic|colloidal|utt/;
const PDM_COLLECTIVE = /\bbtt\b|tangerine|utt|amino/;

function numericStatus(target: CoverageTarget, d: Delivery): CoverageStatus {
  const isIU = (target.unit ?? '').toLowerCase() === 'iu';
  const current = isIU ? d.totalIU : d.totalMg;
  const lowRaw = target.low ?? 0;
  const low = isIU ? lowRaw : toMg(lowRaw, target.unit).v;
  if (low <= 0) {
    // Deliberate §00.A deviation from legacy (which returned 'ok'): no defined
    // floor + nothing delivered ⇒ pending, never a free "covered".
    return current > 0 ? 'covered' : '';
  }
  if (current >= low * 0.95) {
    return 'covered';
  }
  if (current >= low * 0.30) {
    return 'partial';
  }
  return 'gap';
}

function classify(target: CoverageTarget | null, d: Delivery): CoverageStatus {
  const hasSrc = d.sources.length > 0;
  const kind = target?.kind;
  if (target === null || kind === undefined || kind === 'unspecified') {
    return hasSrc ? 'covered' : '';
  }
  if (kind === 'dietary') {
    return hasSrc ? 'covered' : '';
  }
  if (kind === 'trace_pdm' || kind === 'wallach_collective') {
    const stack = d.sources.join(' | ').toLowerCase();
    const re = kind === 'trace_pdm' ? PDM_TRACE : PDM_COLLECTIVE;
    return re.test(stack) ? 'trace' : '';
  }
  if (kind === 'dietary_with_clinical_lever') {
    if (target.low !== undefined && target.low > 0) {
      return numericStatus(target, d);
    }
    return hasSrc ? 'covered' : '';
  }
  // Numeric: hbsp · wallach · wallach_clinical · any kind carrying low/unit.
  return numericStatus(target, d);
}

function deliveryRatio(target: CoverageTarget | null, status: CoverageStatus, d: Delivery): number {
  if (target === null) {
    return status === 'covered' || status === 'trace' ? 1 : 0;
  }
  const isIU = (target.unit ?? '').toLowerCase() === 'iu';
  const current = isIU ? d.totalIU : d.totalMg;
  const lowRaw = target.low ?? 0;
  const low = isIU ? lowRaw : toMg(lowRaw, target.unit).v;
  if (low > 0) {
    return current / low;
  }
  return status === 'covered' || status === 'trace' ? 1 : 0;
}

// ─── Cache + recompute ─────────────────────────────────────────────────────

let cachedSnapshot: CoverageSnapshot | null = null;

/** Recompute coverage from the targets DB + the active regimen. */
export function recompute(): CoverageSnapshot {
  const targets = readTargets();
  const bySlug = buildBySlug(targets);
  const overrides = loadRgOverrides();
  const delivery = accumulate(loadEffectiveRegimen(), overrides, targets, bySlug);

  const tiles: CoverageTile[] = targets.map((entry) => {
    const target = CoverageTargetSchema.safeParse(entry.target);
    const t = target.success ? target.data : null;
    const d = delivery.get(entry.name) ?? EMPTY_DELIVERY;
    const status = classify(t, d);
    let intakeVsTarget: CoverageTile['intakeVsTarget'] = null;
    if (t !== null && typeof t.low === 'number' && t.low > 0) {
      intakeVsTarget = {
        deliveredAmount: deliveredInUnit(d, t.unit),
        targetLow: t.low,
        targetHigh: typeof t.high === 'number' ? t.high : t.low,
        unit: t.unit ?? 'mg',
      };
    }
    return {
      tileId: buildTileId(entry.name),
      category: catFromTarget(entry.category),
      symbol: '',
      name: entry.name,
      status,
      covered: status === 'covered' || status === 'trace',
      fillPercent: deliveryRatio(t, status, d),
      coveredBy: d.sources,
      aggregateVehicle: status === 'trace',
      intakeVsTarget,
    };
  });

  // Tally by category.
  const byCategory: CoverageSnapshot['byCategory'] = {};
  for (const tile of tiles) {
    const bucket = byCategory[tile.category] ?? { total: 0, covered: 0 };
    bucket.total += 1;
    if (tile.covered) {
      bucket.covered += 1;
    }
    byCategory[tile.category] = bucket;
  }

  const countedTiles = tiles.filter(t => !NON_ESSENTIAL_NAMES.has(t.name));
  const coveredCount = countedTiles.filter(t => t.covered).length;
  const totalCount = countedTiles.length;
  cachedSnapshot = {
    tiles,
    coveredCount,
    totalCount,
    computedAt: new Date().toISOString(),
    byCategory,
  };

  emit('coverage:recomputed', { coveredCount, totalCount });
  return cachedSnapshot;
}

/** Last cached snapshot. Returns null if recompute() hasn't run yet. */
export function getSnapshot(): CoverageSnapshot | null {
  return cachedSnapshot;
}

/** Get a snapshot, computing if needed. Useful for first-render. */
export function getOrCompute(): CoverageSnapshot {
  return cachedSnapshot ?? recompute();
}

// ─── Shared accessors for the scanner verdict engine (Chunk 6b) ────────────

let cachedTargets: Essential[] | null = null;
let cachedBySlug: Map<string, Essential> | null = null;

function ensureTargets(): void {
  if (cachedTargets === null) {
    cachedTargets = readTargets();
    cachedBySlug = buildBySlug(cachedTargets);
  }
}

/** The Wallach targets DB (cached). Shared with state/scanner.ts. */
export function getTargets(): Essential[] {
  ensureTargets();
  return cachedTargets ?? [];
}

/**
 * Match a nutrient/label name to its essential via the SAME registry resolver
 * the live classifier uses — so the scanner's gap-fill math lines up with the
 * Coverage surface (one resolver, no drift).
 */
export function matchEssential(name: string): Essential | null {
  ensureTargets();
  if (cachedBySlug === null) {
    return null;
  }
  const slug = resolveSlug(name);
  if (slug === null) {
    return null;
  }
  return cachedBySlug.get(slug) ?? null;
}

/**
 * Per-essential delivery (mg + IU) from the current EFFECTIVE regimen — the
 * same accumulation the snapshot is built from. The scanner subtracts this from
 * each Wallach target to compute how much a scanned product still fills.
 */
export function currentDelivery(): Map<string, { totalMg: number; totalIU: number }> {
  ensureTargets();
  if (cachedTargets === null || cachedBySlug === null) {
    return new Map();
  }
  const full = accumulate(loadEffectiveRegimen(), loadRgOverrides(), cachedTargets, cachedBySlug);
  const out = new Map<string, { totalMg: number; totalIU: number }>();
  for (const [k, v] of full) {
    out.set(k, { totalMg: v.totalMg, totalIU: v.totalIU });
  }
  return out;
}

// ─── Wire to regimen changes ───────────────────────────────────────────────

let wireInstalled = false;

/**
 * Install the recompute trigger: regimen changes → coverage recomputes.
 * Idempotent — main.ts calls this once at boot.
 */
export function installRecomputeTrigger(): void {
  if (wireInstalled) {
    return;
  }
  wireInstalled = true;

  on('regimen:changed', () => recompute());

  // Also listen to native storage events for cross-tab sync of regimen LS keys.
  onChange((key) => {
    if (key.startsWith('rgSlot') || key === 'lcRegimen_v1') {
      recompute();
    }
  });

  /*
   * Round 150 §31 hook for legacy code: when legacy fires its
   * window.triggerRegimenRerender, also trigger our recompute. Backward
   * compatibility with the legacy event-cascade discipline.
   */
  const w = window as Window & { triggerRegimenRerender?: () => void };
  const original = w.triggerRegimenRerender;
  if (typeof original === 'function') {
    w.triggerRegimenRerender = () => {
      try {
        original();
      }
      finally {
        recompute();
      }
    };
  }
}
