/**
 * state/coverage.ts — periodic-table coverage state + live classifier
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Owns the answer to "which of the 90 essentials does the active regimen
 * cover, and how heavily." Builds a typed CoverageSnapshot keyed by the
 * canonical essential name — the single source of the live numbers consumed by
 * views/coverage.ts (hero count + per-section counts + per-tile status). The
 * layout (coverage-layout-data.json) joins to this snapshot via each tile's
 * `key` field, which equals the essential `name` here.
 *
 * DATA SOURCE:
 *   The essentials come from `essentials-targets-data.json` — the Wallach
 *   targets DB GENERATED by eden/tools/targets_derive.py from the sealed
 *   pillars (numeric targets are Wallach dose claims, R2). Inlined at build
 *   via esbuild JSON import + validated through Zod at the boundary. Each entry
 *   carries its canon `slug` — the join key to the registry resolver below.
 *
 * LIVE CLASSIFIER:
 *   The math lives here (the page loads no legacy JS). Every NUMBER still comes
 *   from Luneth's data (target.low/unit from the targets DB; nutrient amounts
 *   from regimen item labels). Nothing is invented; §00.A holds.
 *
 *   IDENTITY (A2, 2026-07-08): which essential a label nutrient credits is
 *   resolved by the ONE registry resolver — core/nutrient-resolver.ts::resolveSlug,
 *   a faithful port of eden/tools/nutrient_resolve.py, proven equal by the
 *   nutrient_resolver_parity invariant + a vitest. It returns a canon slug; each
 *   target carries its slug, so the join is a direct slug key (no display-name
 *   string-matching). This replaced a hand-rolled matcher that disagreed with the
 *   registry (e.g. it silently dropped "Thiamin" → Vitamin B1).
 *
 *   UNITS (Phase G-1): mcg/mg unify into one mg-family. The A/D/E targets are now
 *   METRIC (mcg RAE / mcg / mg) to match Youngevity's product units (the goal↔product
 *   alignment Luneth asked for). RESIDUAL: no target is IU-family anymore, so a product
 *   that still lists A/D/E in IU lands in the (now unused) totalIU accumulator and does
 *   NOT count toward its metric target (~7 products) — closeable by converting per-vitamin
 *   IU→mcg in toMg (needs the nutrient identity). Full canonical-unit unification stays a
 *   later chunk.
 *
 *   Pipeline: collect the active regimen (the migrated §31 state — committed +
 *   manual items, minus removed, with override scaling) → resolve each label
 *   nutrient to a canon slug + sum into the target's per-essential mg/IU totals
 *   (unit-convert + scale) → classify each essential against its Wallach target.
 *   The 33 trace_pdm rare-earths have no per-mineral dose; they share ONE graduated
 *   verdict from the plant-derived-mineral aggregate (Σ vehicle mg / the ~924 mg
 *   goal — pdm-coverage-data.json), computed once per recompute (pdmAggregate).
 *
 *   Faithful to legacy thresholds (numeric: ok ≥ 0.95·low, warn ≥ 0.30·low,
 *   else gap) with ONE deliberate deviation: a numeric target with low ≤ 0 and
 *   zero delivery reports '' (pending) rather than legacy's 'ok' — legacy would
 *   mark it covered with nothing delivered, an §00.A overclaim.
 *
 *   Status buckets map legacy → view: ok→covered (numeric),
 *   warn→partial, gap→gap, diet→covered, mute→'' (pending, rendered grey).
 *   Empty regimen ⇒ numeric targets are `gap`, the rest pending — the truthful
 *   bare state. recompute() re-runs on every `regimen:changed`.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import coverageLayoutData from '../../../data/coverage-layout-data.json';
import essentialsTargetsData from '../../../data/essentials-targets-data.json';
import pdmCoverageData from '../../../data/pdm-coverage-data.json';
import efaCoverageData from '../../../data/efa-coverage-data.json';
import regimenLabelLookup from '../../../data/regimen-label-lookup.json';
import { emit, on } from '../core/events.js';
import { resolveSlug } from '../core/nutrient-resolver.js';
import {
  CoverageLayoutSchema,
  type CoverageTarget,
  CoverageTargetSchema,
  type Essential,
  EssentialsDataSchema,
  type LayoutTile,
  PdmCoverageSchema,
  type EfaCoverage,
  EfaCoverageSchema,
  RegimenNutrientSchema,
} from '../core/schemas/index.js';
import { onChange } from '../core/storage.js';
import {
  loadEffectiveRegimen,
  loadRgOverrides,
  type OverridesMap,
  type RegimenItem,
} from './regimen.js';

export type TileId = string;

export type TileCategory =
  | 'foundational'
  | 'major-trace'
  | 'rare-trace'
  | 'vitamins'
  | 'aminos'
  | 'fatty-acids'
  | 'other';

/**
 * Live status bucket for one essential. '' = pending / no target (rendered grey).
 * 'present' = a trace/rare vehicle is in the stack but its mg is not derivable
 * (present-but-unquantified — the hollow dot). 'trace' is retained for back-compat
 * (readers treat it as covered) but is no longer produced.
 */
export type CoverageStatus = 'covered' | 'partial' | 'trace' | 'gap' | 'present' | '';

export interface CoverageTile {
  tileId: TileId;
  category: TileCategory;
  symbol: string;
  name: string;
  /** Authoritative live bucket — views render this directly (no re-derivation). */
  status: CoverageStatus;
  /** Convenience flag: status is `covered` or `trace` (covered-by-presence). */
  covered: boolean;
  /** Ratio of Wallach target met (0..>1, can exceed 1 with stacking; 1 for trace/dietary). */
  fillPercent: number;
  /** Regimen item display names contributing to this tile. */
  coveredBy: string[];
  /** Whether this tile is closed via the PDM aggregate-vehicle rule. */
  aggregateVehicle: boolean;
  /**
   * Numeric intake-vs-Wallach-target readout for the deep-dive meter, in the
   * target's own display unit. `null` when the target is non-numeric with no
   * aggregate (dietary / unspecified). EXCEPTION: trace_pdm tiles carry the shared
   * plant-derived-mineral aggregate (Σ vehicle mg vs the ~924 mg goal) here
   * whenever any PDM source is in the stack.
   */
  intakeVsTarget: {
    deliveredAmount: number;
    targetLow: number;
    targetHigh: number;
    unit: string;
  } | null;
  /** True for a trace_pdm / wallach_collective rare-earth-group tile (scored as one group). */
  pdmGroup: boolean;
}

/**
 * The ONE shared rare-earth-group readout every trace_pdm tile points at: the sum of the
 * regimen's plant-derived vehicle mg vs the Wallach maintenance goal (924 mg). null before
 * the first recompute. §00.A: goalMg is a Wallach dose expressed in mg via composition.
 */
export interface PdmGroupSummary {
  deliveredMg: number;
  goalMg: number;
  status: CoverageStatus;
  sources: string[];
}

export interface CoverageSnapshot {
  tiles: CoverageTile[];
  /** The shared rare-earth-group meter (all trace_pdm tiles reference this one readout). */
  pdmGroup: PdmGroupSummary | null;
  coveredCount: number;
  totalCount: number;
  computedAt: string;
  /** Counts by category for the workspace section heads. */
  byCategory: { [K in TileCategory]?: { total: number; covered: number } };
}

// ─── Category + id helpers ─────────────────────────────────────────────────

/**
 * Map the targets-DB coarse category to our TileCategory. Mineral subsection
 * granularity (foundational / major-trace / rare-trace) lives in the layout,
 * not the targets DB, so minerals collapse to `other` here — `byCategory` is a
 * tally aid, not a render source (views read the layout for section grouping).
 */
function catFromTarget(raw: string): TileCategory {
  switch (raw) {
    case 'vitamins':
      return 'vitamins';
    case 'amino_acids':
      return 'aminos';
    case 'fatty_acids':
      return 'fatty-acids';
    default:
      return 'other';
  }
}

function buildTileId(name: string): TileId {
  return `tile_${name.toLowerCase().replace(/\W+/g, '_')}`;
}

// ─── Essential membership — single source for the "90" count ───────────────

/**
 * The periodic-table presentation layout. Single source for which essentials
 * exist and which count toward Wallach's 90: a tile flagged `essential: false`
 * (Omega-9 / oleic — body-synthesizable) is shown for completeness but NOT
 * counted. The targets-DB embed carries the per-essential dose; the layout
 * carries essentiality. §00.A: the count traces to Wallach's "90 Essential
 * Nutrients" enumeration (60 minerals + 16 vitamins + 12 amino acids + 2 EFAs).
 */
const LAYOUT = CoverageLayoutSchema.parse(coverageLayoutData);

function layoutTiles(): readonly LayoutTile[] {
  return LAYOUT.sections.flatMap(s =>
    s.subsections !== undefined
      ? s.subsections.flatMap(sub => sub.tiles)
      : (s.tiles ?? []),
  );
}

/** Canonical names the layout marks non-essential — excluded from the count. */
const NON_ESSENTIAL_NAMES: ReadonlySet<string> = new Set(
  layoutTiles().filter(t => t.essential === false).map(t => t.key),
);

/** Count of Wallach essentials (layout tiles where `essential !== false`) — 90. */
export function essentialCount(): number {
  return layoutTiles().filter(t => t.essential !== false).length;
}

/** Layout tile by its `key` (= layout_key / canonical name) — built once. */
let tileByKey: Map<string, LayoutTile> | null = null;
function tileIndex(): Map<string, LayoutTile> {
  if (tileByKey === null) {
    tileByKey = new Map(layoutTiles().map(t => [t.key, t]));
  }
  return tileByKey;
}

/**
 * The compact tile glyph for an essential, by its layout_key: the chemical
 * symbol (minerals), vitamin letter, or amino abbreviation from the periodic
 * layout; ω3/ω6/ω9 for the fatty acids (no short code in the layout); '' if none.
 */
export function essentialGlyph(layoutKey: string): string {
  const t = tileIndex().get(layoutKey);
  const g = t?.sym ?? t?.letter ?? t?.abbr;
  if (g !== undefined && g.length > 0) {
    return g;
  }
  const omega = /^Omega-([369])\b/.exec(layoutKey);
  return omega !== null ? `ω${omega[1]}` : '';
}

// ─── Targets DB read (Zod-validated at the boundary) ───────────────────────

/** Zod-validate the build-inlined Wallach targets DB (`{ essentials: [...] }`). */
function readTargets(): Essential[] {
  const result = EssentialsDataSchema.safeParse(essentialsTargetsData);
  return result.success ? result.data.essentials : [];
}

// ─── Unit conversion (delivery vs. Wallach target, in the target's unit) ───

/** Convert an amount to a common unit. Faithful legacy `toMg`: IU stays IU. */
// IU→mg for the three fat-soluble vitamins that labels/Wallach state in IU. MUST mirror
// eden/tools/targets_derive.py IU_CONVERSIONS: the A/D/E TARGET is derived there in mcg/mg,
// so a product listing them in IU has to use the SAME physical factor to land in the same
// mg-family the target lives in (§00.B #3 — one conversion truth across the Python/TS line).
// Values are IU→mg: retinol/beta-carotene 0.3 mcg RAE/IU ÷1000; D 0.025 mcg/IU ÷1000; E 0.67 mg/IU.
const IU_TO_MG: Record<string, number> = {
  'vitamin-a': 0.3 / 1000,
  'vitamin-d': 0.025 / 1000,
  'vitamin-e': 0.67,
};

function toMg(value: number, unit: string | undefined, slug?: string): { v: number; u: 'mg' | 'iu' } {
  // Robust unit parse: labels/regimen snapshots carry SUFFIXED units ("mcg RAE", "mg NE",
  // "mcg DFE") and micro-sign variants. Match by token/prefix, not exact string, so a
  // "mcg RAE" can never fall through to the mg default and inflate 1000x (the Vitamin A bug).
  const u = (unit ?? 'mg').toLowerCase().trim();
  if (u.includes('iu')) {
    // A/D/E: convert IU into the mg-family so an IU-listed product still counts toward its
    // metric target (Phase G-1 residual). Other IU nutrients stay IU-family (no metric target).
    const f = slug !== undefined ? IU_TO_MG[slug] : undefined;
    return (f !== undefined) ? { v: value * f, u: 'mg' } : { v: value, u: 'iu' };
  }
  if (u.startsWith('mcg') || u.startsWith('ug') || u.includes('μg') || u.includes('µg')) {
    return { v: value / 1000, u: 'mg' };
  }
  if (u === 'g' || u.startsWith('gram')) {
    return { v: value * 1000, u: 'mg' };
  }
  return { v: value, u: 'mg' }; // 'mg' + 'mg RAE'/'mg NE' + unknown -> mg-family
}

/**
 * Convert accumulated delivery (kept internally in mg or IU) back into the
 * target's own display unit, so the deep-dive meter can show "intake / target"
 * in the same unit Wallach stated (mcg, mg, g, IU) rather than a raw mg figure.
 */
function deliveredInUnit(d: Delivery, unit: string | undefined): number {
  const u = (unit ?? 'mg').toLowerCase();
  if (u === 'iu') {
    return d.totalIU;
  }
  if (u === 'g') {
    return d.totalMg / 1000;
  }
  if (u === 'mcg' || u === 'μg' || u === 'µg') {
    return d.totalMg * 1000;
  }
  return d.totalMg;
}

// ─── Nutrient → essential resolution (the ONE registry resolver) ───────────

/** Index the targets by canon slug — the direct join key resolveSlug returns. */
function buildBySlug(targets: Essential[]): Map<string, Essential> {
  const m = new Map<string, Essential>();
  for (const t of targets) {
    m.set(t.slug, t);
  }
  return m;
}

// ─── Regimen delivery accumulation ─────────────────────────────────────────

interface Delivery {
  totalMg: number;
  totalIU: number;
  /** Display names of regimen items contributing (for hasSrc + PDM detection). */
  sources: string[];
}

const EMPTY_DELIVERY: Delivery = { totalMg: 0, totalIU: 0, sources: [] };

// ─── Live-composition auto-heal (memory: auto-heal-not-user-debug) ─────────
// A regimen item stores a SNAPSHOT of its product's nutrients at add-time. If the
// sealed Product DB later corrects a value, that snapshot goes stale and the user
// would have to re-add the item to pick up the fix. Instead: for any item that came
// from the catalog (NOT a user-scanned label) whose name still matches a live
// product, we re-read the CURRENT composition from the SAME vault the add-picker
// uses (regimen-label-lookup) at compute time, so the number self-corrects on the
// next render with no re-adding. The match is EXACT on the lowercased canonical
// name -- addItem (views/regimen.ts) stores label.name = the vault's canonical_name
// verbatim, so a user-scanned custom item (or the base foundation, whose legacy
// names differ) never collides and always keeps its own data.
let cachedVaultNutrients: Map<string, unknown[]> | null = null;
function vaultNutrientsByName(): Map<string, unknown[]> {
  if (cachedVaultNutrients === null) {
    const m = new Map<string, unknown[]>();
    const root: unknown = (regimenLabelLookup as { products?: unknown }).products ?? regimenLabelLookup;
    if (root !== null && typeof root === 'object') {
      for (const value of Object.values(root as Record<string, unknown>)) {
        for (const cand of (Array.isArray(value) ? value : [value])) {
          if (cand !== null && typeof cand === 'object') {
            const c = cand as { canonical_name?: unknown; name?: unknown; nutrients?: unknown };
            const nm = typeof c.canonical_name === 'string'
              ? c.canonical_name
              : (typeof c.name === 'string' ? c.name : undefined);
            if (nm !== undefined && Array.isArray(c.nutrients)) {
              m.set(nm.toLowerCase(), c.nutrients);
            }
          }
        }
      }
    }
    cachedVaultNutrients = m;
  }
  return cachedVaultNutrients;
}

/**
 * The composition to credit for an item: the LIVE vault nutrients when the item
 * came from the catalog and still matches a product (auto-heal), else the item's
 * own stored snapshot (user-scanned / custom items and the base foundation keep
 * their data). No write-back -- the heal is a read-time re-resolution.
 */
export function liveNutrients(item: RegimenItem): unknown[] {
  const snapshot = Array.isArray(item.label.nutrients) ? item.label.nutrients : [];
  if (item.provenance === 'user_scanned') {
    return snapshot;
  }
  const name = typeof item.label.name === 'string' ? item.label.name.toLowerCase() : '';
  return vaultNutrientsByName().get(name) ?? snapshot;
}

/** Resolve an item's serving/dose scaling factor (override → item → label.servings → 1). */
function readScale(item: RegimenItem, overrides: OverridesMap): number {
  const ov = overrides[String(item.id)];
  const candidates: unknown[] = [
    ov?.['scaling_factor'],
    (item as Record<string, unknown>)['scaling_factor'],
    (item.label as Record<string, unknown>)['servings'],
  ];
  for (const c of candidates) {
    const n = typeof c === 'number' ? c : typeof c === 'string' ? Number.parseFloat(c) : Number.NaN;
    if (Number.isFinite(n) && n > 0) {
      return n;
    }
  }
  return 1;
}

// ─── Trace/rare-mineral aggregate (PDM coverage) ───────────────────────────
// The 33 trace_pdm rare-earths have no individual Wallach dose; they are covered
// as ONE group by plant-derived-mineral intake — Σ(vehicle mg) / goal. Goal +
// per-product vehicle mg are GENERATED (pdm_coverage_derive.py) from the sealed
// pillar (composition) + the curated judgment + Wallach's sealed dose claim.
const PDM = PdmCoverageSchema.parse(pdmCoverageData);
const PDM_GOAL = PDM.goal.maintenance_mg;

/**
 * Rare-earth-group best sources: plant-derived-mineral products ranked by vehicle mg
 * (highest first — Luneth: "factor recommendations by highest amounts first"). pdm_mg is
 * product COMPOSITION, never a target; present-only vehicles (no derivable mg) are excluded.
 */
export function rankedPdmSources(): { productId: string; name: string; mg: number }[] {
  return Object.entries(PDM.products)
    .filter(([, r]) => r.pdm_mg > 0)
    .map(([productId, r]) => ({ productId, name: r.canonical_name, mg: r.pdm_mg }))
    .sort((a, b) => b.mg - a.mg);
}

/**
 * The goal's derivation numbers (provenance) for the "how is this calculated?" hover —
 * read straight from the sealed pillar+claim projection, never re-typed in a view (R3).
 */
export function pdmGoalProvenance(): {
  doseAmount: number;
  doseUnit: string;
  perBwLb: number;
  refMg: number;
  bodyWeightLb: number;
  goalMg: number;
} {
  const p = (PDM.goal as { provenance?: Record<string, number | string> }).provenance ?? {};
  return {
    doseAmount: Number(p['wallach_dose_amount'] ?? 1),
    doseUnit: String(p['wallach_dose_unit'] ?? 'fl oz'),
    perBwLb: Number(p['wallach_dose_per_body_weight_lb'] ?? 100),
    refMg: Number(p['reference_mg_per_fl_oz'] ?? 0),
    bodyWeightLb: Number(p['body_weight_lb'] ?? 154),
    goalMg: PDM_GOAL,
  };
}

let cachedPdmByName: Map<string, { mg: number; present: boolean }> | null = null;
function pdmByName(): Map<string, { mg: number; present: boolean }> {
  if (cachedPdmByName === null) {
    const m = new Map<string, { mg: number; present: boolean }>();
    for (const rec of Object.values(PDM.products)) {
      const nm = rec.canonical_name.toLowerCase();
      if (nm !== '') {
        m.set(nm, { mg: rec.pdm_mg, present: rec.present });
      }
    }
    cachedPdmByName = m;
  }
  return cachedPdmByName;
}

interface PdmDelivery {
  totalMg: number;
  present: boolean;
  sources: string[];
}

/**
 * Aggregate plant-derived-mineral delivery across the effective regimen: sum each
 * item's vehicle mg (serving-scaled), OR-ing the present-but-unquantified flag.
 * Matched by canonical name (the same join the auto-heal uses). This ONE aggregate
 * scores all 33 trace_pdm tiles (they have no per-mineral delivery of their own).
 */
function pdmAggregate(items: RegimenItem[], overrides: OverridesMap): PdmDelivery {
  const map = pdmByName();
  let totalMg = 0;
  let present = false;
  const sources: string[] = [];
  for (const item of items) {
    const name = typeof item.label.name === 'string' ? item.label.name.toLowerCase() : '';
    const rec = map.get(name);
    if (rec === undefined) {
      continue;
    }
    const display = typeof item.label.name === 'string' && item.label.name !== '' ? item.label.name : 'Unknown';
    if (rec.mg > 0) {
      totalMg += rec.mg * readScale(item, overrides);
      if (!sources.includes(display)) {
        sources.push(display);
      }
    }
    else if (rec.present) {
      present = true;
      if (!sources.includes(display)) {
        sources.push(display);
      }
    }
  }
  return { totalMg, present, sources };
}

// ─── Essential-fatty-acid aggregate (EFA coverage) ─────────────────────────
// omega-3 + omega-6 have no individual Wallach dose: he states ONE amount for the
// essential fatty acids as a CATEGORY ("supplemented at the rate of 9 grams per day
// in capsule form", WAL-CLM-DDDL-000115), and his EFAs are exactly two — "only two
// (linoleic and linolenic) are designated as Essential Fatty Acids". So they share
// ONE meter, Σ(regimen efa_oil_mg) / goal, exactly as the 33 rare-earths share the
// PDM meter. The goal + per-product mg are GENERATED (efa_coverage_derive.py) from
// the sealed pillars; omega-9 is NOT a member (Wallach never names oleic acid an EFA).
// ★ The measure is OIL mass: Wallach writes "essential fatty acids AS FLAXSEED OIL at
// 9 grams per day", so 9 one-gram softgels IS his dose. Summing the named acids would
// demand ~12.7 and make his requirement 40% harder than he wrote it.
const EFA: EfaCoverage = EfaCoverageSchema.parse(efaCoverageData);
const EFA_GOAL = EFA.goal.maintenance_mg;

let cachedEfaByName: Map<string, number> | null = null;
function efaByName(): Map<string, number> {
  if (cachedEfaByName === null) {
    const m = new Map<string, number>();
    for (const rec of Object.values(EFA.products)) {
      const nm = rec.canonical_name.toLowerCase();
      if (nm !== '') {
        m.set(nm, rec.efa_oil_mg);
      }
    }
    cachedEfaByName = m;
  }
  return cachedEfaByName;
}

interface EfaDelivery {
  totalMg: number;
  sources: string[];
}

/**
 * Aggregate essential-fatty-acid delivery across the effective regimen: sum each
 * item's EFA mg (serving-scaled), matched by canonical name — the same join the PDM
 * aggregate and the auto-heal use. This ONE aggregate scores both omega tiles.
 */
function efaAggregate(items: RegimenItem[], overrides: OverridesMap): EfaDelivery {
  const map = efaByName();
  let totalMg = 0;
  const sources: string[] = [];
  for (const item of items) {
    const name = typeof item.label.name === 'string' ? item.label.name.toLowerCase() : '';
    const mg = map.get(name);
    if (mg === undefined || mg <= 0) {
      continue;
    }
    totalMg += mg * readScale(item, overrides);
    const display = typeof item.label.name === 'string' && item.label.name !== '' ? item.label.name : 'Unknown';
    if (!sources.includes(display)) {
      sources.push(display);
    }
  }
  return { totalMg, sources };
}

/** The shared EFA verdict from the aggregate (mirrors the pdm/numericStatus thresholds). */
function efaStatusOf(e: EfaDelivery): CoverageStatus {
  if (EFA_GOAL <= 0) {
    return '';
  }
  if (e.totalMg >= EFA_GOAL * 0.95) {
    return 'covered';
  }
  if (e.totalMg >= EFA_GOAL * 0.30) {
    return 'partial';
  }
  return e.totalMg > 0 ? 'gap' : '';
}

/** The shared trace_pdm verdict from the aggregate (mirrors numericStatus thresholds). */
function pdmStatusOf(p: PdmDelivery): CoverageStatus {
  if (PDM_GOAL <= 0) {
    return '';
  }
  if (p.totalMg >= PDM_GOAL * 0.95) {
    return 'covered';
  }
  if (p.totalMg >= PDM_GOAL * 0.30) {
    return 'partial';
  }
  if (p.totalMg > 0) {
    return 'gap';
  }
  return p.present ? 'present' : '';
}

/**
 * Sum every regimen item's label nutrients into per-essential mg/IU totals.
 * Each label nutrient resolves to a canon slug via the registry resolver, then
 * to its target by slug — so the Coverage math credits the SAME essential the
 * Products pillar does (one resolution truth).
 */
function accumulate(
  items: RegimenItem[],
  overrides: OverridesMap,
  targets: Essential[],
  bySlug: Map<string, Essential>,
): Map<string, Delivery> {
  const out = new Map<string, Delivery>();
  for (const t of targets) {
    out.set(t.name, { totalMg: 0, totalIU: 0, sources: [] });
  }
  for (const item of items) {
    const scale = readScale(item, overrides);
    const displayName = typeof item.label.name === 'string' && item.label.name !== ''
      ? item.label.name
      : 'Unknown';
    const rawNutrients = liveNutrients(item);
    for (const raw of rawNutrients) {
      const parsed = RegimenNutrientSchema.safeParse(raw);
      if (!parsed.success) {
        continue;
      }
      const n = parsed.data;
      if (!(n.amount > 0)) {
        continue;
      }
      const slug = resolveSlug(n.name, n.form ?? null);
      if (slug === null) {
        continue;
      }
      const matched = bySlug.get(slug);
      if (matched === undefined) {
        continue;
      }
      const d = out.get(matched.name);
      if (d === undefined) {
        continue;
      }
      const conv = toMg(n.amount * scale, n.unit, matched.slug);
      if (conv.u === 'iu') {
        d.totalIU += conv.v;
      }
      else {
        d.totalMg += conv.v;
      }
      if (!d.sources.includes(displayName)) {
        d.sources.push(displayName);
      }
    }
  }
  return out;
}

// ─── Classification (legacy classifyLive port) ─────────────────────────────

function numericStatus(target: CoverageTarget, d: Delivery): CoverageStatus {
  const isIU = (target.unit ?? '').toLowerCase() === 'iu';
  const current = isIU ? d.totalIU : d.totalMg;
  const lowRaw = target.low ?? 0;
  const low = isIU ? lowRaw : toMg(lowRaw, target.unit).v;
  if (low <= 0) {
    // Deliberate §00.A deviation from legacy (which returned 'ok'): no defined
    // floor + nothing delivered ⇒ pending, never a free "covered".
    return current > 0 ? 'covered' : '';
  }
  if (current >= low * 0.95) {
    return 'covered';
  }
  if (current >= low * 0.30) {
    return 'partial';
  }
  return 'gap';
}

/**
 * The 4 organic building blocks (hydrogen · carbon · nitrogen · oxygen) are present in
 * air/water/food by default (Luneth), so a '' (no-dose) status reads covered, not absent.
 *
 * PROMOTED to the state layer 2026-07-14. It previously lived ONLY in views/knowledge.ts
 * (as a symbol set applied inside the drawer's dot mapper), which meant the drawer painted
 * H/C/N/O green while Coverage rendered the same four tiles blank — two surfaces disagreeing
 * about 4 essentials over ONE snapshot. A coverage verdict is a state decision, never a view
 * decision; both surfaces now inherit this from the snapshot. Keyed by canon slug (not the
 * display symbol) so it joins the same way every other target does.
 */
const FOUNDATIONAL_PRESENT_SLUGS: ReadonlySet<string> = new Set([
  'hydrogen',
  'carbon',
  'nitrogen',
  'oxygen',
]);

function classify(
  target: CoverageTarget | null,
  d: Delivery,
  pdmStatus: CoverageStatus,
  efaStatus: CoverageStatus,
): CoverageStatus {
  const hasSrc = d.sources.length > 0;
  const kind = target?.kind;
  if (target === null || kind === undefined || kind === 'unspecified') {
    return hasSrc ? 'covered' : '';
  }
  if (kind === 'dietary') {
    return hasSrc ? 'covered' : '';
  }
  if (kind === 'trace_pdm') {
    // The 33 trace_pdm rare-earths share ONE verdict from the plant-derived-mineral
    // aggregate (Σ vehicle mg / goal), computed once per recompute — not per mineral
    // (no product label itemizes a rare earth). silver/tin/cobalt carry their own
    // Wallach dose → kind 'wallach' → the numeric path below, never here.
    return pdmStatus;
  }
  if (kind === 'wallach_collective') {
    // ★ THIS BRANCH WAS 'trace_pdm || wallach_collective' AND IT WAS A BEARTRAP.
    // wallach_collective was a DEAD alias — no target carried it — so it sat here
    // harmlessly routing to the RARE-EARTH mineral meter. The moment targets_derive
    // started emitting it for the omegas (2026-07-15), seeding two plant-derived
    // MINERAL products with ZERO fatty acids rendered OMEGA-3 and OMEGA-6 as
    // "covered" — proven with a DOM probe, not reasoned about. A dead alias is not
    // inert; it is a loaded branch waiting for someone to feed it.
    // Every collective group MUST route to its own meter, keyed by the group the
    // claim names. No group => no verdict, never a neighbouring group's.
    if (target.collective_group === 'essential-fatty-acids') {
      return efaStatus;
    }
    return '';
  }
  if (kind === 'dietary_with_clinical_lever') {
    if (target.low !== undefined && target.low > 0) {
      return numericStatus(target, d);
    }
    return hasSrc ? 'covered' : '';
  }
  // Numeric: hbsp · wallach · wallach_clinical · any kind carrying low/unit.
  return numericStatus(target, d);
}

function deliveryRatio(target: CoverageTarget | null, status: CoverageStatus, d: Delivery): number {
  if (target === null) {
    return status === 'covered' || status === 'trace' ? 1 : 0;
  }
  const isIU = (target.unit ?? '').toLowerCase() === 'iu';
  const current = isIU ? d.totalIU : d.totalMg;
  const lowRaw = target.low ?? 0;
  const low = isIU ? lowRaw : toMg(lowRaw, target.unit).v;
  if (low > 0) {
    return current / low;
  }
  return status === 'covered' || status === 'trace' ? 1 : 0;
}

// ─── Cache + recompute ─────────────────────────────────────────────────────

let cachedSnapshot: CoverageSnapshot | null = null;

/** Recompute coverage from the targets DB + the active regimen. */
export function recompute(): CoverageSnapshot {
  const targets = readTargets();
  const bySlug = buildBySlug(targets);
  const overrides = loadRgOverrides();
  const items = loadEffectiveRegimen();
  const delivery = accumulate(items, overrides, targets, bySlug);
  const pdm = pdmAggregate(items, overrides);
  const pdmStatus = pdmStatusOf(pdm);
  const efa = efaAggregate(items, overrides);
  const efaStatus = efaStatusOf(efa);

  const tiles: CoverageTile[] = targets.map((entry) => {
    const target = CoverageTargetSchema.safeParse(entry.target);
    const t = target.success ? target.data : null;
    const d = delivery.get(entry.name) ?? EMPTY_DELIVERY;
    // The foundational-present rule runs HERE (not inside classify) because it keys off the
    // essential's identity, not its target/delivery — classify() only sees the target + delivery.
    const classified = classify(t, d, pdmStatus, efaStatus);
    const status: CoverageStatus = (classified === '' && FOUNDATIONAL_PRESENT_SLUGS.has(entry.slug))
      ? 'covered'
      : classified;
    // NOT `|| wallach_collective` — that alias fed the omegas into the rare-earth
    // meter (see classify). trace_pdm is the ONLY kind the PDM aggregate scores.
    const isPdm = t?.kind === 'trace_pdm';
    let intakeVsTarget: CoverageTile['intakeVsTarget'] = null;
    if (isPdm) {
      // The rare-earth group reads Σ vehicle mg against the ONE shared goal (the meter
      // the inner page shows) — no per-mineral number exists. Null when nothing
      // plant-derived is in the stack, so the view stays quiet on a bare regimen.
      if (pdm.totalMg > 0) {
        intakeVsTarget = {
          deliveredAmount: Math.round(pdm.totalMg * 10) / 10,
          targetLow: PDM_GOAL,
          targetHigh: PDM_GOAL,
          unit: 'mg',
        };
      }
    }
    else if (t !== null && typeof t.low === 'number' && t.low > 0) {
      intakeVsTarget = {
        deliveredAmount: deliveredInUnit(d, t.unit),
        targetLow: t.low,
        targetHigh: typeof t.high === 'number' ? t.high : t.low,
        unit: t.unit ?? 'mg',
      };
    }
    const base = {
      tileId: buildTileId(entry.name),
      category: catFromTarget(entry.category),
      symbol: '',
      name: entry.name,
      status,
      covered: status === 'covered' || status === 'trace',
      fillPercent: isPdm ? (PDM_GOAL > 0 ? pdm.totalMg / PDM_GOAL : 0) : deliveryRatio(t, status, d),
      coveredBy: isPdm ? pdm.sources : d.sources,
      aggregateVehicle: isPdm && status === 'covered',
      intakeVsTarget,
    };
    return { ...base, pdmGroup: isPdm };
  });

  // Tally by category.
  const byCategory: CoverageSnapshot['byCategory'] = {};
  for (const tile of tiles) {
    const bucket = byCategory[tile.category] ?? { total: 0, covered: 0 };
    bucket.total += 1;
    if (tile.covered) {
      bucket.covered += 1;
    }
    byCategory[tile.category] = bucket;
  }

  const countedTiles = tiles.filter(t => !NON_ESSENTIAL_NAMES.has(t.name));
  const coveredCount = countedTiles.filter(t => t.covered).length;
  const totalCount = countedTiles.length;
  cachedSnapshot = {
    tiles,
    pdmGroup: {
      deliveredMg: Math.round(pdm.totalMg * 10) / 10,
      goalMg: PDM_GOAL,
      status: pdmStatus,
      sources: pdm.sources,
    },
    coveredCount,
    totalCount,
    computedAt: new Date().toISOString(),
    byCategory,
  };

  emit('coverage:recomputed', { coveredCount, totalCount });
  return cachedSnapshot;
}

/** Last cached snapshot. Returns null if recompute() hasn't run yet. */
export function getSnapshot(): CoverageSnapshot | null {
  return cachedSnapshot;
}

/** Get a snapshot, computing if needed. Useful for first-render. */
export function getOrCompute(): CoverageSnapshot {
  return cachedSnapshot ?? recompute();
}

// ─── Shared accessors for the scanner verdict engine (Chunk 6b) ────────────

let cachedTargets: Essential[] | null = null;
let cachedBySlug: Map<string, Essential> | null = null;

function ensureTargets(): void {
  if (cachedTargets === null) {
    cachedTargets = readTargets();
    cachedBySlug = buildBySlug(cachedTargets);
  }
}

/** The Wallach targets DB (cached). Shared with state/scanner.ts. */
export function getTargets(): Essential[] {
  ensureTargets();
  return cachedTargets ?? [];
}

/**
 * Match a nutrient/label name to its essential via the SAME registry resolver
 * the live classifier uses — so the scanner's gap-fill math lines up with the
 * Coverage surface (one resolver, no drift).
 */
export function matchEssential(name: string): Essential | null {
  ensureTargets();
  if (cachedBySlug === null) {
    return null;
  }
  const slug = resolveSlug(name);
  if (slug === null) {
    return null;
  }
  return cachedBySlug.get(slug) ?? null;
}

/**
 * Per-essential delivery (mg + IU) from the current EFFECTIVE regimen — the
 * same accumulation the snapshot is built from. The scanner subtracts this from
 * each Wallach target to compute how much a scanned product still fills.
 */
export function currentDelivery(): Map<string, { totalMg: number; totalIU: number }> {
  ensureTargets();
  if (cachedTargets === null || cachedBySlug === null) {
    return new Map();
  }
  const full = accumulate(loadEffectiveRegimen(), loadRgOverrides(), cachedTargets, cachedBySlug);
  const out = new Map<string, { totalMg: number; totalIU: number }>();
  for (const [k, v] of full) {
    out.set(k, { totalMg: v.totalMg, totalIU: v.totalIU });
  }
  return out;
}

// ─── Wire to regimen changes ───────────────────────────────────────────────

let wireInstalled = false;

/**
 * Install the recompute trigger: regimen changes → coverage recomputes.
 * Idempotent — main.ts calls this once at boot.
 */
export function installRecomputeTrigger(): void {
  if (wireInstalled) {
    return;
  }
  wireInstalled = true;

  on('regimen:changed', () => recompute());

  // Also listen to native storage events for cross-tab sync of regimen LS keys.
  onChange((key) => {
    if (key.startsWith('rgSlot') || key === 'lcRegimen_v1') {
      recompute();
    }
  });

  /*
   * Round 150 §31 hook for legacy code: when legacy fires its
   * window.triggerRegimenRerender, also trigger our recompute. Backward
   * compatibility with the legacy event-cascade discipline.
   */
  const w = window as Window & { triggerRegimenRerender?: () => void };
  const original = w.triggerRegimenRerender;
  if (typeof original === 'function') {
    w.triggerRegimenRerender = () => {
      try {
        original();
      }
      finally {
        recompute();
      }
    };
  }
}
