/**
 * state/entity-page.ts — read boundary for the per-entity page view-model (Phase H2)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces dashboard/assets/data/entity-page-data.json (GENERATED by
 * eden/tools/entity_page_derive.py) to the entity-page view: one lean record per
 * essential + condition, holding claim IDs + the H1 directed relations. Inlined at
 * build via esbuild JSON import and validated ONCE through the Zod boundary; a
 * bad/absent artifact degrades to empty so a lookup returns null, never throws.
 *
 * The records store IDs only — the view resolves claim text/verbatim/citation from
 * state/corpus (record ids) + state/search (search ids). Pure reads; no §00.A number
 * originates here (every amount still traces to a Wallach claim via the resolvers).
 * ═══════════════════════════════════════════════════════════════════════════
 */

import entityPageData from '../../../data/entity-page-data.json';
import {
  type ConditionPage,
  EntityPageDataSchema,
  type EssentialPage,
} from '../core/schemas/index.js';

interface EntityPageStore {
  essentials: Record<string, EssentialPage>;
  conditions: Record<string, ConditionPage>;
}

const EMPTY: EntityPageStore = { essentials: {}, conditions: {} };

let cached: EntityPageStore | null = null;

/** Parse + cache once (bad/absent artifact → empty; lookups return null). */
function data(): EntityPageStore {
  if (cached === null) {
    const parsed = EntityPageDataSchema.safeParse(entityPageData);
    cached = parsed.success
      ? { essentials: parsed.data.essentials, conditions: parsed.data.conditions }
      : EMPTY;
  }
  return cached;
}

/** One essential's page view-model by canon slug, or null when absent. */
export function getEssentialPage(slug: string): EssentialPage | null {
  return data().essentials[slug] ?? null;
}

/** One condition's page view-model by catalog slug, or null when absent. */
export function getConditionPage(slug: string): ConditionPage | null {
  return data().conditions[slug] ?? null;
}
