/**
 * state/entity-page.ts — read boundary for the per-entity page view-model (Phase H2)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces dashboard/assets/data/entity-page-data.json (GENERATED by
 * eden/tools/entity_page_derive.py) to the entity-page view: one lean record per
 * essential + condition, holding claim IDs + the H1 directed relations. Inlined at
 * build via esbuild JSON import and validated ONCE through the Zod boundary; a
 * bad/absent artifact degrades to empty so a lookup returns null, never throws.
 *
 * The records store IDs only — the view resolves claim text/verbatim/citation from
 * state/corpus (record ids) + state/search (search ids). Pure reads; no §00.A number
 * originates here (every amount still traces to a Wallach claim via the resolvers).
 * ═══════════════════════════════════════════════════════════════════════════
 */

import entityPageData from '../../../data/entity-page-data.json';
import {
  type ConditionPage,
  EntityPageDataSchema,
  type EssentialPage,
} from '../core/schemas/index.js';

interface EntityPageStore {
  essentials: Record<string, EssentialPage>;
  conditions: Record<string, ConditionPage>;
}

const EMPTY: EntityPageStore = { essentials: {}, conditions: {} };

let cached: EntityPageStore | null = null;

/** Parse + cache once (bad/absent artifact → empty; lookups return null). */
function data(): EntityPageStore {
  if (cached === null) {
    const parsed = EntityPageDataSchema.safeParse(entityPageData);
    cached = parsed.success
      ? { essentials: parsed.data.essentials, conditions: parsed.data.conditions }
      : EMPTY;
  }
  return cached;
}

/** One essential's page view-model by canon slug, or null when absent. */
export function getEssentialPage(slug: string): EssentialPage | null {
  return data().essentials[slug] ?? null;
}

/** One condition's page view-model by catalog slug, or null when absent. */
export function getConditionPage(slug: string): ConditionPage | null {
  return data().conditions[slug] ?? null;
}

/** Lean summary of one essential for the Home tab's search + shelves. */
export interface EssentialSummary {
  slug: string;
  name: string;
  scientific_name: string;
  symbol: string;
  category: string;
  claim_count: number;
}

/** Lean summary of one condition for the Home tab's search + shelves. */
export interface ConditionSummary {
  slug: string;
  name: string;
  claim_count: number;
  /** How many nutrients Wallach ties to the condition — the restore (maps E,C) list length. */
  nutrient_count: number;
}

/** Every essential as a lean list summary (slug-keyed order). Home search/shelves read this. */
export function listEssentialPages(): EssentialSummary[] {
  return Object.entries(data().essentials).map(([slug, e]) => ({
    slug,
    name: e.name,
    scientific_name: e.scientific_name,
    symbol: e.symbol ?? '',
    category: e.category ?? '',
    claim_count: e.claim_count,
  }));
}

/** Every condition as a lean list summary — the mirror of listEssentialPages. */
export function listConditionPages(): ConditionSummary[] {
  return Object.entries(data().conditions).map(([slug, c]) => ({
    slug,
    name: c.name,
    claim_count: c.claim_count,
    nutrient_count: c.restore.length,
  }));
}
