/**
 * state/search.ts — read boundary + retrieval for the Search subsystem
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces the ONE derived Search index (dashboard/assets/data/search/search-index.json,
 * GENERATED by eden/tools/search_index_derive.py) to views/search.ts: the entity registry
 * (with claim counts), the book meta (for composed cites), and every faceted claim. Inlined
 * at build via esbuild JSON import and validated ONCE through the Zod boundary; a bad/absent
 * artifact degrades to empty so the surface never throws.
 *
 * Pure reads + deterministic retrieval only — no mutation, no localStorage. This is the
 * offline "Ask-Wallach" resolver: it maps a plain-language query to a LANDING (browse all
 * entities), an ENTITY page (subject/synonym hit), or an ASK answer (best-matching claim),
 * field-weighted, no LLM (blueprint §6 — protects the never-breaks/fully-portable guarantee).
 *
 * §00.A: every answer/verbatim here is a faithful projection of a sealed Wallach claim.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import searchIndexJson from '../../../data/search/search-index.json';
import {
  FACET_ORDER_BY_TYPE,
  SEARCH_FACETS,
  type SearchClaim,
  type SearchEntity,
  type SearchFacet,
  type SearchIndex,
  SearchIndexSchema,
} from '../core/schemas/index.js';
import { facetLabel } from './copy.js';

const EMPTY_INDEX: SearchIndex = { books: {}, entities: {}, claims: [] };

let indexCache: SearchIndex | null = null;

function index(): SearchIndex {
  if (indexCache === null) {
    const parsed = SearchIndexSchema.safeParse(searchIndexJson);
    indexCache = parsed.success ? parsed.data : EMPTY_INDEX;
  }
  return indexCache;
}

// ─── Entity + claim reads ──────────────────────────────────────────────────

/** An entity registry entry by slug, or null. */
export function getEntity(slug: string): SearchEntity | null {
  return index().entities[slug] ?? null;
}

/** Human display name for a slug — registry display_name, else a humanized fallback. */
export function displayName(slug: string): string {
  const e = getEntity(slug);
  if (e !== null) {
    return e.display_name;
  }
  return slug.replace(/[_-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

/** Every claim whose subject is this entity, in stable id order. */
export function claimsForSubject(subject: string): SearchClaim[] {
  return index().claims
    .filter(c => c.subject === subject)
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** One entity page's claims, grouped into the facet sections it actually has (canonical order). */
export interface FacetGroup {
  facet: string;
  label: string;
  claims: SearchClaim[];
}
export function facetGroups(subject: string): FacetGroup[] {
  const claims = claimsForSubject(subject);
  const e = getEntity(subject);
  // Conditions (and any future type in FACET_ORDER_BY_TYPE) get a tailored section order;
  // everything else uses the default SEARCH_FACETS order.
  const order: readonly SearchFacet[] = (e !== null && FACET_ORDER_BY_TYPE[e.type] !== undefined)
    ? FACET_ORDER_BY_TYPE[e.type] as readonly SearchFacet[]
    : SEARCH_FACETS;
  const out: FacetGroup[] = [];
  for (const facet of order) {
    const inFacet = claims.filter(c => c.facet === facet);
    if (inFacet.length > 0) {
      out.push({ facet, label: facetLabel(facet), claims: inFacet });
    }
  }
  return out;
}

/** The browse landing: every registered entity (slug + display + type + count), slug-sorted. */
export interface EntitySummary {
  slug: string;
  display_name: string;
  type: string;
  symbol: string | null;
  claim_count: number;
}
export function entityList(): EntitySummary[] {
  const ents = index().entities;
  return Object.keys(ents).sort().map((slug) => {
    const e = ents[slug] as SearchEntity;
    return { slug, display_name: e.display_name, type: e.type, symbol: e.symbol ?? null, claim_count: e.claim_count };
  });
}

/** Compose a display citation from the index's book meta + the claim's page (never hand-typed, R3). */
export function composeCite(claim: SearchClaim): string {
  const b = claim.book_id !== null ? index().books[claim.book_id] : undefined;
  if (b === undefined) {
    return '';
  }
  const head = `${b.title.toUpperCase()} (${b.year})`;
  return claim.page !== null ? `${head} · P.${claim.page}` : head;
}

// ─── By-id claim lookup (the entity-page artifact stores search claim IDs) ──

let claimByIdCache: Map<string, SearchClaim> | null = null;

/**
 * One search claim by its id — the entity-page view-model (state/entity-page) stores
 * search[].claim_ids and resolves them here. Built once as a Map over the index claims;
 * null when the id is absent (or corpus-only — a record id that never entered the search
 * index). Callers must route record/protocol ids to state/corpus.getClaim, not here.
 */
export function getSearchClaim(id: string): SearchClaim | null {
  if (claimByIdCache === null) {
    claimByIdCache = new Map(index().claims.map(c => [c.id, c] as const));
  }
  return claimByIdCache.get(id) ?? null;
}

// ─── Retrieval (deterministic, offline) ────────────────────────────────────

/** How a query resolved: the browse landing, an entity page, or a single best Ask answer. */
export interface SearchResult {
  mode: 'landing' | 'entity' | 'ask';
  subject: string;
  /** Present when mode === 'ask' — the single best-matching claim. */
  claim: SearchClaim | null;
  /** True when a non-empty query matched no entity + no claim (landing shows a gentle note). */
  noMatch: boolean;
}

function normalize(s: string): string {
  return s.trim().toLowerCase();
}

/** Entity slug whose slug / synonym / display_name matches the query exactly-ish, else null. */
function entityHit(q: string): string | null {
  for (const [slug, e] of Object.entries(index().entities)) {
    if (slug === q || e.display_name.toLowerCase() === q) {
      return slug;
    }
    if (e.synonyms.some(s => s.toLowerCase() === q)) {
      return slug;
    }
  }
  return null;
}

/** Field-weighted score of a claim against a normalized query (subject/synonym > question/topic > answer > verbatim). */
function scoreClaim(c: SearchClaim, q: string): number {
  let score = 0;
  if (c.subject.includes(q) || q.includes(c.subject)) {
    score += 5;
  }
  if (c.question.toLowerCase().includes(q)) {
    score += 6;
  }
  if (c.topics.some(t => t.includes(q) || q.includes(t))) {
    score += 4;
  }
  if (c.answer_short.toLowerCase().includes(q)) {
    score += 3;
  }
  if (c.answer.toLowerCase().includes(q)) {
    score += 1;
  }
  if (c.verbatim.toLowerCase().includes(q)) {
    score += 1;
  }
  return score;
}

/** The single best-matching claim for an Ask query (null if nothing clears the bar). */
export function ask(query: string): SearchClaim | null {
  const q = normalize(query);
  if (q.length < 2) {
    return null;
  }
  let best: SearchClaim | null = null;
  let bestScore = 0;
  for (const c of index().claims) {
    const s = scoreClaim(c, q);
    if (s > bestScore) {
      bestScore = s;
      best = c;
    }
  }
  return best;
}

/**
 * Resolve a plain-language query to a render intent. Empty query → the browse LANDING
 * (every entity). A subject/synonym hit → its entity page. Otherwise the best Ask answer;
 * if none clears the bar, the landing with a gentle no-match note.
 */
export function resolveQuery(query: string): SearchResult {
  const q = normalize(query);
  if (q.length === 0) {
    return { mode: 'landing', subject: '', claim: null, noMatch: false };
  }
  const hit = entityHit(q);
  if (hit !== null) {
    return { mode: 'entity', subject: hit, claim: null, noMatch: false };
  }
  const best = ask(q);
  if (best !== null) {
    return { mode: 'ask', subject: best.subject, claim: best, noMatch: false };
  }
  return { mode: 'landing', subject: '', claim: null, noMatch: true };
}

/** The first registered entity (slug-sorted) — a safe fallback subject. */
export function defaultSubject(): string {
  const keys = Object.keys(index().entities).sort();
  return keys[0] ?? '';
}

/** Total claim count for a subject (for the header readout). */
export function claimCount(subject: string): number {
  const e = getEntity(subject);
  return e !== null ? e.claim_count : claimsForSubject(subject).length;
}

/** Total entities + claims in the index (for the footer readout). */
export function indexTotals(): { entities: number; claims: number } {
  const idx = index();
  return { entities: Object.keys(idx.entities).length, claims: idx.claims.length };
}

// ─── Bridge (window.* — reached by headless probes + the topbar search bar) ──

const bridge = window as Window & {
  wallachSearch?: {
    resolveQuery: typeof resolveQuery;
    facetGroups: typeof facetGroups;
    getEntity: typeof getEntity;
    composeCite: typeof composeCite;
    defaultSubject: typeof defaultSubject;
    entityList: typeof entityList;
    indexTotals: typeof indexTotals;
  };
};
bridge.wallachSearch = { resolveQuery, facetGroups, getEntity, composeCite, defaultSubject, entityList, indexTotals };
