/**
 * state/search.ts — read boundary + retrieval for the Search subsystem
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces the ONE derived Search index (dashboard/assets/data/search/search-index.json,
 * GENERATED by eden/tools/search_index_derive.py) to views/search.ts: the entity registry
 * (with claim counts), the book meta (for composed cites), and every faceted claim. Inlined
 * at build via esbuild JSON import and validated ONCE through the Zod boundary; a bad/absent
 * artifact degrades to empty so the surface never throws.
 *
 * Pure reads + deterministic retrieval only — no mutation, no localStorage. This is the
 * offline "Ask-Wallach" resolver: it maps a plain-language query to a LANDING (browse all
 * entities), an ENTITY page (subject/synonym hit), or an ASK answer (best-matching claim),
 * field-weighted, no LLM (blueprint §6 — protects the never-breaks/fully-portable guarantee).
 *
 * §00.A: every answer/verbatim here is a faithful projection of a sealed Wallach claim.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import searchIndexJson from '../../../data/search/search-index.json';
import {
  FACET_FAMILIES,
  FACET_ORDER_BY_TYPE,
  INTRO_ORDER_BY_TYPE,
  INTRO_ORDER_DEFAULT,
  SEARCH_FACETS,
  type SearchClaim,
  type SearchEntity,
  type SearchFacet,
  type SearchIndex,
  SearchIndexSchema,
} from '../core/schemas/index.js';
import { facetLabel } from './copy.js';

const EMPTY_INDEX: SearchIndex = { books: {}, entities: {}, claims: [] };

let indexCache: SearchIndex | null = null;

function index(): SearchIndex {
  if (indexCache === null) {
    const parsed = SearchIndexSchema.safeParse(searchIndexJson);
    indexCache = parsed.success ? parsed.data : EMPTY_INDEX;
  }
  return indexCache;
}

// ─── Entity + claim reads ──────────────────────────────────────────────────

/** An entity registry entry by slug, or null. */
export function getEntity(slug: string): SearchEntity | null {
  return index().entities[slug] ?? null;
}

/** Human display name for a slug — registry display_name, else a humanized fallback. */
export function displayName(slug: string): string {
  const e = getEntity(slug);
  if (e !== null) {
    return e.common_name ?? e.display_name;
  }
  return slug.replace(/[_-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

/** Every claim whose subject is this entity, in stable id order. */
export function claimsForSubject(subject: string): SearchClaim[] {
  return index().claims
    .filter(c => c.subject === subject)
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** Distinct book titles a subject's claims cite (for the entity-page meta line), sorted. */
export function booksForSubject(subject: string): string[] {
  const titles = new Set<string>();
  for (const c of claimsForSubject(subject)) {
    if (c.book_id !== null) {
      const b = index().books[c.book_id];
      if (b !== undefined) {
        titles.add(b.title);
      }
    }
  }
  return [...titles].sort();
}

/** One entity page's claims, grouped into the facet sections it actually has (canonical order). */
export interface FacetGroup {
  facet: string;
  label: string;
  claims: SearchClaim[];
}
export function facetGroups(subject: string): FacetGroup[] {
  const claims = claimsForSubject(subject);
  const e = getEntity(subject);
  // Conditions (and any future type in FACET_ORDER_BY_TYPE) get a tailored section order;
  // everything else uses the default SEARCH_FACETS order.
  const order: readonly SearchFacet[] = (e !== null && FACET_ORDER_BY_TYPE[e.type] !== undefined)
    ? FACET_ORDER_BY_TYPE[e.type] as readonly SearchFacet[]
    : SEARCH_FACETS;
  const out: FacetGroup[] = [];
  for (const facet of order) {
    const inFacet = claims.filter(c => c.facet === facet);
    if (inFacet.length > 0) {
      out.push({ facet, label: facetLabel(facet), claims: inFacet });
    }
  }
  return out;
}

/**
 * Trim to <= max on a word boundary and add an ellipsis; returns s unchanged when it already fits.
 * Trailing punctuation/dash/whitespace before the cut is dropped so the ellipsis reads clean.
 */
function softClamp(s: string, max: number): string {
  if (s.length <= max) {
    return s;
  }
  const cut = s.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  const body = (lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s.,;:—-]+$/, '');
  return `${body}…`;
}

/**
 * The one-line "at a glance" intro for an entity page (Phase H2 follow-up, 2026-07-13). Every topic
 * gets one: the answer_short of its highest-priority available facet (semantic priority via
 * INTRO_ORDER_*, never array position), so a topic with no 'basics' claim still leads with a sensible
 * overview — a food's stance, a person's biography — instead of a blank hero. Soft-clamped so an
 * unusually long summary (chicken/pork stance run 650+) can't turn the hero into an essay; everything
 * under the ceiling renders byte-faithful. '' when the entity has no claims at all.
 */
const LEDE_MAX = 340;
export function entityLede(subject: string): string {
  const e = getEntity(subject);
  // A hand-picked lede claim wins when the facet-priority default is not the best overview for a
  // topic (e.g. cholesterol's "deficiency → disease states" line, or pork's clean red-meat stance):
  // derive-validated to be this entity's OWN enriched claim, so it stays faithful + traceable (R1/§00.A).
  if (e !== null && e.intro_claim !== undefined) {
    const picked = getSearchClaim(e.intro_claim);
    if (picked !== null && picked.subject === subject) {
      return softClamp(picked.answer_short, LEDE_MAX);
    }
  }
  const order: readonly SearchFacet[] = (e !== null && INTRO_ORDER_BY_TYPE[e.type] !== undefined)
    ? INTRO_ORDER_BY_TYPE[e.type] as readonly SearchFacet[]
    : INTRO_ORDER_DEFAULT;
  let best: SearchClaim | null = null;
  let bestRank = order.length;
  for (const c of claimsForSubject(subject)) {
    const rank = order.indexOf(c.facet);
    if (rank >= 0 && rank < bestRank) {
      bestRank = rank;
      best = c;
    }
  }
  return best !== null ? softClamp(best.answer_short, LEDE_MAX) : '';
}

/** The browse landing: every registered entity (slug + display + type + count), slug-sorted. */
export interface EntitySummary {
  slug: string;
  display_name: string;
  type: string;
  symbol: string | null;
  claim_count: number;
}
export function entityList(): EntitySummary[] {
  const ents = index().entities;
  return Object.keys(ents).sort().map((slug) => {
    const e = ents[slug] as SearchEntity;
    return { slug, display_name: e.display_name, type: e.type, symbol: e.symbol ?? null, claim_count: e.claim_count };
  });
}

/** Compose a display citation from the index's book meta + the claim's page (never hand-typed, R3). */
export function composeCite(claim: SearchClaim): string {
  const b = claim.book_id !== null ? index().books[claim.book_id] : undefined;
  if (b === undefined) {
    return '';
  }
  const head = `${b.title.toUpperCase()} (${b.year})`;
  return claim.page !== null ? `${head} · P.${claim.page}` : head;
}

// ─── By-id claim lookup (the entity-page artifact stores search claim IDs) ──

let claimByIdCache: Map<string, SearchClaim> | null = null;

/**
 * One search claim by its id — the entity-page view-model (state/entity-page) stores
 * search[].claim_ids and resolves them here. Built once as a Map over the index claims;
 * null when the id is absent (or corpus-only — a record id that never entered the search
 * index). Callers must route record/protocol ids to state/corpus.getClaim, not here.
 */
export function getSearchClaim(id: string): SearchClaim | null {
  if (claimByIdCache === null) {
    claimByIdCache = new Map(index().claims.map(c => [c.id, c] as const));
  }
  return claimByIdCache.get(id) ?? null;
}

// ─── Retrieval (deterministic, offline) ────────────────────────────────────

/** How a query resolved: the browse landing, an entity page, or a single best Ask answer. */
export interface SearchResult {
  mode: 'landing' | 'entity' | 'ask';
  subject: string;
  /** Present when mode === 'ask' — the single best-matching claim (== claims[0]). */
  claim: SearchClaim | null;
  /** The ranked answers for an 'ask' query: [0] is the best answer, the rest are "more answers". */
  claims: SearchClaim[];
  /** The normalized query, echoed for the no-match empty state. */
  query: string;
  /** True when a non-empty query matched no entity + no claim (landing shows a gentle note). */
  noMatch: boolean;
}

function normalize(s: string): string {
  return s.trim().toLowerCase();
}

/** Entity slug whose slug / synonym / display_name matches the query exactly-ish, else null. */
function entityHit(q: string): string | null {
  for (const [slug, e] of Object.entries(index().entities)) {
    if (slug === q || e.display_name.toLowerCase() === q) {
      return slug;
    }
    if (e.synonyms.some(s => s.toLowerCase() === q)) {
      return slug;
    }
  }
  return null;
}

/**
 * Common English glue words carrying no retrieval signal — dropped before token scoring so a
 * natural-language question ("why are fried eggs bad") ranks on its content words. Built from a
 * split string (not an array literal) so it stays under the inline-array lint without a fixture.
 */
const STOPWORDS = new Set<string>(
  ('the a an of to is are and or in on for with how what why does do did can it its be as by that '
    + 'this which who was were has have had you your i my me about at from into than then so if not '
    + 'no am we they he she his her their').split(' '),
);

/** Split a query into lowercase content tokens (≥2 chars, non-stopword). */
function tokenize(q: string): string[] {
  return q.toLowerCase().split(/[^a-z0-9]+/).filter(t => t.length > 1 && !STOPWORDS.has(t));
}

/**
 * Per-TOKEN field-weighted score of a claim (question > subject > topics > answer_short > answer /
 * verbatim), summed over the query's content tokens, plus a small whole-query boost so a single
 * exact word still reads as precise. Whole-substring `.includes(q)` (the old scorer) never matched
 * a real multi-word question; tokenizing lets "why are fried eggs bad" rank on fried/eggs/bad.
 * Still 100% offline string matching, no LLM.
 */
function scoreClaim(c: SearchClaim, tokens: string[], q: string): number {
  let score = 0;
  const subj = c.subject.toLowerCase();
  if (subj.includes(q) || q.includes(subj)) {
    score += 3;
  }
  const ql = c.question.toLowerCase();
  const al = c.answer_short.toLowerCase();
  const ab = c.answer.toLowerCase();
  const vb = c.verbatim.toLowerCase();
  const tops = c.topics.map(t => t.toLowerCase());
  for (const t of tokens) {
    if (ql.includes(t)) {
      score += 6;
    }
    if (subj.includes(t)) {
      score += 5;
    }
    if (tops.some(x => x.includes(t))) {
      score += 4;
    }
    if (al.includes(t)) {
      score += 3;
    }
    if (ab.includes(t)) {
      score += 1;
    }
    if (vb.includes(t)) {
      score += 1;
    }
  }
  return score;
}

/** Distinct content tokens the subject's answers hint at, for the "keep exploring" card foot. */
export function subjectFacetHints(subject: string, max = 4): string[] {
  return facetGroups(subject).slice(0, max).map(g => g.facet);
}

/** The ranked answers for an Ask query — [0] is the best answer, the rest are "more answers".
 *  Empty when nothing clears the bar. Deterministic (score desc, then id) — no LLM. */
export function askRanked(query: string, limit = 6): SearchClaim[] {
  const q = normalize(query);
  if (q.length < 2) {
    return [];
  }
  const tokens = tokenize(q);
  if (tokens.length === 0) {
    return [];
  }
  const scored = index().claims.map(c => ({ c, s: scoreClaim(c, tokens, q) }));
  const hits = scored.filter(x => x.s > 0);
  hits.sort((a, b) => (b.s - a.s) || (a.c.id < b.c.id ? -1 : a.c.id > b.c.id ? 1 : 0));
  return hits.slice(0, limit).map(x => x.c);
}

/**
 * Resolve a plain-language query to a render intent. Empty query → the browse LANDING
 * (every entity). A subject/synonym hit → its entity page. Otherwise the best Ask answer;
 * if none clears the bar, the landing with a gentle no-match note.
 */
export function resolveQuery(query: string): SearchResult {
  const q = normalize(query);
  if (q.length === 0) {
    return { mode: 'landing', subject: '', claim: null, claims: [], query: '', noMatch: false };
  }
  const hit = entityHit(q);
  if (hit !== null) {
    return { mode: 'entity', subject: hit, claim: null, claims: [], query: q, noMatch: false };
  }
  const ranked = askRanked(q);
  const best = ranked[0];
  if (best !== undefined) {
    return { mode: 'ask', subject: best.subject, claim: best, claims: ranked, query: q, noMatch: false };
  }
  return { mode: 'landing', subject: '', claim: null, claims: [], query: q, noMatch: true };
}

/** The first registered entity (slug-sorted) — a safe fallback subject. */
export function defaultSubject(): string {
  const keys = Object.keys(index().entities).sort();
  return keys[0] ?? '';
}

/** Total claim count for a subject (for the header readout). */
export function claimCount(subject: string): number {
  const e = getEntity(subject);
  return e !== null ? e.claim_count : claimsForSubject(subject).length;
}

/** Total entities + claims in the index (for the footer readout). */
export function indexTotals(): { entities: number; claims: number } {
  const idx = index();
  return { entities: Object.keys(idx.entities).length, claims: idx.claims.length };
}

/** One facet-family readout for the opening "browse by kind" screen: id (→ CSS data-family +
 *  the view-copy label id), its facets, and the total claim count across them. */
export interface FamilyCount {
  id: string;
  facets: readonly string[];
  count: number;
}
/** Per-family claim counts for the opening screen — facets partitioned by FACET_FAMILIES. */
export function familyCounts(): FamilyCount[] {
  const byFacet = new Map<string, number>();
  for (const c of index().claims) {
    byFacet.set(c.facet, (byFacet.get(c.facet) ?? 0) + 1);
  }
  return FACET_FAMILIES.map(fam => ({
    id: fam.id,
    facets: fam.facets,
    count: fam.facets.reduce((n, f) => n + (byFacet.get(f) ?? 0), 0),
  }));
}

// ─── Bridge (window.* — reached by headless probes + the topbar search bar) ──

const bridge = window as Window & {
  wallachSearch?: {
    resolveQuery: typeof resolveQuery;
    facetGroups: typeof facetGroups;
    getEntity: typeof getEntity;
    composeCite: typeof composeCite;
    defaultSubject: typeof defaultSubject;
    entityList: typeof entityList;
    indexTotals: typeof indexTotals;
    familyCounts: typeof familyCounts;
  };
};
bridge.wallachSearch = { resolveQuery, facetGroups, getEntity, composeCite, defaultSubject, entityList, indexTotals, familyCounts };
