/**
 * state/search.ts — read boundary + retrieval for the Search subsystem
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Surfaces the ONE derived Search index (dashboard/assets/data/search/search-index.json,
 * GENERATED by eden/tools/search_index_derive.py) to views/search.ts: the entity registry
 * (with claim counts), the book meta (for composed cites), and every faceted claim. Inlined
 * at build via esbuild JSON import and validated ONCE through the Zod boundary; a bad/absent
 * artifact degrades to empty so the surface never throws.
 *
 * Pure reads + deterministic retrieval only — no mutation, no localStorage. This is the
 * offline "Ask-Wallach" resolver: it maps a plain-language query to a LANDING (browse all
 * entities), an ENTITY page (subject/synonym hit), or an ASK answer (best-matching claim),
 * field-weighted, no LLM (blueprint §6 — protects the never-breaks/fully-portable guarantee).
 *
 * §00.A: every answer/verbatim here is a faithful projection of a sealed Wallach claim.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import searchIndexJson from '../../../data/search/search-index.json';
import {
  FACET_FAMILIES,
  FACET_ORDER_BY_TYPE,
  INTRO_ORDER_BY_TYPE,
  INTRO_ORDER_DEFAULT,
  SEARCH_FACETS,
  type SearchClaim,
  type SearchEntity,
  type SearchFacet,
  type SearchIndex,
  SearchIndexSchema,
} from '../core/schemas/index.js';
import { facetLabel, kindCategory, kindLabel } from './copy.js';
import { resolveClaims } from './corpus.js';
import {
  getConditionPage,
  getEssentialPage,
  listConditionPages,
  listEssentialPages,
} from './entity-page.js';

const EMPTY_INDEX: SearchIndex = { books: {}, entities: {}, claims: [] };

let indexCache: SearchIndex | null = null;

function index(): SearchIndex {
  if (indexCache === null) {
    const parsed = SearchIndexSchema.safeParse(searchIndexJson);
    indexCache = parsed.success ? parsed.data : EMPTY_INDEX;
  }
  return indexCache;
}

// ─── Entity + claim reads ──────────────────────────────────────────────────

/** An entity registry entry by slug, or null. */
export function getEntity(slug: string): SearchEntity | null {
  return index().entities[slug] ?? null;
}

/** Human display name for a slug — search registry, else a wider condition/essential page name,
 *  else a humanized fallback (so a wide-universe slug still reads as a real title + round-trips). */
export function displayName(slug: string): string {
  const e = getEntity(slug);
  if (e !== null) {
    return e.common_name ?? e.display_name;
  }
  const c = getConditionPage(slug);
  if (c !== null) {
    return c.name;
  }
  const es = getEssentialPage(slug);
  if (es !== null) {
    return es.name;
  }
  return slug.replace(/[_-]+/g, ' ').replace(/\b\w/g, c2 => c2.toUpperCase());
}

/** Every claim whose subject is this entity, in stable id order. */
export function claimsForSubject(subject: string): SearchClaim[] {
  return index().claims
    // A topic includes claims PRIMARILY about it (subject) OR secondarily (also_about) -- the
    // catch-all intent: ORAC food answers surface on the Antioxidants topic, and vice-versa.
    .filter(c => c.subject === subject || c.also_about.includes(subject))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** The four ORAC-family subjects whose claims populate the ORAC knowledge page. */
const ORAC_SUBJECTS: ReadonlySet<string> = new Set(['orac', 'antioxidants', 'free_radicals', 'longevity']);

/**
 * Every claim on the ORAC knowledge page: one of the four ORAC-family subjects AND actually
 * about ORAC (its subject IS orac, or 'orac' is in its also_about). The subject-set keeps out an
 * off-topic claim that merely also_abouts orac (e.g. an eggs-dosing claim); the also_about clause
 * keeps out longevity/antioxidant claims that never touch ORAC. 31 on today's index -- a LIVE
 * count, never the demo's stale hardcoded "30". Stable id order.
 */
export function oracClaims(): SearchClaim[] {
  return index().claims
    .filter(c => ORAC_SUBJECTS.has(c.subject) && (c.subject === 'orac' || c.also_about.includes('orac')))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/** Distinct book titles a subject's claims cite (for the entity-page meta line), sorted. */
export function booksForSubject(subject: string): string[] {
  const titles = new Set<string>();
  for (const c of claimsForSubject(subject)) {
    if (c.book_id !== null) {
      const b = index().books[c.book_id];
      if (b !== undefined) {
        titles.add(b.title);
      }
    }
  }
  return [...titles].sort();
}

/** One entity page's claims, grouped into the facet sections it actually has (canonical order). */
export interface FacetGroup {
  facet: string;
  label: string;
  claims: SearchClaim[];
}
export function facetGroups(subject: string): FacetGroup[] {
  const claims = claimsForSubject(subject);
  const e = getEntity(subject);
  // Conditions (and any future type in FACET_ORDER_BY_TYPE) get a tailored section order;
  // everything else uses the default SEARCH_FACETS order.
  const order: readonly SearchFacet[] = (e !== null && FACET_ORDER_BY_TYPE[e.type] !== undefined)
    ? FACET_ORDER_BY_TYPE[e.type] as readonly SearchFacet[]
    : SEARCH_FACETS;
  const out: FacetGroup[] = [];
  for (const facet of order) {
    const inFacet = claims.filter(c => c.facet === facet);
    if (inFacet.length > 0) {
      out.push({ facet, label: facetLabel(facet), claims: inFacet });
    }
  }
  return out;
}

/**
 * Trim to <= max on a word boundary and add an ellipsis; returns s unchanged when it already fits.
 * Trailing punctuation/dash/whitespace before the cut is dropped so the ellipsis reads clean.
 */
function softClamp(s: string, max: number): string {
  if (s.length <= max) {
    return s;
  }
  const cut = s.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  const body = (lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s.,;:—-]+$/, '');
  return `${body}…`;
}

/**
 * The one-line "at a glance" intro for an entity page (Phase H2 follow-up, 2026-07-13). Every topic
 * gets one: the answer_short of its highest-priority available facet (semantic priority via
 * INTRO_ORDER_*, never array position), so a topic with no 'basics' claim still leads with a sensible
 * overview — a food's stance, a person's biography — instead of a blank hero. Soft-clamped so an
 * unusually long summary (chicken/pork stance run 650+) can't turn the hero into an essay; everything
 * under the ceiling renders byte-faithful. '' when the entity has no claims at all.
 */
const LEDE_MAX = 340;
export function entityLede(subject: string): string {
  const e = getEntity(subject);
  // A hand-picked lede claim wins when the facet-priority default is not the best overview for a
  // topic (e.g. cholesterol's "deficiency → disease states" line, or pork's clean red-meat stance).
  // The pick may be a claim PRIMARILY about another entity but genuinely also_about THIS one (e.g.
  // sexual_health opening with the Kegel claim whose primary home is pelvic-floor-exercises) — safe
  // because this is the DELIBERATE override path; the auto facet-priority path below still requires
  // subject===entity, so a tangential also_about never auto-ledes. Derive-validated either way (Luneth 2026-07-27).
  if (e !== null && e.intro_claim !== undefined) {
    const picked = getSearchClaim(e.intro_claim);
    if (picked !== null && (picked.subject === subject || picked.also_about.includes(subject))) {
      return softClamp(picked.answer_short, LEDE_MAX);
    }
  }
  const order: readonly SearchFacet[] = (e !== null && INTRO_ORDER_BY_TYPE[e.type] !== undefined)
    ? INTRO_ORDER_BY_TYPE[e.type] as readonly SearchFacet[]
    : INTRO_ORDER_DEFAULT;
  let best: SearchClaim | null = null;
  let bestRank = order.length;
  for (const c of claimsForSubject(subject)) {
    // The LEDE must be PRIMARILY about the entity, never a tangential also_about claim
    // (else the eggs topic ledes with a red-meat claim). Card LISTINGS still show also_about.
    if (c.subject !== subject) {
      continue;
    }
    const rank = order.indexOf(c.facet);
    if (rank >= 0 && rank < bestRank) {
      bestRank = rank;
      best = c;
    }
  }
  return best !== null ? softClamp(best.answer_short, LEDE_MAX) : '';
}

/** The browse landing: every registered entity (slug + display + type + count), slug-sorted. */
export interface EntitySummary {
  slug: string;
  display_name: string;
  type: string;
  symbol: string | null;
  claim_count: number;
}
export function entityList(): EntitySummary[] {
  const ents = index().entities;
  return Object.keys(ents).sort().map((slug) => {
    const e = ents[slug] as SearchEntity;
    return { slug, display_name: e.display_name, type: e.type, symbol: e.symbol ?? null, claim_count: e.claim_count };
  });
}

/** Compose a display citation from the index's book meta + the claim's page (never hand-typed, R3). */
export function composeCite(claim: SearchClaim): string {
  const b = claim.book_id !== null ? index().books[claim.book_id] : undefined;
  if (b === undefined) {
    return '';
  }
  const head = `${b.title.toUpperCase()} (${b.year})`;
  return claim.page !== null ? `${head} · P.${claim.page}` : head;
}

/**
 * A COMPACT book cite for space-constrained cards: the short title (before any subtitle ":")
 * + year, no page -- derived from the registry title (single source), e.g. "Hell's Kitchen:
 * Causes..." -> "Hell's Kitchen (2015)". Casing is left to the card CSS (text-transform).
 */
export function composeShortCite(claim: SearchClaim): string {
  const b = claim.book_id !== null ? index().books[claim.book_id] : undefined;
  if (b === undefined) {
    return '';
  }
  const short = b.title.replace(/:.*$/, '').trim();
  return `${short} (${b.year})`;
}

// ─── By-id claim lookup (the entity-page artifact stores search claim IDs) ──

let claimByIdCache: Map<string, SearchClaim> | null = null;

/**
 * One search claim by its id — the entity-page view-model (state/entity-page) stores
 * search[].claim_ids and resolves them here. Built once as a Map over the index claims;
 * null when the id is absent (or corpus-only — a record id that never entered the search
 * index). Callers must route record/protocol ids to state/corpus.getClaim, not here.
 */
export function getSearchClaim(id: string): SearchClaim | null {
  if (claimByIdCache === null) {
    claimByIdCache = new Map(index().claims.map(c => [c.id, c] as const));
  }
  return claimByIdCache.get(id) ?? null;
}

// ─── Retrieval (deterministic, offline) ────────────────────────────────────

/** How a query resolved: the browse landing, an entity page, or a single best Ask answer. */
export interface SearchResult {
  mode: 'landing' | 'entity' | 'ask';
  subject: string;
  /** Present when mode === 'ask' — the single best-matching claim (== claims[0]). */
  claim: SearchClaim | null;
  /** The ranked answers for an 'ask' query: [0] is the best answer, the rest are "more answers". */
  claims: SearchClaim[];
  /** The normalized query, echoed for the no-match empty state. */
  query: string;
  /** True when a non-empty query matched no entity + no claim (landing shows a gentle note). */
  noMatch: boolean;
}

function normalize(s: string): string {
  return s.trim().toLowerCase();
}

/** Entity slug whose slug / synonym / display_name matches the query exactly-ish, else null. */
function entityHit(q: string): string | null {
  for (const [slug, e] of Object.entries(index().entities)) {
    if (slug === q || e.display_name.toLowerCase() === q) {
      return slug;
    }
    if (e.synonyms.some(s => s.toLowerCase() === q)) {
      return slug;
    }
  }
  return null;
}

/**
 * The WIDER exact-match: the full Knowledge universe beyond the ~73 enriched search entities —
 * every condition + essential page (state/entity-page, an already-gated shipped artifact). Matches
 * a query to a page slug by slug, spaced-slug, or display name (case-folded). This is what makes the
 * search a CATCH-ALL: typing "cancer" resolves the real condition page instead of falling through to
 * a tangential ask answer. Synonyms are not matched here yet (the page artifact's synonyms field is
 * still sparse — 2/502 conditions, 14/91 essentials — so name/slug is the reliable key; alias data is
 * a separate follow-up). entityHit (the enriched 73) is tried FIRST, so an enriched entity still wins.
 */
function wideEntityHit(q: string): string | null {
  const spaced = (slug: string): string => slug.replace(/[_-]+/g, ' ');
  for (const c of listConditionPages()) {
    if (c.slug === q || spaced(c.slug) === q || c.name.toLowerCase() === q) {
      return c.slug;
    }
  }
  for (const e of listEssentialPages()) {
    if (e.slug === q || spaced(e.slug) === q || e.name.toLowerCase() === q) {
      return e.slug;
    }
  }
  return null;
}

/**
 * Common English glue words carrying no retrieval signal — dropped before token scoring so a
 * natural-language question ("why are fried eggs bad") ranks on its content words. Built from a
 * split string (not an array literal) so it stays under the inline-array lint without a fixture.
 */
const STOPWORDS = new Set<string>(
  ('the a an of to is are and or in on for with how what why does do did can it its be as by that '
    + 'this which who was were has have had you your i my me about at from into than then so if not '
    + 'no am we they he she his her their').split(' '),
);

/** Split a query into lowercase content tokens (≥2 chars, non-stopword). */
function tokenize(q: string): string[] {
  return q.toLowerCase().split(/[^a-z0-9]+/).filter(t => t.length > 1 && !STOPWORDS.has(t));
}

/**
 * Per-TOKEN field-weighted score of a claim (question > subject > topics > answer_short > answer /
 * verbatim), summed over the query's content tokens, plus a small whole-query boost so a single
 * exact word still reads as precise. Whole-substring `.includes(q)` (the old scorer) never matched
 * a real multi-word question; tokenizing lets "why are fried eggs bad" rank on fried/eggs/bad.
 * Still 100% offline string matching, no LLM.
 */
function scoreClaim(c: SearchClaim, tokens: string[], q: string): number {
  let score = 0;
  const subj = c.subject.toLowerCase();
  if (subj.includes(q) || q.includes(subj)) {
    score += 3;
  }
  const ql = c.question.toLowerCase();
  const al = c.answer_short.toLowerCase();
  const ab = c.answer.toLowerCase();
  const vb = c.verbatim.toLowerCase();
  const tops = c.topics.map(t => t.toLowerCase());
  for (const t of tokens) {
    if (ql.includes(t)) {
      score += 6;
    }
    if (subj.includes(t)) {
      score += 5;
    }
    if (tops.some(x => x.includes(t))) {
      score += 4;
    }
    if (al.includes(t)) {
      score += 3;
    }
    if (ab.includes(t)) {
      score += 1;
    }
    if (vb.includes(t)) {
      score += 1;
    }
  }
  return score;
}

/** Distinct content tokens the subject's answers hint at, for the "keep exploring" card foot. */
export function subjectFacetHints(subject: string, max = 4): string[] {
  return facetGroups(subject).slice(0, max).map(g => g.facet);
}

// ─── Intent detection + charged-topic safety gate ───────────────────────────

/**
 * Charged topics that must NEVER ambush a searcher — surfaced only when the query EXPLICITLY names
 * one (its name/slug or an exact synonym), never via an incidental body word. The Explore tab keeps
 * them (a full index); this gate is search-results only, extensible with Luneth. (memory: charged-search-gate)
 */
const CHARGED: ReadonlySet<string> = new Set(['homosexuality', 'intersex']);
/** Explicit charged terms beyond the entities' own synonyms, so the gate never misses a common word.
 *  Built from a split string (not an array literal) so it stays under the inline-data lint. */
const CHARGED_TERMS: readonly string[] = (
  'homosexual|homosexuality|gay|lesbian|lgbt|lgbtq|queer|same-sex|same sex|sexual orientation|'
  + 'gay gene|intersex|hermaphrodite|hermaphroditism|transgender'
).split('|');

/** True when the query EXPLICITLY names a charged topic (its name/synonym, whole-word). */
function chargedExplicit(q: string): boolean {
  const pad = ` ${q} `;
  for (const slug of CHARGED) {
    const e = getEntity(slug);
    const names = e !== null ? [e.display_name.toLowerCase(), ...e.synonyms.map(s => s.toLowerCase())] : [];
    names.push(slug.replace(/[_-]+/g, ' '));
    for (const t of names) {
      if (pad.includes(` ${t} `)) {
        return true;
      }
    }
  }
  for (const t of CHARGED_TERMS) {
    if (pad.includes(` ${t} `)) {
      return true;
    }
  }
  return false;
}

/** True when a claim is primarily (subject) or secondarily (also_about) about a charged topic. */
function isCharged(c: SearchClaim): boolean {
  return CHARGED.has(c.subject) || c.also_about.some(s => CHARGED.has(s));
}

/** Is this slug a charged entity? (exported for the view's suggestion filter). */
export function isChargedEntity(slug: string): boolean {
  return CHARGED.has(slug);
}

/**
 * Entity-name/synonym index for INTENT detection: phrase (>=3 chars) -> slug over the whole universe
 * (search registry names + synonyms + condition/essential names), longest phrase first so "breast
 * cancer" beats "cancer". Cached once. Charged entities are included — they only match when a charged
 * name/synonym is literally present, which is itself an explicit search.
 */
let phraseCache: { phrase: string; slug: string }[] | null = null;
function entityPhrases(): { phrase: string; slug: string }[] {
  if (phraseCache === null) {
    const arr: { phrase: string; slug: string }[] = [];
    for (const [slug, e] of Object.entries(index().entities)) {
      arr.push({ phrase: e.display_name.toLowerCase(), slug });
      for (const s of e.synonyms) {
        arr.push({ phrase: s.toLowerCase(), slug });
      }
    }
    for (const c of listConditionPages()) {
      arr.push({ phrase: c.name.toLowerCase(), slug: c.slug });
    }
    for (const es of listEssentialPages()) {
      arr.push({ phrase: es.name.toLowerCase(), slug: es.slug });
    }
    const seen = new Set<string>();
    const dedup: { phrase: string; slug: string }[] = [];
    for (const p of arr) {
      if (p.phrase.length >= 3 && !seen.has(p.phrase)) {
        seen.add(p.phrase);
        dedup.push(p);
      }
    }
    phraseCache = dedup.sort((a, b) => b.phrase.length - a.phrase.length);
  }
  return phraseCache;
}

/** The entity a query MENTIONS (a name/synonym appearing whole-word anywhere in it), longest match
 *  first; null if none. Powers intent routing: "what causes cancer" mentions cancer. */
function entityInQuery(q: string): string | null {
  const pad = ` ${q} `;
  for (const { phrase, slug } of entityPhrases()) {
    if (pad.includes(` ${phrase} `)) {
      return slug;
    }
  }
  return null;
}

/**
 * A generous ceiling on the ranked "more answers" — replaces the old hard cap that let the view show
 * only 4 with no way to reach the rest (Luneth 2026-07-23: "no arbitrary truncation"). Typical queries
 * return well under this over the ~321 enriched claims; an exact entity name routes to its topic page
 * instead, so this bound is NOT the "hundreds of entries" surface (that is the deferred inline-claims
 * pass). Every ranked hit up to the ceiling renders — first few visible, the rest behind "See N more".
 */
const ASK_ANSWER_LIMIT = 40;

/** The ranked answers for an Ask query — [0] is the best answer, the rest are "more answers".
 *  Empty when nothing clears the bar. Deterministic (score desc, then id) — no LLM. */
export function askRanked(query: string, limit = 6): SearchClaim[] {
  const q = normalize(query);
  if (q.length < 2) {
    return [];
  }
  const tokens = tokenize(q);
  if (tokens.length === 0) {
    return [];
  }
  // Charged topics (homosexuality/intersex) must never AMBUSH a searcher — a claim about one is
  // ranked only when the query EXPLICITLY names it, never via an incidental body word ("testosterone").
  const allowCharged = chargedExplicit(q);
  const scored = index().claims
    .filter(c => allowCharged || !isCharged(c))
    .map(c => ({ c, s: scoreClaim(c, tokens, q) }));
  const hits = scored.filter(x => x.s > 0);
  hits.sort((a, b) => (b.s - a.s) || (a.c.id < b.c.id ? -1 : a.c.id > b.c.id ? 1 : 0));
  return hits.slice(0, limit).map(x => x.c);
}

/**
 * The topic's OWN name tokens (slug + display name, both singular + plural), so INTENT scoring can
 * DISCOUNT the shared topic word: every claim about antioxidants repeats "antioxidants", so that word
 * carries no signal for picking the best ANSWER within the topic. Multi-word synonyms are deliberately
 * excluded — antioxidants' "what foods fight free radicals" synonym would wrongly eat the word "foods".
 */
function entityNameTokens(slug: string): Set<string> {
  const out = new Set<string>();
  const add = (s: string): void => {
    for (const t of tokenize(s)) {
      out.add(t);
      out.add(t.endsWith('s') ? t.slice(0, -1) : `${t}s`);
    }
  };
  add(slug.replace(/[_-]+/g, ' '));
  const e = getEntity(slug);
  if (e !== null) {
    add(e.display_name);
  }
  return out;
}

/**
 * Re-pick the hero for a mentioned entity by INTENT — the query minus the topic's OWN name. Every claim
 * about antioxidants repeats "antioxidants", so that word can't discriminate the best ANSWER within the
 * topic; a generic claim (a definition, a niche warning) would otherwise win a specific query just by
 * repeating it. We rank only the already-ranked answers ABOUT this subject on the intent tokens, and hero
 * the top; a claim heroes iff it genuinely tops intent (so "...when losing weight" still wins a weight-loss
 * query). Never hides a claim — every answer stays in the ranked "more answers" list. An empty intent (a
 * bare "what is X") returns the top claim unchanged. (memory: search-routing-verify-not-scoreclaim)
 */
function heroByIntent(subject: string, best: SearchClaim, ranked: SearchClaim[], q: string): SearchClaim {
  const strip = entityNameTokens(subject);
  const intent = tokenize(q).filter(t => !strip.has(t));
  if (intent.length === 0) {
    return best;
  }
  let hero = best;
  let heroScore = -1;
  for (const c of ranked) {
    if (c.subject !== subject && !c.also_about.includes(subject)) {
      continue;
    }
    const s = scoreClaim(c, intent, q);
    if (s > heroScore) {
      heroScore = s;
      hero = c;
    }
  }
  return hero;
}

/**
 * Resolve a plain-language query to a render intent. Empty query → the browse LANDING
 * (every entity). A subject/synonym hit → its entity page. Otherwise the best Ask answer;
 * if none clears the bar, the landing with a gentle no-match note.
 */
export function resolveQuery(query: string): SearchResult {
  const q = normalize(query);
  if (q.length === 0) {
    return { mode: 'landing', subject: '', claim: null, claims: [], query: '', noMatch: false };
  }
  // 1. A whole-query name/synonym match resolves straight to that entity page (highest confidence).
  const hit = entityHit(q) ?? wideEntityHit(q);
  if (hit !== null) {
    return { mode: 'entity', subject: hit, claim: null, claims: [], query: q, noMatch: false };
  }
  // 2. Rank claims (charged topics filtered unless named), and detect whether the query MENTIONS an
  //    entity anywhere in it (intent).
  const ranked = askRanked(q, ASK_ANSWER_LIMIT);
  const best = ranked[0];
  const mentioned = entityInQuery(q);
  if (mentioned !== null) {
    // Show the sharp best-answer ONLY when it is PRIMARILY about the mentioned entity; otherwise that
    // entity's own rich page is the honest answer. Kills "what causes cancer" -> a tangential gold claim
    // (best.subject 'gold' !== 'cancer', so we route to the Cancer page, which holds the real answer).
    if (best !== undefined && best.subject === mentioned) {
      // Once the topic is known (an entity is mentioned), rank ITS answers by the query's INTENT — the
      // words other than the topic's own name — and hero the best match. A generic claim (a definition, a
      // niche warning) otherwise wins by merely REPEATING the topic word: "...more antioxidants when losing
      // weight" hijacking "how to get more antioxidants", or "what are antioxidants" hijacking "which foods
      // have the most antioxidants". A bare "what is X" query has no intent words, so the top claim stays.
      const hero = heroByIntent(mentioned, best, ranked, q);
      const claims = hero.id === best.id ? ranked : [hero, ...ranked.filter(c => c.id !== hero.id)];
      return { mode: 'ask', subject: hero.subject, claim: hero, claims, query: q, noMatch: false };
    }
    return { mode: 'entity', subject: mentioned, claim: null, claims: [], query: q, noMatch: false };
  }
  if (best !== undefined) {
    return { mode: 'ask', subject: best.subject, claim: best, claims: ranked, query: q, noMatch: false };
  }
  return { mode: 'landing', subject: '', claim: null, claims: [], query: q, noMatch: true };
}

/** The first registered entity (slug-sorted) — a safe fallback subject. */
export function defaultSubject(): string {
  const keys = Object.keys(index().entities).sort();
  return keys[0] ?? '';
}

/** Total claim count for a subject (for the header readout). */
export function claimCount(subject: string): number {
  const e = getEntity(subject);
  return e !== null ? e.claim_count : claimsForSubject(subject).length;
}

/** Total entities + claims in the index (for the footer readout). */
export function indexTotals(): { entities: number; claims: number } {
  const idx = index();
  return { entities: Object.keys(idx.entities).length, claims: idx.claims.length };
}

/** One facet-family readout for the opening "browse by kind" screen: id (→ CSS data-family +
 *  the view-copy label id), its facets, and the total claim count across them. */
export interface FamilyCount {
  id: string;
  facets: readonly string[];
  count: number;
}
/** Per-family claim counts for the opening screen — facets partitioned by FACET_FAMILIES. */
export function familyCounts(): FamilyCount[] {
  const byFacet = new Map<string, number>();
  for (const c of index().claims) {
    byFacet.set(c.facet, (byFacet.get(c.facet) ?? 0) + 1);
  }
  return FACET_FAMILIES.map(fam => ({
    id: fam.id,
    facets: fam.facets,
    count: fam.facets.reduce((n, f) => n + (byFacet.get(f) ?? 0), 0),
  }));
}

// ─── Entity answer assembly (the CATCH-ALL: ALL of an entity's claims, categorized) ──

/**
 * The catch-all entity result. Gathers EVERY claim about an entity — the enriched Q&A slice (best)
 * PLUS the raw sealed corpus record — and groups them into the five browse FAMILIES (The Science ·
 * What To Do · Wallach's Take · Cautions · The Story), enriched-first within each. So "cancer" is
 * rich (its 65 claims, categorized) rather than a lone hero + a link. The old topic page showed only
 * the ~enriched slice, which left a non-enriched condition empty.
 */
const FACET_FAMILY: ReadonlyMap<string, string> = (() => {
  const m = new Map<string, string>();
  for (const fam of FACET_FAMILIES) {
    for (const f of fam.facets) {
      m.set(f, fam.id);
    }
  }
  return m;
})();

/** One topic inside a browse family: the subject, its in-family claim count, the dominant facet (the
 *  card's micro-label), and a peek — its crispest answer_short. */
export interface FamilyTopic {
  subject: string;
  count: number;
  facet: string;
  peek: string;
}
/**
 * The topics inside a browse FAMILY — every subject with >= 1 claim whose facet belongs to the family,
 * each with its in-family count, its dominant family-facet (the card micro-label), and a peek (its
 * crispest answer_short). Sorted by count desc, then display name. Powers the browse-by-kind grid: a
 * pure filter-and-group over data every claim already carries (facet + subject, both gate-enforced),
 * so it needs no new cataloguing. Grouped by PRIMARY subject only (not also_about), so the per-family
 * topic counts sum to familyCounts()'s total for that family.
 */
export function familyTopics(familyId: string): FamilyTopic[] {
  const bySubject = new Map<string, SearchClaim[]>();
  for (const c of index().claims) {
    if (FACET_FAMILY.get(c.facet) === familyId) {
      const arr = bySubject.get(c.subject);
      if (arr === undefined) {
        bySubject.set(c.subject, [c]);
      }
      else {
        arr.push(c);
      }
    }
  }
  const out: FamilyTopic[] = [];
  for (const [subject, cs] of bySubject) {
    // Peek = the crispest (shortest non-empty) answer_short among this subject's in-family claims;
    // dominant facet = the family facet the subject uses most (its card micro-label).
    let peek = cs[0] as SearchClaim;
    const byFacet = new Map<string, number>();
    for (const c of cs) {
      byFacet.set(c.facet, (byFacet.get(c.facet) ?? 0) + 1);
      const short = c.answer_short.trim();
      const cur = peek.answer_short.trim();
      if (short.length > 0 && (cur.length === 0 || short.length < cur.length)) {
        peek = c;
      }
    }
    let facet: string = (cs[0] as SearchClaim).facet;
    let facetN = -1;
    for (const [f, n] of byFacet) {
      if (n > facetN) {
        facetN = n;
        facet = f;
      }
    }
    out.push({ subject, count: cs.length, facet, peek: peek.answer_short.trim() });
  }
  out.sort((a, b) => (b.count - a.count)
    || (displayName(a.subject).toLowerCase() < displayName(b.subject).toLowerCase() ? -1 : 1));
  return out;
}

/** Corpus colour-category (state/copy::kindCategory) -> the browse family a RAW claim joins. Red
 *  (contraindication) folds into Cautions. Lives in state (not a view), so no colour-literal gate. */
const CATEGORY_FAMILY: Record<string, string> = {
  teal: 'science', green: 'action', orange: 'stance', amber: 'signs', violet: 'story', red: 'signs',
};

/** Entity-page family display order — reads what-it-is -> cautions -> what-to-do -> his take -> story. */
const FAMILY_ORDER: readonly string[] = ['science', 'signs', 'action', 'stance', 'story'];

/** One answer on an entity page — an enriched Q&A (quality 0, best) or a raw record claim (quality 1). */
export interface EntityAnswer {
  id: string;
  quality: 0 | 1;
  familyId: string;
  pill: string;
  title: string;
  prev: string;
  short: string;
  body: string;
  verbatim: string;
}
/** One family group on an entity page — its answers (best-first) + the family total. */
export interface EntityFamily {
  familyId: string;
  count: number;
  answers: EntityAnswer[];
}

/** True when a slug resolves to any entity in the full universe (search registry OR a page). */
export function entityExists(slug: string): boolean {
  return getEntity(slug) !== null || getConditionPage(slug) !== null || getEssentialPage(slug) !== null;
}

/**
 * ALL of an entity's answers, grouped into the five families, enriched-Q&A first then raw record.
 * Conditions/essentials draw from the entity-page record (raw) + search (enriched); a topic (a search
 * entity with no page) has only its enriched claims. Dedup by id so an enriched claim never doubles as
 * its own raw row.
 */
export function entityFamilies(subject: string): EntityFamily[] {
  const cond = getConditionPage(subject);
  const ess = cond === null ? getEssentialPage(subject) : null;
  const page = cond ?? ess;

  const answers: EntityAnswer[] = [];
  const seen = new Set<string>();

  const enriched: SearchClaim[] = page !== null
    ? page.search.flatMap(g => g.claim_ids).map(getSearchClaim).filter((c): c is SearchClaim => c !== null)
    : claimsForSubject(subject);
  for (const c of enriched) {
    if (seen.has(c.id)) {
      continue;
    }
    seen.add(c.id);
    answers.push({
      id: c.id, quality: 0, familyId: FACET_FAMILY.get(c.facet) ?? 'science', pill: facetLabel(c.facet),
      title: c.question, prev: c.answer_short, short: c.answer_short,
      body: c.answer.trim() === c.answer_short.trim() ? '' : c.answer, verbatim: c.verbatim,
    });
  }

  if (page !== null) {
    for (const cc of resolveClaims(page.record.flatMap(g => g.claim_ids))) {
      if (seen.has(cc.id)) {
        continue;
      }
      seen.add(cc.id);
      answers.push({
        id: cc.id, quality: 1, familyId: CATEGORY_FAMILY[kindCategory(cc.kind)] ?? 'science', pill: kindLabel(cc.kind),
        title: softClamp(cc.claim_text, 116), prev: '', short: '', body: cc.claim_text, verbatim: cc.verbatim,
      });
    }
  }

  const out: EntityFamily[] = [];
  for (const fid of FAMILY_ORDER) {
    const inFam = answers.filter(a => a.familyId === fid);
    if (inFam.length === 0) {
      continue;
    }
    inFam.sort((a, b) => a.quality - b.quality);
    out.push({ familyId: fid, count: inFam.length, answers: inFam });
  }
  return out;
}

/**
 * Related entities to "keep exploring" from an entity page — only those that resolve to a page (so
 * every pill is a live jump). Conditions surface their related + tied conditions + restore nutrients;
 * essentials their related + tied conditions + interaction partners; a topic its registry `related`.
 * Deduped, the subject itself excluded, capped.
 */
export function relatedSlugs(subject: string): string[] {
  const cond = getConditionPage(subject);
  const ess = cond === null ? getEssentialPage(subject) : null;
  const raw = cond !== null
    ? [...cond.related, ...cond.related_conditions, ...cond.restore]
    : ess !== null
      ? [...ess.related, ...ess.conditions, ...ess.works_with]
      : (getEntity(subject)?.related ?? []);
  const out: string[] = [];
  const seen = new Set<string>([subject]);
  for (const s of raw) {
    if (!seen.has(s) && entityExists(s)) {
      seen.add(s);
      out.push(s);
    }
  }
  return out.slice(0, 8);
}

// ─── Bridge (window.* — reached by headless probes + the topbar search bar) ──

const bridge = window as Window & {
  wallachSearch?: {
    resolveQuery: typeof resolveQuery;
    facetGroups: typeof facetGroups;
    getEntity: typeof getEntity;
    composeCite: typeof composeCite;
    defaultSubject: typeof defaultSubject;
    entityList: typeof entityList;
    indexTotals: typeof indexTotals;
    familyCounts: typeof familyCounts;
    familyTopics: typeof familyTopics;
    entityFamilies: typeof entityFamilies;
    oracClaims: typeof oracClaims;
  };
};
bridge.wallachSearch = { resolveQuery, facetGroups, getEntity, composeCite, defaultSubject, entityList, indexTotals, familyCounts, familyTopics, entityFamilies, oracClaims };
