/**
 * core/schemas/efa-coverage.ts — the essential-fatty-acid coverage metric schema
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/efa-coverage-data.json (GENERATED by
 * eden/tools/efa_coverage_derive.py) at the Zod boundary in state/coverage.ts.
 *
 * omega-3 + omega-6 carry no individual Wallach dose; Wallach states ONE amount for
 * the essential fatty acids as a CATEGORY ("supplemented at the rate of 9 grams per
 * day in capsule form", WAL-CLM-DDDL-000115), and his EFAs are exactly two: "only
 * two (linoleic and linolenic) are designated as Essential Fatty Acids". So they are
 * scored as ONE group — the sum of each regimen product's efa_mg over
 * goal.maintenance_mg — exactly as the 33 trace_pdm rare-earths share the PDM meter.
 *
 * ★ omega-9 is NOT a member. Wallach never names oleic acid an essential fatty acid,
 * so a product's oleic mg is deliberately absent from efa_mg: crediting it would
 * measure intake against a requirement he never stated.
 *
 * §00.A: the goal is Wallach's own number in a different unit (9 g -> 9000 mg, a unit
 * change of a figure he wrote, not a new amount — it cites source_claim_id); each
 * per-product efa_mg is product COMPOSITION, never a target. No number is authored in
 * a view (R1/R4) — this whole file is a pillar projection.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/** Root shape of efa-coverage-data.json (the `_purpose` header key is ignored). */
export const EfaCoverageSchema = z.object({
  goal: z.object({
    collective_group: z.string(),
    maintenance_mg: z.number(),
    members: z.array(z.string()),
    unit: z.string(),
    source_claim_id: z.string(),
  }).passthrough(),
  products: z.record(z.object({
    canonical_name: z.string(),
    efa_mg: z.number(),
    by_member: z.record(z.number()),
  }).passthrough()),
}).passthrough();
export type EfaCoverage = z.infer<typeof EfaCoverageSchema>;
