/**
 * core/schemas/entity-page.ts — Zod boundary for the per-entity page view-model (Phase H2)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Types dashboard/assets/data/entity-page-data.json (GENERATED by
 * eden/tools/entity_page_derive.py). LEAN by design: each record holds claim IDs +
 * derived extras only — claim text / verbatim / citation resolve AT RENDER from the
 * corpus embed (state/corpus) + the search index (state/search). The view never holds
 * a canonical value as a literal; it projects these IDs (§00.B single-source, R1).
 *
 * The relations are pre-computed upstream (H1): `conditions`/`restore` are the DIRECTED
 * maps(E,C) pills (not co-occurrence — that is `related`); `works_with` is interaction-kind
 * only; `protocol_claim_ids` drops base-line-table rows (prominence). The view reads these
 * as given and must NOT re-derive pills from co-occurrence — that reopens the Audit-B leak.
 * ═══════════════════════════════════════════════════════════════════════════
 */
import { z } from 'zod';

/** One record group: a raw corpus claim.kind + the claim IDs of that kind (corpus-embed ids). */
export const EntityKindGroupSchema = z.object({
  kind: z.string(),
  claim_ids: z.array(z.string()),
});

/** One search group: a facet + its search-index claim IDs (a subset of the corpus ids). */
export const EntityFacetGroupSchema = z.object({
  facet: z.string(),
  claim_ids: z.array(z.string()),
});

/** An essential's page view-model — entity-page-data.json → essentials[slug]. */
export const EssentialPageSchema = z.object({
  type: z.literal('essential'),
  // `name` carries the FRIENDLY name (common_name, e.g. 'Vitamin A') — the H1 label.
  name: z.string(),
  /** Scientific name (e.g. 'Retinol') — the entity-page "also known as" detail; == name when no split. */
  scientific_name: z.string(),
  symbol: z.string().nullable(),
  category: z.string().nullable(),
  is_essential: z.boolean(),
  claim_count: z.number(),
  /** TILE/HERO count: distinct claims on the element-SPECIFIC surfaces (Full Record UNION Worth
   * Knowing, deduped) -- EXCLUDES the shared plant-derived group_record. claim_count above stays
   * the operational-only number that labels "The full record - All N". See entity_page_derive.py. */
  distinct_claim_count: z.number(),
  books: z.array(z.string()),
  synonyms: z.array(z.string()),
  record: z.array(EntityKindGroupSchema),
  /** Rows in "The full record" AFTER enriched claims are removed (they render once, above, as
   * Worth-Knowing cards). This labels "All N claims" and the filter placeholder; claim_count
   * stays the operational total. Disjoint from `search` by construction — see entity_page_derive.py. */
  record_claim_count: z.number(),
  search: z.array(EntityFacetGroupSchema),
  /** DIRECTED maps(E,C) pills — conditions this essential is Wallach-tied to (H1). */
  conditions: z.array(z.string()),
  /** Genuine interaction-kind partners (H1) — NOT co-occurrence. */
  works_with: z.array(z.string()),
  /** Co-occurrence "keep exploring" graph (mixed essential + condition slugs). */
  related: z.array(z.string()),
  /** GROUP claims propagated onto plant-derived (trace_pdm) element pages: shared search-index
   * claim IDs authored `about: [colloidal-minerals]`, rendered as a distinct "shared across
   * the plant-derived group" section so a user does not misread them as strontium-specific.
   * Present ONLY on the 35 trace_pdm slugs; omitted elsewhere. Grouped by enrichment FACET
   * ({facet, claim_ids}) — like `search`, not `record` — so the shared cards spread across the
   * facet taxonomy (HISTORY & LORE, SOURCES, ...) instead of two teal kind blocks (Luneth 2026-07-22). */
  group_record: z.array(EntityFacetGroupSchema).optional(),
});

/** A condition's page view-model — entity-page-data.json → conditions[slug]. */
export const ConditionPageSchema = z.object({
  type: z.literal('condition'),
  name: z.string(),
  claim_count: z.number(),
  books: z.array(z.string()),
  synonyms: z.array(z.string()),
  /** Curated "what to do": protocol-kind then non-base-line-table dose claims (prominence). */
  protocol_claim_ids: z.array(z.string()),
  /** DIRECTED maps(E,C) pills — nutrients to restore for this condition (H1). */
  restore: z.array(z.string()),
  record: z.array(EntityKindGroupSchema),
  /** Rows in "The full record" AFTER enriched claims are removed (they render once, above, as
   * Worth-Knowing cards). This labels "All N claims" and the filter placeholder; claim_count
   * stays the operational total. Disjoint from `search` by construction — see entity_page_derive.py. */
  record_claim_count: z.number(),
  search: z.array(EntityFacetGroupSchema),
  related_conditions: z.array(z.string()),
  related: z.array(z.string()),
});

/** The whole generated artifact. _meta is provenance/counts — not consumed typed (passthrough). */
export const EntityPageDataSchema = z.object({
  _meta: z.unknown().optional(),
  essentials: z.record(EssentialPageSchema),
  conditions: z.record(ConditionPageSchema),
});

export type EntityKindGroup = z.infer<typeof EntityKindGroupSchema>;
export type EntityFacetGroup = z.infer<typeof EntityFacetGroupSchema>;
export type EssentialPage = z.infer<typeof EssentialPageSchema>;
export type ConditionPage = z.infer<typeof ConditionPageSchema>;
export type EntityPageData = z.infer<typeof EntityPageDataSchema>;
