/**
 * core/schemas/entity-page.ts — Zod boundary for the per-entity page view-model (Phase H2)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Types dashboard/assets/data/entity-page-data.json (GENERATED by
 * eden/tools/entity_page_derive.py). LEAN by design: each record holds claim IDs +
 * derived extras only — claim text / verbatim / citation resolve AT RENDER from the
 * corpus embed (state/corpus) + the search index (state/search). The view never holds
 * a canonical value as a literal; it projects these IDs (§00.B single-source, R1).
 *
 * The relations are pre-computed upstream (H1): `conditions`/`restore` are the DIRECTED
 * maps(E,C) pills (not co-occurrence — that is `related`); `works_with` is interaction-kind
 * only; `protocol_claim_ids` drops base-line-table rows (prominence). The view reads these
 * as given and must NOT re-derive pills from co-occurrence — that reopens the Audit-B leak.
 * ═══════════════════════════════════════════════════════════════════════════
 */
import { z } from 'zod';

/** One record group: a raw corpus claim.kind + the claim IDs of that kind (corpus-embed ids). */
export const EntityKindGroupSchema = z.object({
  kind: z.string(),
  claim_ids: z.array(z.string()),
});

/** One search group: a facet + its search-index claim IDs (a subset of the corpus ids). */
export const EntityFacetGroupSchema = z.object({
  facet: z.string(),
  claim_ids: z.array(z.string()),
});

/** An essential's page view-model — entity-page-data.json → essentials[slug]. */
export const EssentialPageSchema = z.object({
  type: z.literal('essential'),
  name: z.string(),
  symbol: z.string().nullable(),
  category: z.string().nullable(),
  is_essential: z.boolean(),
  claim_count: z.number(),
  books: z.array(z.string()),
  synonyms: z.array(z.string()),
  one_liner: z.string().nullable(),
  record: z.array(EntityKindGroupSchema),
  search: z.array(EntityFacetGroupSchema),
  /** DIRECTED maps(E,C) pills — conditions this essential is Wallach-tied to (H1). */
  conditions: z.array(z.string()),
  /** Genuine interaction-kind partners (H1) — NOT co-occurrence. */
  works_with: z.array(z.string()),
  /** Co-occurrence "keep exploring" graph (mixed essential + condition slugs). */
  related: z.array(z.string()),
});

/** A condition's page view-model — entity-page-data.json → conditions[slug]. */
export const ConditionPageSchema = z.object({
  type: z.literal('condition'),
  name: z.string(),
  claim_count: z.number(),
  books: z.array(z.string()),
  synonyms: z.array(z.string()),
  one_liner: z.string().nullable(),
  /** Curated "what to do": protocol-kind then non-base-line-table dose claims (prominence). */
  protocol_claim_ids: z.array(z.string()),
  /** DIRECTED maps(E,C) pills — nutrients to restore for this condition (H1). */
  restore: z.array(z.string()),
  record: z.array(EntityKindGroupSchema),
  search: z.array(EntityFacetGroupSchema),
  related_conditions: z.array(z.string()),
  related: z.array(z.string()),
});

/** The whole generated artifact. _meta is provenance/counts — not consumed typed (passthrough). */
export const EntityPageDataSchema = z.object({
  _meta: z.unknown().optional(),
  essentials: z.record(EssentialPageSchema),
  conditions: z.record(ConditionPageSchema),
});

export type EntityKindGroup = z.infer<typeof EntityKindGroupSchema>;
export type EntityFacetGroup = z.infer<typeof EntityFacetGroupSchema>;
export type EssentialPage = z.infer<typeof EssentialPageSchema>;
export type ConditionPage = z.infer<typeof ConditionPageSchema>;
export type EntityPageData = z.infer<typeof EntityPageDataSchema>;
