/**
 * core/schemas/foods-composition.ts — the food catalog's composition schema
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/foods-composition-data.json (GENERATED by
 * eden/tools/foods_composition_derive.py) at the Zod boundary in state/foods.ts.
 *
 * ★ WHOSE NUMBERS ARE IN HERE. `amount` and `per_100g` are COMPOSITION — what a food
 * CONTAINS — and they come from a pinned outside source, not from Wallach. `fraction` is that
 * composition measured against WALLACH'S OWN daily target, read from
 * essentials-targets-data.json. So every denominator is his and every numerator is a
 * published table's, exactly the arithmetic a Youngevity label already performs on the product
 * side. Admitted by owner ruling 2026-08-21 (chronicle/contradictions/2026-08-21-usda-food-
 * composition-third-source.md). No target, dose, range, deficiency sign or health claim
 * comes from this file — §00.A is untouched by it.
 *
 * ★ TWO SOURCES, TWO TIERS, AND THE SURFACE SAYS WHICH. Most rows come from the pinned USDA
 * SR Legacy archive. The rest come from the second sources pinned in
 * eden/foods/sources/sources.json, admitted by the same owner ruling to reach essentials SR
 * Legacy does not measure at all. `provenance.tier` is EXACT when the two tables were joined
 * by an id they both carry (the NDB number) and APPROXIMATE when they were joined by the
 * source's own food NAME — a human decision, one per pair, whose reasoning rides along in
 * `provenance.why`. The tier is DERIVED FROM THE JOIN in the generator and re-checked by
 * `food_composition_traces_to_source`; it is never a label someone typed.
 *
 * ★ `per_100g` IS A STRING ON PURPOSE. Where the source publishes the value as one cell it is
 * that cell's own unparsed text, carried through so the gate can byte-compare it against the
 * row it came from. Parsing it here would destroy the only thing that makes the number
 * provable. Never "clean it up" to a number.
 *
 * ★ A FOOD CANNOT NAME A PRESENCE-COVERED ESSENTIAL. The generator emits a row only for an
 * essential carrying a NUMERIC Wallach target, so silver, the twelve amino acids and the 34
 * trace_pdm minerals are absent by construction — they cover on the mere presence of a
 * source, and a food entering there would turn them green with nothing compared.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/**
 * One component total behind a SUMMED value.
 *
 * USDA publishes flavonoids as one row per compound and proanthocyanidins in a separate
 * database again, so a food's flavonoid total is Σ of its component rows across both. Those
 * components ride along here so the total is never an unsupported number: the gate re-sums
 * them and compares.
 */
export const FoodValuePartSchema = z.object({
  /** The candidate file this part was read from, by stem. */
  source: z.string(),
  /** How many component rows were summed. */
  rows: z.number(),
  /** This part's own total, as the decimal string the generator produced. */
  total: z.string(),
}).passthrough();

/** Where one nutrient row's number came from, and how far it can be trusted. */
export const FoodProvenanceSchema = z.object({
  /** 'usda-sr-legacy', or the second source's id from sources.json. */
  source_id: z.string(),
  /**
   * EXACT — joined by an id both tables carry, no human judgment in the join.
   * APPROXIMATE — joined by the source's own food name, one human decision per pair.
   * Derived from the join in the generator, never typed per row.
   */
  tier: z.enum(['EXACT', 'APPROXIMATE']),
  /** The join that produced this row, e.g. 'ndb:09042' or 'name:Dates, dried'. */
  join: z.string(),
  /** 'cell' — one cell of the source. 'sum' — Σ of component rows (see `parts`). */
  value_kind: z.string(),
  /** Present when value_kind is 'sum'. */
  parts: z.array(FoodValuePartSchema).optional(),
  /** APPROXIMATE only: the human reasoning that accepted this pair. */
  why: z.string().optional(),
  /**
   * True when the source measured SEVERAL VARIETIES of what our generic row calls one food
   * (red and green lentils, smooth and fibrous mango) and the curation took the LOWEST.
   * The card says so: an understated number that reads as an exact one is a quieter kind of
   * overstatement than a wrong number, and harder to notice.
   */
  conservative: z.boolean().optional(),
}).passthrough();

/** One essential a single serving of a food delivers a meaningful amount of. */
export const FoodNutrientSchema = z.object({
  /** The canon essential slug this row credits. Always one with a numeric Wallach target. */
  slug: z.string(),
  /** Amount in ONE serving, expressed in Wallach's own unit for this essential. */
  amount: z.number(),
  /** Wallach's unit for this essential ('mg' | 'mcg'), copied from his target. */
  unit: z.string(),
  /** amount / Wallach's daily target. >= the artifact's qualify_fraction, by construction. */
  fraction: z.number(),
  /** True at or above the artifact's strong_fraction — the UI's "strong source" mark. */
  strong: z.boolean(),
  /** The source row's own text, UNPARSED where the source prints one cell. Never parse it. */
  per_100g: z.string(),
  /** Where this number came from and how far it can be trusted. Present on EVERY row. */
  provenance: FoodProvenanceSchema,
  /** USDA rows only: the USDA unit the per_100g figure is in ('MG' | 'UG'). */
  usda_unit: z.string().optional(),
  /** USDA rows only: nutrient_id — the other half of the join key. */
  nutrient_id: z.string().optional(),
  /** Second-source rows only: the unit the source publishes its value in. */
  source_unit: z.string().optional(),
}).passthrough();

/** One food the Regimen and Coverage tabs may recommend. */
export const FoodSchema = z.object({
  /** Stable slug, from the curation. The regimen stores this, not the name. */
  id: z.string(),
  /** Display name, hand-curated. Never USDA's raw description. */
  name: z.string(),
  category: z.string(),
  /** USDA join keys, carried so any number on screen can be traced back. */
  fdc_id: z.string(),
  usda_description: z.string(),
  portion_id: z.string(),
  /** USDA's own words for the serving ('1 cup', '3 oz', '1 large'). */
  portion_label: z.string(),
  grams: z.number(),
  nutrients: z.array(FoodNutrientSchema),
  /**
   * Essential-fatty-acid delivery, in the currency Wallach's dose is stated in: grams of an
   * oil HE prescribes. Absent on a food with no measured 18:2, 18:3, 20:5 or 22:6.
   *
   * ★ TWO OILS, SUMMED (owner ruling, Luneth 2026-08-31). He names two and doses them
   * interchangeably — "taken alternately as salmon oil and flaxseed oil at the rate of 5
   * grams t.i.d." — so the plant share (18:2 + 18:3 − CLA) converts against FLAXSEED oil and
   * the marine share (20:5 + 22:6) against SALMON oil, and the two oil masses add. Flaxseed
   * oil carries none of the marine forms, so one oil for both shares under-reported every
   * oily fish by roughly 25x: canned salmon read 1.5% of his nine grams and did not appear
   * on the omega-3 list at all.
   *
   * ★ WHY NOT A NUTRIENT ROW. omega-3 and omega-6 carry no individual Wallach target — he
   * states ONE amount for the essential fatty acids as a category — so a food credited
   * against either would be measured against a number that does not exist, and the
   * composition gate REDs exactly that. The EFAs share one meter instead, the same shape the
   * 34 plant-derived minerals already use.
   */
  efa: z.object({
    /** Every counted acid one serving delivers: plant + marine, CLA already subtracted. */
    acid_mg: z.number(),
    /** The plant half of `acid_mg` — 18:2 + 18:3 − CLA. */
    plant_acid_mg: z.number(),
    /** The marine half of `acid_mg` — 20:5 + 22:6. Zero on everything that is not seafood. */
    marine_acid_mg: z.number(),
    /**
     * Those acids re-expressed as the oil it would take to supply them, EACH against its own
     * oil, then summed. This is the number the card prints and the meter counts.
     */
    oil_equivalent_mg: z.number(),
    /** The plant acid over flaxseed oil's own EFA fraction. */
    plant_oil_equivalent_mg: z.number(),
    /** The marine acid over salmon oil's own EFA fraction. */
    marine_oil_equivalent_mg: z.number(),
    /**
     * That oil over `_meta.efa_goal.maintenance_mg` — the same shape a nutrient row's
     * `fraction` has, against the same kind of denominator (a Wallach number).
     */
    fraction: z.number(),
    /**
     * Whether the group clears `_meta.qualify_fraction`, the identical bar a nutrient row
     * must clear to exist at all.
     *
     * ★ READ THIS FLAG; NEVER RE-DERIVE IT FROM `fraction`. The generator tests the
     * FULL-PRECISION fraction and stores it rounded to 4 dp, exactly as it does for a row,
     * so a food just under the bar can carry `fraction: 0.07` and `qualifies: false`
     * (kiwifruit, at 6.996%). Re-deriving it in a view would disagree with the ranking on
     * seven of the 192 foods, and the card and the order would tell different stories.
     */
    qualifies: z.boolean(),
    /** At or above `_meta.strong_fraction`, mirroring a row's own `strong`. */
    strong: z.boolean(),
  }).passthrough().optional(),
  /** How many essentials this food credits overall. */
  breadth: z.number(),
  /**
   * The ranking key: Σ of every qualifying fraction one serving delivers — nutrient rows
   * PLUS the EFA group, counted once, uncapped.
   *
   * ★ THE EFA GROUP IS IN HERE, and was not until 2026-08-22. It is not a row (see `efa`
   * above), so a Σ over rows scored walnuts — 220% of Wallach's nine grams — at 0.38 and
   * dropped them to page 47 of 64 in a list ordered by nutrition, while the card beside it
   * printed the 220%. Uncapped because every other term is: capping this one alone would
   * leave the group the single under-weighted term against rows that routinely run 200–300%.
   * Counted ONCE and never per member — omega-3 and omega-6 share one meter because Wallach
   * states one amount, and fanning it would invent two he never gave.
   */
  strength: z.number(),
}).passthrough();

/** Root shape of foods-composition-data.json (`_purpose` is ignored). */
export const FoodsCompositionSchema = z.object({
  _meta: z.object({
    /** The fraction of a Wallach target one serving must deliver to be credited (0.07). */
    qualify_fraction: z.number(),
    /** At or above this fraction the food is a STRONG source (0.20). */
    strong_fraction: z.number(),
    /** The essentials any pinned source can measure — the only ones a food can ever move. */
    essentials_measurable: z.array(z.string()),
    /**
     * slug → the SHORT display name a tile chip can hold, plus the canon's own category.
     * Derived from the canon in the generator, never typed in a view (R3). `category` is
     * passed through unmapped so the card picks its colour straight from it and no
     * category-to-colour table exists in two places.
     */
    essential_display: z.record(z.object({
      label: z.string(),
      category: z.string(),
    }).passthrough()),
    /**
     * The essentials that come from a source OTHER than SR Legacy, by slug: which source,
     * at which tier, and the words the surface uses for it. `display` lives in the data
     * because a source name hand-typed into a view is a second home for a fact (R3) — and
     * it is exactly how a card would keep saying "USDA" about a number that stopped coming
     * from USDA.
     */
    second_sources: z.record(z.object({
      source_id: z.string(),
      tier: z.enum(['EXACT', 'APPROXIMATE']),
    }).passthrough()),
    /**
     * source_id → the words the card uses for that source. Keyed by SOURCE, not by
     * essential, because one essential can resolve to either of two publications depending
     * on the food — sulfur reads from AFCD where AFCD measured it and from Doleman where it
     * did not — and the card has to name the one that actually supplied the number.
     */
    source_display: z.record(z.string()),
    /**
     * Essentials with a numeric Wallach target that are NOT BOUND to any composition source.
     * Carried so the gap is legible on screen rather than silently absent. No food can cover
     * these today; only a product can.
     *
     * ★ "NOT BOUND" IS NOT "NOT MEASURABLE". Four of them — sulfur, chloride, biotin,
     * molybdenum — are measured by a source already pinned in sources.json that nothing
     * reads yet. They are listed here because the binding work is not done, not because the
     * food world has nothing to say about them. Never let this list read as a finding.
     */
    essentials_without_composition: z.array(z.string()),
    /**
     * The TWO reference oils Wallach names, read from the pinned archive — the bridge
     * between what USDA measures in a food (acid) and what his dose is stated in (oil).
     *
     * ★ `efa_fraction` IS FLAXSEED OIL'S, and stays that way. The marine oil sits beside it
     * under `marine`, never in place of it: re-pointing a published key at a different
     * quantity is the token-indirection failure this project keeps meeting.
     */
    efa_reference: z.object({
      efa_fraction: z.number(),
      label: z.string(),
      category: z.string(),
      /** Salmon oil — the denominator for the 20:5/22:6 share. */
      marine: z.object({
        fdc_id: z.string(),
        efa_fraction: z.number(),
      }).passthrough(),
    }).passthrough(),
    /**
     * Wallach's ONE amount for the EFA group, in the mg of oil the meter counts —
     * the denominator every food's `efa.fraction` is over. Read in the generator straight
     * from the sealed dose claim it cites, so a food and a product are scored against one
     * Wallach number rather than two copies of it.
     */
    efa_goal: z.object({
      maintenance_mg: z.number(),
      unit: z.string(),
      collective_group: z.string(),
      source_claim_id: z.string(),
    }).passthrough(),
    food_count: z.number(),
  }).passthrough(),
  foods: z.array(FoodSchema),
}).passthrough();

export type Food = z.infer<typeof FoodSchema>;
