/**
 * core/schemas/orac-data.ts — the ORAC knowledge tab's canonical-numbers schema (Phase 2)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/orac-data.json (GENERATED by
 * eden/tools/orac_data_derive.py) at the Zod boundary in state/orac.ts.
 *
 * Every field is a Wallach number PARSED from a sealed claim's byte-faithful verbatim
 * (the source claims carry dose == null), so it has exactly one home (R1/R3/§00.A): the
 * §02/§03/§08 narrative sections interpolate these numbers into the framing prose that
 * lives in view-copy.json. No ORAC number is authored in a view or in the prose store.
 *
 * `_purpose` (the artifact's self-documenting header) is stripped by z.object.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

const Sourced = { source_claim_id: z.string() };

/** Root shape of orac-data.json. */
export const OracDataSchema = z.object({
  /** §02 mirror-test — Adelman aging-pigment decade table (bar height = pct). */
  decades: z.object({
    ...Sourced,
    cite: z.string(),
    rows: z.array(z.object({
      age: z.string(),
      pct: z.number(),
    })),
  }),
  /** §02 stolen-years — the 20–25 year gap + the should-average / actual figures. */
  stolen_years: z.object({
    ...Sourced,
    low: z.number(),
    high: z.number(),
    display: z.string(),
    should_low: z.number(),
    should_high: z.number(),
    actual: z.number(),
  }),
  /** §02 rankings — the US world-longevity decline (year → rank progression). */
  rankings: z.object({
    ...Sourced,
    cite: z.string(),
    points: z.array(z.object({
      year: z.number(),
      rank: z.number(),
    })),
  }),
  /** §03 daily target — 20,000–25,000 ORAC/day; base_age (100) feeds the §08 ceiling. */
  target: z.object({
    ...Sourced,
    low: z.number(),
    high: z.number(),
    low_display: z.string(),
    high_display: z.string(),
    base_age: z.number(),
  }),
  /** §03 disease dose — the >100,000 ORAC/day neurological-disease figure. */
  disease_target: z.object({
    ...Sourced,
    min: z.number(),
    display: z.string(),
    min_display: z.string(),
  }),
  /** §08 piece 2 — the calorie-restricted band (1,250–1,800). */
  calories: z.object({
    ...Sourced,
    low: z.number(),
    high: z.number(),
    display: z.string(),
  }),
  /** §08 payoff — +25–50 healthful years for a 150–175 lb person. */
  payoff: z.object({
    ...Sourced,
    cite: z.string(),
    years_low: z.number(),
    years_high: z.number(),
    years_display: z.string(),
    weight_low: z.number(),
    weight_high: z.number(),
    weight_display: z.string(),
  }),
  /** §08 forces intro — base age (100), the ceiling (150), and the gap between (50). */
  ceiling: z.object({
    ...Sourced,
    base_claim_id: z.string(),
    base: z.number(),
    ceiling: z.number(),
    gap: z.number(),
  }),
});
export type OracData = z.infer<typeof OracDataSchema>;
