/**
 * core/schemas/orac-foods-data.ts — the ORAC tab's food league-tables schema
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/orac-foods-data.json (GENERATED by
 * eden/tools/orac_foods_derive.py) at the Zod boundary in state/orac-foods.ts.
 *
 * Every ORAC score is PARSED from a sealed food_source claim's byte-faithful verbatim
 * (the 5 source claims carry dose == null), so it has exactly one home (R1/R3/§00.A): the
 * sections 04–06 food figures interpolate these numbers into framing prose that lives in
 * view-copy.json. No ORAC score is authored in a view, in view-copy, or in the curation —
 * the curation (orac-foods-curation.json) decides only names/grouping/colour/selection.
 *
 * `_purpose` (the artifact's self-documenting header) is stripped by z.object.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/** One §06 category row: display name + comma-grouped value. (`bar` is legacy — the field
 *  plot computes every dot position at render from value_display and never reads it.) */
const TableRow = z.object({
  name: z.string(),
  value_display: z.string(),
  bar: z.number(),
});

/** Root shape of orac-foods-data.json. */
export const OracFoodsDataSchema = z.object({
  /** §04 REACH — each curated food as % of the daily target (pct is the label, may exceed 100). */
  reach: z.object({
    source_claim_id: z.string(),
    target: z.number(),
    target_display: z.string(),
    cite: z.string(),
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      pct: z.number(),
      over: z.boolean(),
    })),
  }),
  /** §05 SCALE — spice-outlier bars relative to the first (cloves); max_display fills the note. */
  scale: z.object({
    max_display: z.string(),
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      value: z.number(),
      value_display: z.string(),
      bar: z.number(),
    })),
  }),
  /** §06 THE FIELD — the category rows the single-axis food field plots (one dot per row;
   *  positions are computed at render from value_display — see views/knowledge-orac.ts::renderField). */
  tables: z.object({
    categories: z.array(z.object({
      key: z.string(),
      label: z.string(),
      color: z.string(),
      basis: z.string(),
      rows: z.array(TableRow),
    })),
  }),
  /** The four wines as scale-style bars. NOT CURRENTLY RENDERED: no view reads this member —
   *  the wines now draw as the `wine` category inside `tables`, and the §07 slot is Best
   *  Supplement Sources (orac-products-data.json). Kept required so the derive keeps emitting it. */
  wine: z.object({
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      value_display: z.string(),
      bar: z.number(),
    })),
  }),
});
export type OracFoodsData = z.infer<typeof OracFoodsDataSchema>;
