/**
 * core/schemas/orac-foods-data.ts — the ORAC tab's food league-tables schema (Phase 3b)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/orac-foods-data.json (GENERATED by
 * eden/tools/orac_foods_derive.py) at the Zod boundary in state/orac-foods.ts.
 *
 * Every ORAC score is PARSED from a sealed food_source claim's byte-faithful verbatim
 * (the 5 source claims carry dose == null), so it has exactly one home (R1/R3/§00.A): the
 * sections 04–07 food tables interpolate these numbers into framing prose that lives in
 * view-copy.json. No ORAC score is authored in a view, in view-copy, or in the curation —
 * the curation (orac-foods-curation.json) decides only names/grouping/colour/selection.
 *
 * `_purpose` (the artifact's self-documenting header) is stripped by z.object.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/** One §06 league-table / §07 wine row: display name + comma-grouped value + bar % (0–100). */
const TableRow = z.object({
  name: z.string(),
  value_display: z.string(),
  bar: z.number(),
});

/** Root shape of orac-foods-data.json. */
export const OracFoodsDataSchema = z.object({
  /** §04 REACH — each curated food as % of the daily target (pct is the label, may exceed 100). */
  reach: z.object({
    source_claim_id: z.string(),
    target: z.number(),
    target_display: z.string(),
    cite: z.string(),
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      pct: z.number(),
      over: z.boolean(),
    })),
  }),
  /** §05 SCALE — spice-outlier bars relative to the first (cloves); max_display fills the note. */
  scale: z.object({
    max_display: z.string(),
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      value: z.number(),
      value_display: z.string(),
      bar: z.number(),
    })),
  }),
  /** §06 TABLES — the category league tables (bars relative to each category's own max). */
  tables: z.object({
    categories: z.array(z.object({
      key: z.string(),
      label: z.string(),
      color: z.string(),
      basis: z.string(),
      rows: z.array(TableRow),
    })),
  }),
  /** §07 WINE — the four wines as scale-style bars (relative to Cabernet). */
  wine: z.object({
    rows: z.array(z.object({
      name: z.string(),
      color: z.string(),
      value_display: z.string(),
      bar: z.number(),
    })),
  }),
});
export type OracFoodsData = z.infer<typeof OracFoodsDataSchema>;
