/**
 * core/schemas/orac-products-data.ts — the ORAC tab's §07 "Best Supplement Sources" schema
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/orac-products-data.json (GENERATED by
 * eden/tools/orac_products_derive.py) at the Zod boundary in state/orac-products.ts.
 *
 * These ORAC scores are YOUNGEVITY OFFICIAL, lab-tested per-serving values (source: ygy) —
 * NOT Wallach numbers and NOT parsed from the corpus. Product ORAC is composition /
 * measured-property data (what a serving delivers); §00.A lets Youngevity supply + surface
 * composition (Luneth-confirmed framing 2026-07-24). The numbers have ONE hand-authored home
 * (orac-products-curation.json); the generator joins each product_id with the product pillar
 * for name+form and prices.json for the wholesale price, so nothing is re-typed in a view.
 *
 * `_purpose` (the artifact's self-documenting header) is stripped by z.object.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/** One supplement: its pillar id (opens the detail page), name, delivery form, ORAC score,
 *  wholesale price, and the ORAC-per-wholesale-dollar VALUE figure (all *_display pre-formatted). */
const OracProduct = z.object({
  product_id: z.string(),
  name: z.string(),
  form: z.string(),
  orac: z.number(),
  orac_display: z.string(),
  price_wholesale: z.number(),
  price_display: z.string(),
  value: z.number(),
  value_display: z.string(),
});

/** Root shape of orac-products-data.json. The `leader` is the standout top scorer (rendered as a
 *  hero card, no bar); `rows` are the runners-up with a `bar` scaled to the runner-up field's max. */
export const OracProductsDataSchema = z.object({
  source: z.string(),
  cite: z.string(),
  untested_note: z.string(),
  leader: OracProduct,
  rows: z.array(OracProduct.extend({ bar: z.number() })),
});
export type OracProductsData = z.infer<typeof OracProductsDataSchema>;
