/**
 * core/schemas/pdm-coverage.ts — the trace/rare-mineral coverage metric schema
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Validates dashboard/assets/data/pdm-coverage-data.json (GENERATED by
 * eden/tools/pdm_coverage_derive.py) at the Zod boundary in state/coverage.ts.
 *
 * The 33 trace_pdm rare-earths carry no individual Wallach dose; they are scored
 * as ONE group against Wallach's plant-derived colloidal-mineral dose — the sum of
 * each regimen product's vehicle mg over goal.maintenance_mg. §00.A: the goal is a
 * Wallach dose expressed in mg via composition (it cites source_claim_id); each
 * per-product pdm_mg is product COMPOSITION, never a target. No number is authored
 * in a view (R1/R4) — this whole file is a pillar+judgment projection.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/** Root shape of pdm-coverage-data.json (the `_purpose` header key is ignored). */
export const PdmCoverageSchema = z.object({
  goal: z.object({
    maintenance_mg: z.number(),
    therapeutic_mg: z.number(),
    unit: z.string(),
    source_claim_id: z.string(),
  }).passthrough(),
  group_factors: z.record(z.number()).optional(),
  products: z.record(z.object({
    canonical_name: z.string(),
    pdm_mg: z.number(),
    present: z.boolean(),
  }).passthrough()),
}).passthrough();
export type PdmCoverage = z.infer<typeof PdmCoverageSchema>;
