/**
 * core/schemas/search.ts — Zod schemas for the Search subsystem
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Narrows the ONE derived Search artifact:
 *   - dashboard/assets/data/search/search-index.json — GENERATED by
 *     eden/tools/search_index_derive.py from the two hand-authored SOURCE files
 *     (eden/corpus/search-enrichment.json + eden/catalog/search-entities.json) JOINED
 *     with the sealed corpus. Freshness-gated by derived_artifacts_fresh (R1); shape +
 *     content gated by search_index_wellformed. Shape:
 *       { books: { book_id → {title, year} },
 *         entities: { slug → {display_name, type, symbol?, synonyms, related, claim_count} },
 *         claims: [ {id, subject, also_about, facet, question, answer_short, answer,
 *                    verbatim, page, book_id, topics, tier1_link?} ] }
 *
 * `answer` + `verbatim` are byte-faithful projections of the sealed corpus; the schema
 * only VALIDATES shape — it never invents content. (Superseded the thin-slice mercury-slice
 * + hand search-entities drafts once the Mercury format was signed off, 2026-07-09.)
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { z } from 'zod';

/**
 * The closed facet taxonomy (search-corpus doctrine §4A / blueprint §4A). MUST mirror
 * eden/tools/search_index_derive.py SEARCH_FACETS. Ordered as the entity page renders its
 * sections top-to-bottom, so state/view read the display order straight off this list (no
 * second 13-element literal, which would trip views_state_no_inline_data — this lives in
 * core, which is exempt). Gated by search_index_wellformed (facet ∈ this set).
 */
export const SEARCH_FACETS = [
  'basics', 'warning', 'discovery', 'etymology', 'physiology', 'mechanism', 'sources',
  'uses', 'stance', 'protocol', 'history', 'big_question', 'biography',
] as const;
export const SearchFacetSchema = z.enum(SEARCH_FACETS);
export type SearchFacet = z.infer<typeof SearchFacetSchema>;

/** Human, uppercase section headers for the entity page — one per facet (short UI labels, not prose). */
export const FACET_LABEL: Record<SearchFacet, string> = {
  basics: 'BASICS',
  discovery: 'DISCOVERY',
  etymology: 'ETYMOLOGY',
  physiology: 'IN THE BODY',
  mechanism: 'HOW IT WORKS',
  sources: 'SOURCES & EXPOSURE',
  uses: 'USES',
  stance: 'WALLACH’S STANCE',
  protocol: 'WHAT TO DO',
  warning: 'WARNINGS',
  history: 'HISTORY & LORE',
  big_question: 'BIG QUESTIONS',
  biography: 'BIOGRAPHY',
};

/**
 * Per-entity-type facet DISPLAY order. A type absent here uses SEARCH_FACETS (the default order).
 * Conditions lead with Wallach's thesis (stance) → how-it-works → what-to-do → warnings, because a
 * disease page's compelling content is the cause + cure, not a diagnostic caution (Luneth 2026-07-09).
 * Each ordering MUST list all 13 facets so none is ever dropped from an entity page.
 */
export const FACET_ORDER_BY_TYPE: Record<string, readonly SearchFacet[]> = {
  condition: [
    'stance', 'mechanism', 'protocol', 'warning', 'physiology', 'basics', 'sources',
    'uses', 'history', 'big_question', 'biography', 'discovery', 'etymology',
  ],
};

/** Dual-home pointer — the operational tier-1 slugs a search claim ALSO feeds (never leaks the other way). */
export const Tier1LinkSchema = z.object({
  essentials: z.array(z.string()).optional(),
  conditions: z.array(z.string()).optional(),
  symptoms: z.array(z.string()).optional(),
});
export type Tier1Link = z.infer<typeof Tier1LinkSchema>;

/** One faceted search claim (the de-blobbed record — answer, verbatim, cite are separate layers). */
export const SearchClaimSchema = z.object({
  id: z.string(),
  /** Primary entity slug this claim is about (→ the entity registry). */
  subject: z.string(),
  /** Secondary entity slugs for cross-surfacing. */
  also_about: z.array(z.string()),
  facet: SearchFacetSchema,
  /** The plain-language question this answers (powers Ask + the question-inventory). */
  question: z.string(),
  /** ≤160-char one-line answer (the palette/preview line). */
  answer_short: z.string(),
  /** Modern-voice explanation — NO inline verbatim (byte-faithful from the sealed claim's summary). */
  answer: z.string(),
  /** Wallach's exact words (byte-faithful; the separate verbatim layer). */
  verbatim: z.string(),
  /** Source page in the book (composed into the display cite with the index's book meta — never hand-typed). */
  page: z.number().nullable(),
  /** The book this claim is from (→ the index `books` map for the composed cite). */
  book_id: z.string().nullable(),
  /** Routing handles for retrieval (search-topic:* space). */
  topics: z.array(z.string()),
  tier1_link: Tier1LinkSchema.optional(),
}).passthrough();
export type SearchClaim = z.infer<typeof SearchClaimSchema>;

/** Book meta the index composes its citation display from (one source; no per-claim duplication). */
export const SearchBookMetaSchema = z.object({
  title: z.string(),
  year: z.number(),
}).passthrough();
export type SearchBookMeta = z.infer<typeof SearchBookMetaSchema>;

/** One registry entity (display + retrieval facets + derived claim count). */
export const SearchEntitySchema = z.object({
  display_name: z.string(),
  type: z.enum(['element', 'nutrient', 'substance', 'condition', 'concept', 'topic', 'person', 'event']),
  symbol: z.string().optional(),
  synonyms: z.array(z.string()),
  related: z.array(z.string()),
  /** Derived count of claims whose subject is this entity (index-time, for the header readout). */
  claim_count: z.number(),
}).passthrough();
export type SearchEntity = z.infer<typeof SearchEntitySchema>;

/** Root of the derived Search index artifact. */
export const SearchIndexSchema = z.object({
  books: z.record(z.string(), SearchBookMetaSchema),
  entities: z.record(z.string(), SearchEntitySchema),
  claims: z.array(SearchClaimSchema),
}).passthrough();
export type SearchIndex = z.infer<typeof SearchIndexSchema>;
