#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// build.mjs — cross-platform dashboard build
// ═══════════════════════════════════════════════════════════════════════════
// Usage:    node tools/build.mjs        OR    npm run build  (from dashboard/)
// Output:   dashboard/assets/js/dist/main.js  (committed runtime contract)
//           dashboard/assets/js/dist/main.js.map  (source map)
//           dashboard/assets/vendor/tesseract/worker-offline.js  (bundled-model OCR worker)
//
// What this does:
//   1. Verifies devDependencies are installed (suggests `npm install` if not)
//   2. Runs `tsc --noEmit` for type-checking only
//   3. Runs esbuild to bundle .ts → single browser-runnable IIFE
//   3b. Regenerates the offline OCR worker (bundled model, for raw file:// use)
//   4. Verifies the output exists + is non-empty
//
// Works identically on Windows PowerShell, macOS Terminal, Linux bash.
// No shell-script dependency — one build entry point on every platform.
// ═══════════════════════════════════════════════════════════════════════════

import { execSync } from 'node:child_process';
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DASH = resolve(ROOT, 'dashboard');
const ENTRY = resolve(DASH, 'assets/js/src/main.ts');
const OUT = resolve(DASH, 'assets/js/dist/main.js');

function step(msg) { console.log(`→ ${msg}`); }
function ok(msg)   { console.log(`✓ ${msg}`); }
function fail(msg) { console.error(`✗ ${msg}`); process.exit(1); }

function run(cmd, cwd) {
  try {
    execSync(cmd, { cwd, stdio: 'inherit', shell: process.platform === 'win32' });
  } catch (err) {
    fail(`Command failed: ${cmd}`);
  }
}

// ─── 1. Check devDependencies ──────────────────────────────────────────
if (!existsSync(resolve(DASH, 'node_modules'))) {
  step('node_modules missing — running `npm install` in dashboard/');
  run('npm install --no-audit --no-fund', DASH);
}

// ─── 2. Type-check ─────────────────────────────────────────────────────
step('Type-checking (tsc --noEmit)…');
run('npx tsc --noEmit', DASH);

// ─── 3. Bundle ─────────────────────────────────────────────────────────
step('Bundling with esbuild…');
const esbuildCmd = [
  'npx esbuild',
  `"${ENTRY}"`,
  '--bundle',
  '--format=iife',
  '--target=es2022',
  '--platform=browser',
  '--sourcemap',
  `--outfile="${OUT}"`,
].join(' ');
run(esbuildCmd, DASH);

// ─── 3b. Offline OCR worker ────────────────────────────────────────────
step('Building the offline OCR worker (bundled model)…');
buildOfflineOcrWorker();

// ─── 4. Verify output ──────────────────────────────────────────────────
if (!existsSync(OUT) || statSync(OUT).size === 0) {
  fail(`Build produced empty or missing output: ${OUT}`);
}
const sizeKB = (statSync(OUT).size / 1024).toFixed(1);
ok(`Build OK · ${OUT} (${sizeKB} KB)`);

// ═══════════════════════════════════════════════════════════════════════════
// The offline OCR worker: one self-contained file =
//   [model base64]  +  [fetch patch]  +  [the vendored worker.min.js]
// On a raw file:// open the browser blocks fetch() of the local model, so state/ocr.ts uses
// THIS worker (bundled model, no fetch). Over http/https it uses the lean worker.min.js and a
// normal fetch. Regenerated here so it can never drift from the worker.min.js / eng.traineddata.gz
// it derives from. Idempotent: the 17MB write is skipped when nothing changed.
// ═══════════════════════════════════════════════════════════════════════════
function buildOfflineOcrWorker() {
  const TDIR = resolve(DASH, 'assets/vendor/tesseract');
  const gzPath = resolve(TDIR, 'lang-data/eng.traineddata.gz');
  const workerMinPath = resolve(TDIR, 'worker.min.js');
  if (!existsSync(gzPath) || !existsSync(workerMinPath)) {
    ok('offline OCR worker skipped — vendored Tesseract not present (run tools/vendor-tesseract.js)');
    return;
  }
  const fetchPatch = [
    "/* Wallach Codex offline patch (generated by tools/build.mjs): serve the bundled model to the",
    "   worker's own fetch of eng.traineddata.gz. On a raw file:// open the browser blocks fetch() of",
    "   local files, so without this the worker hangs at 'Load engine'. Over http/https the online",
    '   build uses the unpatched worker.min.js and a normal fetch. */',
    '(function () {',
    "  var real = (typeof self.fetch === 'function') ? self.fetch.bind(self) : null;",
    '  self.fetch = function (input, init) {',
    "    var url = (typeof input === 'string') ? input : (input && input.url) || '';",
    "    if (url.indexOf('traineddata') !== -1 && self.WALLACH_TRAINEDDATA) {",
    '      var bin = atob(self.WALLACH_TRAINEDDATA);',
    '      var n = bin.length, bytes = new Uint8Array(n);',
    '      for (var i = 0; i < n; i++) { bytes[i] = bin.charCodeAt(i); }',
    "      return Promise.resolve(new Response(bytes, { status: 200, headers: { 'Content-Type': 'application/octet-stream' } }));",
    '    }',
    '    if (real) { return real(input, init); }',
    "    return Promise.reject(new Error('fetch unavailable in offline OCR worker'));",
    '  };',
    '})();',
  ].join('\n');
  const b64 = readFileSync(gzPath).toString('base64');
  const workerMin = readFileSync(workerMinPath, 'utf8');
  const combined = `self.WALLACH_TRAINEDDATA="${b64}";\n${fetchPatch}\n\n${workerMin}`;
  const outPath = resolve(TDIR, 'worker-offline.js');
  if (existsSync(outPath) && readFileSync(outPath, 'utf8') === combined) {
    ok('offline OCR worker already in sync');
    return;
  }
  writeFileSync(outPath, combined);
  ok(`offline OCR worker rebuilt (${(Buffer.byteLength(combined) / 1048576).toFixed(1)} MB)`);
}
