#!/usr/bin/env python3
"""Audit every header-research dossier against the SEALED corpus.

WHY: three dossiers in a row (vitamin-b2, vitamin-b5, and B6 before them) turned out to
carry claims that are no longer true -- dead claim ids after a reseal, understated claim
counts, and flat statements that some kind of material "does not exist in the pack" when
it demonstrably does now. Each of those cost real design time or nearly suppressed a
concept that Luneth then picked. Reading 48 files by eye would miss the same things.

Three machine-checkable failures:
  DEAD ID       a cited WAL-CLM-... is not in the sealed corpus
  STALE COUNT   the dossier's stated "N sealed claims" is below what the corpus now holds
  BLIND SPOT    the dossier asserts some material is absent, while claims of that facet
                exist -- reported as a candidate for human review, never auto-judged

The third cannot be decided by a machine (the assertion may be about a narrower thing than
the facet name), so it is surfaced with the evidence and left to a person.
"""
import collections
import glob
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(r"C:\Users\Light\Desktop\claude\health expert")
DOSS = ROOT / "chronicle" / "header-research"
OUT = pathlib.Path(__file__).resolve().parent / "dossier-sweep.md"

claims = {}
for p in sorted(glob.glob(str(ROOT / "eden" / "corpus" / "claims" / "*.json"))):
    d = json.loads(pathlib.Path(p).read_text(encoding="utf-8"))
    for c in (d["claims"] if isinstance(d, dict) and "claims" in d else d):
        claims[c["id"]] = c
if not claims:
    sys.exit("FATAL: no sealed claims loaded")

enr = {}
for p in glob.glob(str(ROOT / "eden" / "corpus" / "**" / "*enrich*.json"), recursive=True):
    try:
        d = json.loads(pathlib.Path(p).read_text(encoding="utf-8"))
    except Exception:
        continue
    src = d.get("entries") or d.get("enrichment") or (d if isinstance(d, dict) else {})
    if isinstance(src, dict):
        for k, v in src.items():
            if isinstance(v, dict):
                enr[k] = v


def entity_claims(slug):
    """Same matcher claim_review uses, so counts are comparable to what a session sees."""
    out = []
    for c in claims.values():
        e = enr.get(c["id"], {})
        if (slug in (c.get("essentials") or []) or slug in (c.get("conditions") or [])
                or slug in (c.get("symptoms") or []) or slug in (c.get("other_substances") or [])
                or e.get("subject") == slug or slug in (e.get("also_about") or [])):
            out.append(c)
    return out


# phrases that assert absence -- the shape that burned B2 and B5
NEG = re.compile(
    r"(no [a-z\- ]{0,28}(claim|material|fact|angle|concept|anecdote|history|etymology|source)"
    r"|not in (any|the) (claim|pack)|do not use|do NOT use|is NOT in|unsupported"
    r"|does not exist|absent|flagged rather than invented|never states)", re.I)

FACET_WORDS = {
    "discovery": ["discovery", "history", "etymology", "discovered", "named"],
    "sources": ["food", "source", "where to get"],
    "warning": ["toxicity", "overdose", "warning", "interaction"],
    "mechanism": ["mechanism", "how it works"],
    "basics": ["definition", "what is"],
    "stance": ["stance", "prevalence"],
}

rows = []
for f in sorted(DOSS.glob("*.md")):
    if f.name in ("README.md",):
        continue
    txt = f.read_text(encoding="utf-8")
    slug = f.stem
    cited = sorted(set(re.findall(r"WAL-CLM-[A-Z]+-\d+", txt)))
    dead = [i for i in cited if i not in claims]
    ec = entity_claims(slug)
    m = re.search(r"(\d+)\s+sealed claims", txt)
    stated = int(m.group(1)) if m else None
    actual = len(ec)
    facets = collections.Counter()
    kinds = collections.Counter()
    for c in ec:
        kinds[c["kind"]] += 1
        fx = enr.get(c["id"], {}).get("facet")
        if fx:
            facets[fx] += 1
    neg_lines = [ln.strip("- *").strip() for ln in txt.splitlines() if NEG.search(ln)]
    rows.append({"slug": slug, "cited": len(cited), "dead": dead, "stated": stated,
                 "actual": actual, "kinds": kinds, "facets": facets,
                 "neg": neg_lines[:6]})

# ── report ─────────────────────────────────────────────────────────────────────────────
dead_rows = [r for r in rows if r["dead"]]
stale_rows = [r for r in rows if r["stated"] is not None and r["actual"] > r["stated"]]
blind_rows = [r for r in rows if r["neg"]]
clean = [r for r in rows if not r["dead"] and not (r["stated"] and r["actual"] > r["stated"])]

L = []
L.append("# Header-research dossier sweep")
L.append("")
L.append("> Generated by `temporary/build-scripts/dossier-sweep.py` against the SEALED corpus. "
         "Regenerate, never hand-edit.")
L.append("")
L.append("## Why this exists")
L.append("")
L.append("Three dossiers in a row (B6, then vitamin-b2, then vitamin-b5) turned out to assert things that "
         "are no longer true. Each cost design time, and two of them nearly suppressed a concept Luneth then "
         "picked: B2's *\"The glow that named it\"* and B5's *\"Found by accident\"* are both built on material "
         "their dossier says does not exist. A dossier is a **head start, not an authority** -- this sweep says "
         "which ones can still be trusted and which must be re-verified before use.")
L.append("")
L.append("## Summary")
L.append("")
L.append("| check | dossiers |")
L.append("|---|---|")
L.append("| audited | **%d** |" % len(rows))
L.append("| cite at least one DEAD claim id | **%d** |" % len(dead_rows))
L.append("| understate their claim count | **%d** |" % len(stale_rows))
L.append("| assert some material is ABSENT (needs eyes) | **%d** |" % len(blind_rows))
L.append("| no dead ids and no undercount | **%d** |" % len(clean))
L.append("")

L.append("## 1 · Dead claim ids — hard failures, fix before quoting")
L.append("")
if dead_rows:
    L.append("| dossier | dead ids |")
    L.append("|---|---|")
    for r in sorted(dead_rows, key=lambda r: -len(r["dead"])):
        L.append("| `%s` | %s |" % (r["slug"], ", ".join("`%s`" % d for d in r["dead"])))
else:
    L.append("_None. Every cited id in every dossier resolves in the sealed corpus._")
L.append("")

L.append("## 2 · Understated claim counts — new material exists that the dossier never saw")
L.append("")
L.append("The dossier's own header says *N sealed claims*; the corpus now holds more. The gap is where "
         "concepts get wrongly ruled out.")
L.append("")
L.append("| dossier | dossier says | corpus now has | gap | kinds now available |")
L.append("|---|---|---|---|---|")
for r in sorted(stale_rows, key=lambda r: -(r["actual"] - r["stated"])):
    kk = ", ".join("%s×%d" % (k, v) for k, v in r["kinds"].most_common(6))
    L.append("| `%s` | %d | **%d** | **+%d** | %s |"
             % (r["slug"], r["stated"], r["actual"], r["actual"] - r["stated"], kk))
L.append("")

L.append("## 3 · Absence assertions — every one needs a human check")
L.append("")
L.append("Lines matching the shape that burned B2 and B5 (*\"no discovery material\"*, *\"do not use\"*, "
         "*\"not in any claim\"*). **This is a candidate list, not a verdict** — a machine cannot tell whether "
         "an assertion is about something narrower than the facet it mentions. Check each against the "
         "kinds column above before trusting it.")
L.append("")
for r in sorted(blind_rows, key=lambda r: r["slug"]):
    gap = (r["actual"] - r["stated"]) if r["stated"] else None
    tag = " · **undercounts by %d**" % gap if gap and gap > 0 else ""
    L.append("### `%s`%s" % (r["slug"], tag))
    L.append("")
    L.append("_kinds in corpus now: %s_" % (", ".join("%s×%d" % (k, v) for k, v in r["kinds"].most_common(8)) or "none"))
    L.append("")
    for ln in r["neg"]:
        L.append("- %s" % ln[:400])
    L.append("")

L.append("## 4 · Full table")
L.append("")
L.append("| dossier | cited ids | dead | says | actual | absence-claims |")
L.append("|---|---|---|---|---|---|")
for r in sorted(rows, key=lambda r: r["slug"]):
    L.append("| `%s` | %d | %s | %s | %d | %d |"
             % (r["slug"], r["cited"], ("**%d**" % len(r["dead"])) if r["dead"] else "0",
                r["stated"] if r["stated"] is not None else "—", r["actual"], len(r["neg"])))
L.append("")

OUT.write_text("\n".join(L), encoding="utf-8")
print("wrote", OUT)
print("audited %d dossiers | dead-id: %d | undercount: %d | absence-claims: %d"
      % (len(rows), len(dead_rows), len(stale_rows), len(blind_rows)))
for r in sorted(stale_rows, key=lambda r: -(r["actual"] - r["stated"]))[:12]:
    print("   +%-3d %-18s says %-3s now %d" % (r["actual"] - r["stated"], r["slug"], r["stated"], r["actual"]))
print("dead-id dossiers:", [r["slug"] for r in dead_rows])
