#!/usr/bin/env python3
"""
tools/tacitus_simulate.py — ephemeral simulation harness for Tacitus prompts.

Round 145 / Step 5 (2026-06-19). User direction:
  "Manually test it when the time is right... simulation meant to be deleted
   and not fully read. The 'as if it never happened' is the rule."

Purpose
=======
The real Tacitus sleeps Sat-Sun (Sabbath rest, 34-hour structural window).
But Rounds 140-145 shipped substantive prompt edits to Cura + Vision that
won't get exercised until Monday 3:48 AM EDT. This harness lets us simulate
Cura + Vision runs in /tmp WITHOUT writing to tacitus/notebook/, WITHOUT
updating tacitus/sentinel.json, and WITHOUT touching any real state.

Safety constraints (load-bearing)
=================================
1. ALL output goes to /tmp/tacitus_sim/<date>/ — never tacitus/, never memory/.
2. Reads are read-only on real state (prompts, notebook, essence, protocols).
3. The rendered simulation prompt is explicitly labeled "SIMULATION" in
   uppercase at top and bottom — impossible to confuse with a real run.
4. The rubric sheet is for human/Claude grading; not a real Aegis score.
5. After evaluation, run `tacitus_simulate.py purge` to delete /tmp/tacitus_sim/.

Usage
=====
  # Render a Cura simulation for Monday morning's prompts
  python tools/tacitus_simulate.py prepare --mode cura --date 2026-06-22

  # Render a Vision simulation
  python tools/tacitus_simulate.py prepare --mode vision --date 2026-06-22

  # Delete all sim output ("as if it never happened")
  python tools/tacitus_simulate.py purge

  # Show what would be deleted
  python tools/tacitus_simulate.py purge --dry-run
"""

import argparse
import datetime
import os
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIM_ROOT = pathlib.Path("/tmp/tacitus_sim")

# Safety: refuse to operate anywhere except /tmp/tacitus_sim
def _assert_sim_path(p: pathlib.Path) -> None:
    rp = p.resolve()
    if not str(rp).startswith("/tmp/tacitus_sim"):
        sys.exit(f"REFUSED: simulation paths must live under /tmp/tacitus_sim. Got: {rp}")


SIM_BANNER = """
============================================================================
SIMULATION — EPHEMERAL — NOT A REAL TACITUS RUN
============================================================================
This file was generated by tools/tacitus_simulate.py for the purpose of
exercising Tacitus prompts WITHOUT writing to tacitus/notebook/ or updating
tacitus/sentinel.json. Any output produced from this simulation is:
  - NOT a real reflection
  - NOT to be merged into the real notebook
  - NOT to be scored by real Aegis
  - meant to be DELETED after evaluation (`tacitus_simulate.py purge`)
"as if it never happened" — user directive, Round 145 / Step 5
============================================================================
"""

SIM_BANNER_END = """
============================================================================
END SIMULATION CONTEXT — produced output is ephemeral, delete after grading.
============================================================================
"""


def _read_safe(rel: str) -> str:
    p = ROOT / rel
    if not p.exists():
        return f"[MISSING: {rel}]"
    return p.read_text(encoding="utf-8")


def _tail_lines(text: str, n: int) -> str:
    lines = text.splitlines()
    return "\n".join(lines[-n:])


def _last_n_round_entries(saga_text: str, n: int) -> str:
    """Return the last n round entries from saga.md."""
    import re
    pattern = re.compile(r"^## Round\s+\d+", re.MULTILINE)
    matches = list(pattern.finditer(saga_text))
    if not matches:
        return _tail_lines(saga_text, 200)
    if len(matches) <= n:
        start = matches[0].start()
    else:
        start = matches[-n].start()
    return saga_text[start:]


def prepare(mode: str, date_str: str) -> pathlib.Path:
    """Render a simulation prompt + rubric for the given mode + date."""
    if mode not in ("cura", "vision"):
        sys.exit(f"unsupported mode: {mode} (cura | vision)")

    sim_dir = SIM_ROOT / date_str
    _assert_sim_path(sim_dir)
    sim_dir.mkdir(parents=True, exist_ok=True)

    # Read all the inputs the mode's prompt mandates
    inputs = {}
    inputs["prompt"] = _read_safe(f"tacitus/prompts/{mode}.md")
    inputs["identity"] = _read_safe("tacitus/identity.md")
    inputs["changelog"] = _read_safe("tacitus/changelog.md")
    inputs["sentinel"] = _read_safe("tacitus/sentinel.json")
    inputs["open_threads"] = _read_safe("memory/open-threads.md")
    inputs["operating_protocols"] = _read_safe("memory/operating-protocols.md")
    inputs["engineering_doctrine"] = _read_safe("memory/engineering-doctrine.md")
    inputs["feature_flags"] = _read_safe("tacitus/feature-flags.json")
    inputs["verified_patterns"] = _read_safe("memory/verified-patterns.md")

    saga = _read_safe("memory/essence/saga.md")
    inputs["saga_tail"] = _last_n_round_entries(saga, 5)

    lessons = _read_safe("memory/essence/lessons.md")
    inputs["lessons_tail"] = _tail_lines(lessons, 400)

    decisions = _read_safe("memory/essence/decisions.md")
    inputs["decisions_tail"] = _tail_lines(decisions, 200)

    notebook_month = date_str[:7]  # YYYY-MM
    inputs["notebook_recent"] = _read_safe(f"tacitus/notebook/{notebook_month}.md")

    if mode == "cura":
        inputs["source_rule"] = _read_safe("memory/source-rule.md")
        inputs["claude_best_practices"] = _read_safe("memory/claude-best-practices.md")
        inputs["audit_sentinel"] = _read_safe("memory/system/audit-sentinel.json")
    if mode == "vision":
        inputs["user_goals"] = _read_safe("memory/user-goals.md")
        inputs["design_knowledge"] = _read_safe("memory/design-knowledge.md")
        inputs["co_work_workflow"] = _read_safe("memory/co-work-design-workflow.md")
        inputs["aesthetic"] = _read_safe("memory/user-prefs/aesthetic.md")

    # Render the simulation prompt — full context inlined so a fresh Claude
    # session can be fed the file directly with no further file access
    render = [SIM_BANNER]
    render.append(f"## SIMULATED DATE: {date_str}")
    render.append(f"## SIMULATED MODE: {mode.upper()}")
    render.append("")
    render.append("Below is the full context bundle this Tacitus mode would")
    render.append("normally read at session start. Read it all, then produce")
    render.append("the standard Phase 1 → Phase 2 → Phase 3 → Phase 4 output")
    render.append("as the prompt's structure mandates. DO NOT write to any")
    render.append("real file; output goes only to chat (the simulator captures")
    render.append("the chat output in a separate /tmp file).")
    render.append("")
    render.append("---")
    render.append(f"## INPUT 1 — tacitus/prompts/{mode}.md (THE PROMPT)")
    render.append("")
    render.append(inputs["prompt"])
    render.append("\n---\n## INPUT 2 — tacitus/identity.md\n")
    render.append(inputs["identity"])
    render.append("\n---\n## INPUT 3 — tacitus/changelog.md\n")
    render.append(inputs["changelog"])
    render.append("\n---\n## INPUT 4 — tacitus/sentinel.json (READ-ONLY)\n```json\n")
    render.append(inputs["sentinel"])
    render.append("\n```\n")
    render.append("\n---\n## INPUT 5 — tacitus/feature-flags.json\n```json\n")
    render.append(inputs["feature_flags"])
    render.append("\n```\n")
    render.append("\n---\n## INPUT 6 — memory/open-threads.md\n")
    render.append(inputs["open_threads"])
    render.append("\n---\n## INPUT 7 — memory/essence/saga.md (LAST 5 ROUNDS)\n")
    render.append(inputs["saga_tail"])
    render.append("\n---\n## INPUT 8 — memory/essence/lessons.md (TAIL 400 LINES)\n")
    render.append(inputs["lessons_tail"])
    render.append("\n---\n## INPUT 9 — memory/essence/decisions.md (TAIL 200 LINES)\n")
    render.append(inputs["decisions_tail"])
    render.append("\n---\n## INPUT 10 — memory/operating-protocols.md\n")
    render.append(inputs["operating_protocols"])
    render.append("\n---\n## INPUT 11 — memory/engineering-doctrine.md\n")
    render.append(inputs["engineering_doctrine"])
    render.append("\n---\n## INPUT 12 — memory/verified-patterns.md\n")
    render.append(inputs["verified_patterns"])
    render.append(f"\n---\n## INPUT 13 — tacitus/notebook/{notebook_month}.md (RECENT)\n")
    render.append(inputs["notebook_recent"])

    if mode == "cura":
        render.append("\n---\n## INPUT 14 — memory/source-rule.md\n")
        render.append(inputs["source_rule"])
        render.append("\n---\n## INPUT 15 — memory/claude-best-practices.md\n")
        render.append(inputs["claude_best_practices"])
        render.append("\n---\n## INPUT 16 — memory/system/audit-sentinel.json (READ-ONLY)\n```json\n")
        render.append(inputs["audit_sentinel"])
        render.append("\n```\n")
    if mode == "vision":
        render.append("\n---\n## INPUT 14 — memory/user-goals.md\n")
        render.append(inputs["user_goals"])
        render.append("\n---\n## INPUT 15 — memory/design-knowledge.md\n")
        render.append(inputs["design_knowledge"])
        render.append("\n---\n## INPUT 16 — memory/co-work-design-workflow.md (Round 145 ship)\n")
        render.append(inputs["co_work_workflow"])
        render.append("\n---\n## INPUT 17 — memory/user-prefs/aesthetic.md\n")
        render.append(inputs["aesthetic"])

    render.append(SIM_BANNER_END)
    rendered = "\n".join(render)

    prompt_path = sim_dir / f"{mode}-prompt-rendered.md"
    _assert_sim_path(prompt_path)
    prompt_path.write_text(rendered, encoding="utf-8")

    # Render the rubric — grading sheet for the human/Claude evaluator
    rubric = _rubric_for_mode(mode, date_str)
    rubric_path = sim_dir / f"{mode}-rubric.md"
    _assert_sim_path(rubric_path)
    rubric_path.write_text(rubric, encoding="utf-8")

    # Index file
    index = f"""# Simulation Index — {date_str} / {mode.upper()}

{SIM_BANNER}

## Files in this sim
- `{prompt_path.name}` — full context bundle to feed a fresh Claude session
- `{rubric_path.name}` — grading sheet for evaluating the produced output

## How to run the sim
1. Open a fresh Claude session (so no project context pre-loads).
2. Paste the contents of `{prompt_path.name}` as the user message.
3. Capture the assistant's response to `/tmp/tacitus_sim/{date_str}/{mode}-response-iter-N.md`.
4. Apply `{rubric_path.name}` to score the response.
5. If the response misses the bar, iterate the actual prompt at
   `tacitus/prompts/{mode}.md` (via safe_write), re-prepare the sim, and re-run.
6. When satisfied: `python tools/tacitus_simulate.py purge` to delete this dir.

## Reminder of the "as if it never happened" rule
After grading, ALL sim output gets deleted. Findings (if any) get codified
into the real project (lessons.md, prompt edits via safe_write, etc.). The
sim dir itself is ephemeral.
"""
    index_path = sim_dir / "README.md"
    _assert_sim_path(index_path)
    index_path.write_text(index, encoding="utf-8")

    print(f"Simulation prepared at {sim_dir}")
    print(f"  - {prompt_path.name} ({len(rendered):,} bytes)")
    print(f"  - {rubric_path.name}")
    print(f"  - README.md")
    print()
    print("Next step: feed prompt-rendered.md to a fresh Claude session, capture")
    print(f"  the response, then apply the rubric. When done: tacitus_simulate.py purge")
    return sim_dir


def _rubric_for_mode(mode: str, date_str: str) -> str:
    """Mode-specific rubric for grading the simulated output."""
    if mode == "cura":
        return f"""# Cura Simulation Rubric — {date_str}

{SIM_BANNER}

## Phase 1 (Scan) — score 0-5 per sub-check
- [ ] Bug sub-check produced at least 1 candidate
- [ ] Contradiction sub-check produced at least 1 candidate
- [ ] Integrity-of-information sub-check produced at least 1 candidate
- [ ] Architectural-tension sub-check produced at least 1 candidate (Round 140 verified-pattern question gated on feature flag — check if Cura noticed and gated correctly)
- [ ] Translation-quality sub-check (Round 136) produced at least 1 candidate (5-sub-check architecture must be exercised)

## Phase 2 (Prune) — score 0-5
- [ ] Each candidate evaluated against the appropriate gates
- [ ] LAND / NEAR-MISS / CONSIDERED classifications are reasoned, not arbitrary
- [ ] At least 1 LAND survivor (NEVER-zero-output safeguard honored)

## Phase 3 (Deepen) — score 0-5
- [ ] Each LAND survivor has structural detail: WHAT to ship, WHERE in the codebase, WHY
- [ ] Paired-detector discipline: every shipped lesson cites the paired invariant per §18

## Phase 4 (Cross-pollinate) — score 0-5
- [ ] Cross-pollination notes if any (sub-check adjacencies, NEAR-MISS reasoning)

## Phase 5 (Self-audit) — score 0-5
- [ ] Run-level score produced + reasoning
- [ ] No silent degradation flags
- [ ] Soft self-criticism is graded harshly per prompt's anti-pattern guidance

## Round 140-145 specific checks
- [ ] Architectural sub-check honored the verified-pattern question (feature flag was true)
- [ ] If a LAND involves a saga entry, did Cura suggest the `**Patterns consulted:**` marker per §27?
- [ ] If a LAND involves a major feature, did Cura suggest the rollback recipe per §28?
- [ ] Did Cura reference the Round 145 co-work design workflow if a design-surface LAND emerged?

## Quality bar
- Total score >= 26/35 = pass (prompt is fit for Monday)
- Total score 18-25/35 = revise prompt and re-sim
- Total score < 18/35 = significant prompt rework needed; surface to user

{SIM_BANNER_END}
"""
    # vision
    return f"""# Vision Simulation Rubric — {date_str}

{SIM_BANNER}

## Phase 1 (Scan) — score 0-5
- [ ] Produced 5-8 candidates
- [ ] Each candidate is one sentence (not deep-dived prematurely)
- [ ] At least 1 candidate is structurally novel (not just "more of the same")

## Pattern-seed candidate (Round 140 + Round 145) — load-bearing checks
- [ ] If `vision_pattern_seed.enabled == true`, Vision considered a pattern-seed candidate
- [ ] HARD CAP honored: at most ONE pattern-seed candidate produced
- [ ] If candidate emerged, full required structure present:
  - [ ] Target surface (file path + selector + state description)
  - [ ] Source pattern (name + URL from verified-patterns.md or design-knowledge.md)
  - [ ] Starter code (parameter-tuned, NOT generic)
  - [ ] Search-term suggestions (Round 145 OPTIONAL field) — if present, Vision did NOT claim to have searched
  - [ ] Seed-not-propagate framing present VERBATIM: "This is a SEED proposal — Vision cannot verify rendered output... Vision does NOT propose surface-cascade."
- [ ] If NO direct catalog match for an unmistakable design surface, Vision wrote "no pattern-seed candidate" (did NOT manufacture)

## Phase 2 (Prune) — score 0-5
- [ ] All three gates applied (Alignment / Non-duplication / User-would-recognize-as-good)
- [ ] LAND survivors are 1-2 (the prompt cap)
- [ ] NEAR-MISS / CONSIDERED entries have elimination reasoning (NEVER-zero-output safeguard)

## Phase 3 (Deepen) — score 0-5
- [ ] LAND survivors have full structural detail
- [ ] Goal/principle alignment named specifically (not generic)

## Phase 4 (Closing) — score 0-5
- [ ] Run-level score + reasoning
- [ ] No batch-conversion proposals (Round 140 critical discipline)

## Quality bar
- Total score >= 20/25 = pass
- Total score 12-19/25 = revise prompt and re-sim
- Total score < 12/25 = significant prompt rework needed; surface to user

## Discipline check (auto)
- [ ] Run `python tools/invariants.py --only vision_pattern_seed_compliance` BEFORE the sim
- [ ] Confirm all 4 structural arms intact (feature-flag gate + HARD CAP + framing + batch/cascade prohibition)

{SIM_BANNER_END}
"""


def purge(dry_run: bool = False) -> None:
    """Delete /tmp/tacitus_sim entirely. 'As if it never happened.'"""
    if not SIM_ROOT.exists():
        print(f"{SIM_ROOT} does not exist — nothing to purge.")
        return
    _assert_sim_path(SIM_ROOT)
    if dry_run:
        print(f"DRY-RUN: would delete {SIM_ROOT} and all contents:")
        for p in sorted(SIM_ROOT.rglob("*")):
            print(f"  {p}")
        return
    shutil.rmtree(SIM_ROOT)
    print(f"Purged {SIM_ROOT} — as if it never happened.")


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    prep = sub.add_parser("prepare", help="Render simulation prompt + rubric")
    prep.add_argument("--mode", choices=["cura", "vision"], required=True)
    prep.add_argument("--date", default=None,
                      help="Simulated date YYYY-MM-DD (default: next Monday)")

    purge_p = sub.add_parser("purge", help="Delete all sim output")
    purge_p.add_argument("--dry-run", action="store_true",
                        help="Show what would be deleted without deleting")

    args = p.parse_args()

    if args.cmd == "prepare":
        if args.date is None:
            today = datetime.date.today()
            days_until_monday = (0 - today.weekday()) % 7
            if days_until_monday == 0:
                days_until_monday = 7
            target = today + datetime.timedelta(days=days_until_monday)
            args.date = target.strftime("%Y-%m-%d")
        prepare(args.mode, args.date)
    elif args.cmd == "purge":
        purge(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
